"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x122D5F  (58 instructions, 18 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, DF, IF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x122D5F
SIGNATURE = bytes.fromhex('668b4e02668b2d5e')
MAX_ITERATIONS = 290000


def lift_122d5f(cpu):
    """Lifted replacement for flat 0x122D5F."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_122d5f')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x122D5F  668b4e02       mov
            _o = (sb["ds"] + r[6] + 0x2) & 0xFFFFFFFF
            r[1] = (r[1] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x122D63  668b2d5ee31400 mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[5] = (r[5] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x122D6A  6603ed         add
            _a = r[5] & 0xFFFF
            _b = r[5] & 0xFFFF
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            r[5] = (r[5] & 0xFFFF0000) | ((_r & 0xFFFF) & 0xFFFF)
            # 0x122D6D  663bcd         cmp
            _a = r[1] & 0xFFFF
            _b = r[5] & 0xFFFF
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122D70  0f8798000000   jcc
            bb = 13 if cpu._cond(0x7) else 1
        elif bb == 1:
            # 0x122D76  c1c110         grp2
            cpu._shift(0, True, 1, 4, 0x10)
            # 0x122D79  668b4e04       mov
            _o = (sb["ds"] + r[6] + 0x4) & 0xFFFFFFFF
            r[1] = (r[1] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x122D7D  668b2d62e31400 mov
            _o = (sb["ds"] + 0x14E362) & 0xFFFFFFFF
            r[5] = (r[5] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x122D84  6603ed         add
            _a = r[5] & 0xFFFF
            _b = r[5] & 0xFFFF
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            r[5] = (r[5] & 0xFFFF0000) | ((_r & 0xFFFF) & 0xFFFF)
            # 0x122D87  663bcd         cmp
            _a = r[1] & 0xFFFF
            _b = r[5] & 0xFFFF
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122D8A  0f877e000000   jcc
            bb = 13 if cpu._cond(0x7) else 2
        elif bb == 2:
            # 0x122D90  0fb76e08       movzx/sx
            _o = (sb["ds"] + r[6] + 0x8) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[5] = (_v) & 0xFFFFFFFF
            # 0x122D94  66f705748314000100 grp3
            _o = (sb["ds"] + 0x148374) & 0xFFFFFFFF
            cpu._grp3_op(0, False, _o, 2, 0x1)
            # 0x122D9D  7415           jcc
            bb = 5 if cpu._cond(0x4) else 3
        elif bb == 3:
            # 0x122D9F  66f7c50200     grp3
            cpu._grp3_op(0, True, 5, 2, 0x2)
            # 0x122DA4  7421           jcc
            bb = 7 if cpu._cond(0x4) else 4
        elif bb == 4:
            # 0x122DA6  0fbf460e       movzx/sx
            _o = (sb["ds"] + r[6] + 0xE) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x122DAA  03d8           add
            _a = r[3]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122DAC  0fbf4610       movzx/sx
            _o = (sb["ds"] + r[6] + 0x10) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x122DB0  03d0           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122DB2  eb13           jmp
            bb = 7
        elif bb == 5:
            # 0x122DB4  66f7c50100     grp3
            cpu._grp3_op(0, True, 5, 2, 0x1)
            # 0x122DB9  740c           jcc
            bb = 7 if cpu._cond(0x4) else 6
        elif bb == 6:
            # 0x122DBB  0fbf460a       movzx/sx
            _o = (sb["ds"] + r[6] + 0xA) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x122DBF  03d8           add
            _a = r[3]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122DC1  0fbf460c       movzx/sx
            _o = (sb["ds"] + r[6] + 0xC) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x122DC5  03d0           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 7
        elif bb == 7:
            # 0x122DC7  8bc3           mov
            r[0] = (r[3]) & 0xFFFFFFFF
            # 0x122DC9  0bc2           or
            _a = r[0]
            _b = r[2]
            _r = _a | _b
            cpu._flags_logic(_r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122DCB  3d007d0000     cmp
            _a = r[0]
            _b = 0x7D00
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122DD0  7f47           jcc
            bb = 14 if cpu._cond(0xF) else 8
        elif bb == 8:
            # 0x122DD2  3d0083ffff     cmp
            _a = r[0]
            _b = 0xFFFF8300
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122DD7  7c40           jcc
            bb = 14 if cpu._cond(0xC) else 9
        elif bb == 9:
            # 0x122DD9  0fb74606       movzx/sx
            _o = (sb["ds"] + r[6] + 0x6) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x122DDD  3d00100000     cmp
            _a = r[0]
            _b = 0x1000
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122DE2  7f56           jcc
            bb = 15 if cpu._cond(0xF) else 10
        elif bb == 10:
            # 0x122DE4  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122DE6  83e507         grp1
            _a = r[5]
            _b = 0x7
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[5] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122DE9  66833d24e3140000 grp1
            _o = (sb["ds"] + 0x14E324) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122DF1  7505           jcc
            bb = 12 if cpu._cond(0x5) else 11
        elif bb == 11:
            # 0x122DF3  83fd05         grp1
            _a = r[5]
            _b = 0x5
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122DF6  744d           jcc
            bb = 16 if cpu._cond(0x4) else 12
        elif bb == 12:
            # 0x122DF8  c1e504         grp2
            cpu._shift(4, True, 5, 4, 0x04)
            # 0x122DFB  8dbdaa831400   lea
            r[7] = ((r[5] + 0x1483AA)) & 0xFFFFFFFF
            # 0x122E01  0fbf2d6e741400 movzx/sx
            _o = (sb["ds"] + 0x14746E) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[5] = (_v) & 0xFFFFFFFF
            # 0x122E08  8b6c3d00       mov
            _o = (sb["ss"] + r[7] + r[5]) & 0xFFFFFFFF
            r[5] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122E0C  ff27           jmp
            _o = (sb["ds"] + r[7]) & 0xFFFFFFFF
            cpu.eip = mem.r32(_o)
            return
        elif bb == 13:
            # 0x122E0E  66c7056c7414000104 mov
            _o = (sb["ds"] + 0x14746C) & 0xFFFFFFFF
            mem.w16(_o, 0x401)
            # 0x122E17  eb37           jmp
            bb = 17
        elif bb == 14:
            # 0x122E19  66c7056c7414000204 mov
            _o = (sb["ds"] + 0x14746C) & 0xFFFFFFFF
            mem.w16(_o, 0x402)
            # 0x122E22  eb2c           jmp
            bb = 17
        elif bb == 15:
            # 0x122E3A  66c7056c7414000504 mov
            _o = (sb["ds"] + 0x14746C) & 0xFFFFFFFF
            mem.w16(_o, 0x405)
            # 0x122E43  eb0b           jmp
            bb = 17
        elif bb == 16:
            # 0x122E45  66c7056c7414000604 mov
            _o = (sb["ds"] + 0x14746C) & 0xFFFFFFFF
            mem.w16(_o, 0x406)
            # 0x122E4E  eb00           jmp
            bb = 17
        elif bb == 17:
            # 0x122E50  8b3d0e841400   mov
            _o = (sb["ds"] + 0x14840E) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122E56  c70700000000   mov
            _o = (sb["ds"] + r[7]) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            # 0x122E5C  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_122d5f' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
