"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x122B94  (66 instructions, 18 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, DF, IF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x122B94
SIGNATURE = bytes.fromhex('608d6c241c0fb71d')
MAX_ITERATIONS = 330000


def lift_122b94(cpu):
    """Lifted replacement for flat 0x122B94."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_122b94')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x122B94  60             pushad
            cpu._pusha(4)
            # 0x122B95  8d6c241c       lea
            r[5] = ((r[4] + 0x1C)) & 0xFFFFFFFF
            # 0x122B99  0fb71d167b1400 movzx/sx
            _o = (sb["ds"] + 0x147B16) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[3] = (_v) & 0xFFFFFFFF
            # 0x122BA0  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x122BA3  8bbb26e31400   mov
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122BA9  03bb36e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122BAF  03bb46e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122BB5  0fb71d187b1400 movzx/sx
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[3] = (_v) & 0xFFFFFFFF
            # 0x122BBC  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x122BBF  8bb326e31400   mov
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            r[6] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122BC5  03b336e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122BCB  03b346e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122BD1  66833d24e3140001 grp1
            _o = (sb["ds"] + 0x14E324) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122BD9  7540           jcc
            bb = 7 if cpu._cond(0x5) else 1
        elif bb == 1:
            # 0x122BDB  803d85e314000f grp1
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xF
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x122BE2  7411           jcc
            bb = 3 if cpu._cond(0x4) else 2
        elif bb == 2:
            # 0x122BE4  c60585e314000f mov
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            mem.w8(_o, 0xF)
            # 0x122BEB  66b8020f       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0xF02) & 0xFFFF)
            # 0x122BEF  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x122BF3  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 3
        elif bb == 3:
            # 0x122BF5  66833d24e3140001 grp1
            _o = (sb["ds"] + 0x14E324) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122BFD  751a           jcc
            bb = 6 if cpu._cond(0x5) else 4
        elif bb == 4:
            # 0x122BFF  803d84e3140041 grp1
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x41
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x122C06  7411           jcc
            bb = 6 if cpu._cond(0x4) else 5
        elif bb == 5:
            # 0x122C08  c60584e3140041 mov
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            mem.w8(_o, 0x41)
            # 0x122C0F  66b80541       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x4105) & 0xFFFF)
            # 0x122C13  66bace03       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3CE) & 0xFFFF)
            # 0x122C17  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 6
        elif bb == 6:
            # 0x122C19  eb34           jmp
            bb = 11
        elif bb == 7:
            # 0x122C1B  803d85e314000f grp1
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xF
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x122C22  7411           jcc
            bb = 9 if cpu._cond(0x4) else 8
        elif bb == 8:
            # 0x122C24  c60585e314000f mov
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            mem.w8(_o, 0xF)
            # 0x122C2B  66b8020f       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0xF02) & 0xFFFF)
            # 0x122C2F  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x122C33  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 9
        elif bb == 9:
            # 0x122C35  803d84e3140040 grp1
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x40
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x122C3C  7411           jcc
            bb = 11 if cpu._cond(0x4) else 10
        elif bb == 10:
            # 0x122C3E  c60584e3140040 mov
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            mem.w8(_o, 0x40)
            # 0x122C45  66b80540       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x4005) & 0xFFFF)
            # 0x122C49  66bace03       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3CE) & 0xFFFF)
            # 0x122C4D  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 11
        elif bb == 11:
            # 0x122C4F  893de4e21400   mov
            _o = (sb["ds"] + 0x14E2E4) & 0xFFFFFFFF
            mem.w32(_o, r[7])
            # 0x122C55  8935e0e21400   mov
            _o = (sb["ds"] + 0x14E2E0) & 0xFFFFFFFF
            mem.w32(_o, r[6])
            # 0x122C5B  66833d6e74140004 grp1
            _o = (sb["ds"] + 0x14746E) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x4
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122C63  752a           jcc
            bb = 15 if cpu._cond(0x5) else 12
        elif bb == 12:
            # 0x122C65  8b1de8e21400   mov
            _o = (sb["ds"] + 0x14E2E8) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122C6B  891d60831400   mov
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            # 0x122C71  eb0d           jmp
            bb = 14
        elif bb == 13:
            # 0x122C73  ff148da2831400 call
            _o = (sb["ds"] + (r[1] << 2) + 0x1483A2) & 0xFFFFFFFF
            emulate_call32(cpu, mem.r32(_o), 0x122C7A)
            # 0x122C7A  8b1d60831400   mov
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            bb = 14
        elif bb == 14:
            # 0x122C80  83056083140014 grp1
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x14
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x122C87  0fb70b         movzx/sx
            _o = (sb["ds"] + r[3]) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[1] = (_v) & 0xFFFFFFFF
            # 0x122C8A  83f900         grp1
            _a = r[1]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122C8D  75e4           jcc
            bb = 13 if cpu._cond(0x5) else 15
        elif bb == 15:
            # 0x122C8F  66833d24e3140000 grp1
            _o = (sb["ds"] + 0x14E324) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x122C97  7422           jcc
            bb = 17 if cpu._cond(0x4) else 16
        elif bb == 16:
            # 0x122C99  c60585e314000f mov
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            mem.w8(_o, 0xF)
            # 0x122CA0  66b8020f       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0xF02) & 0xFFFF)
            # 0x122CA4  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x122CA8  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            # 0x122CAA  c60584e3140040 mov
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            mem.w8(_o, 0x40)
            # 0x122CB1  66b80540       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x4005) & 0xFFFF)
            # 0x122CB5  66bace03       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3CE) & 0xFFFF)
            # 0x122CB9  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 17
        elif bb == 17:
            # 0x122CBB  61             popad
            cpu._popa(4)
            # 0x122CBC  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_122b94' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
