"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x118066  (38 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, DF, IF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x118066
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 190000


def lift_118066(cpu):
    """Lifted replacement for flat 0x118066."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_118066')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x118066  53             push
            cpu.push(r[3], 4)
            # 0x118067  56             push
            cpu.push(r[6], 4)
            # 0x118068  57             push
            cpu.push(r[7], 4)
            # 0x118069  55             push
            cpu.push(r[5], 4)
            # 0x11806A  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11806C  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118072  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118075  a358e11400     mov
            _o = (sb["ds"] + 0x14E158) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11807A  e86f150000     call
            emulate_call32(cpu, 0x1195EE, 0x11807F)
            # 0x11807F  0fbf055ce11400 movzx/sx
            _o = (sb["ds"] + 0x14E15C) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118086  8d5003         lea
            r[2] = ((r[0] + 0x3)) & 0xFFFFFFFF
            # 0x118089  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11808C  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11808E  0fbf055ee11400 movzx/sx
            _o = (sb["ds"] + 0x14E15E) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118095  8d5003         lea
            r[2] = ((r[0] + 0x3)) & 0xFFFFFFFF
            # 0x118098  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11809B  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11809E  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1180A1  8b10           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1180A3  83ea03         grp1
            _a = r[2]
            _b = 0x3
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1180A6  0fbf0560e11400 movzx/sx
            _o = (sb["ds"] + 0x14E160) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1180AD  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1180AF  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1180B2  83ea05         grp1
            _a = r[2]
            _b = 0x5
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1180B5  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1180B8  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1180BB  8b5004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1180BE  83ea03         grp1
            _a = r[2]
            _b = 0x3
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1180C1  0fbf0562e11400 movzx/sx
            _o = (sb["ds"] + 0x14E162) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1180C8  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1180CA  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1180CD  83ea05         grp1
            _a = r[2]
            _b = 0x5
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1180D0  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1180D3  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1180D4  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1180D5  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1180D6  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1180D7  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_118066' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
