"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1230B7  (187 instructions, 38 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, DF, IF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x1230B7
SIGNATURE = bytes.fromhex('558bec83ec14608b')
MAX_ITERATIONS = 935000


def lift_1230b7(cpu):
    """Lifted replacement for flat 0x1230B7."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1230b7')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1230B7  55             push
            cpu.push(r[5], 4)
            # 0x1230B8  8bec           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x1230BA  83ec14         grp1
            _a = r[4]
            _b = 0x14
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1230BD  60             pushad
            cpu._pusha(4)
            # 0x1230BE  8b450c         mov
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1230C1  8b5d14         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1230C4  8b4d10         mov
            _o = (sb["ss"] + r[5] + 0x10) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1230C7  8b5518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1230CA  3bc3           cmp
            _a = r[0]
            _b = r[3]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1230CC  7e07           jcc
            bb = 2 if cpu._cond(0xE) else 1
        elif bb == 1:
            # 0x1230CE  93             xchg
            r[0], r[3] = r[3], r[0]
            # 0x1230CF  89450c         mov
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1230D2  895d14         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            bb = 2
        elif bb == 2:
            # 0x1230D5  3bca           cmp
            _a = r[1]
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1230D7  7e08           jcc
            bb = 4 if cpu._cond(0xE) else 3
        elif bb == 3:
            # 0x1230D9  87ca           xchg
            _a = r[1]
            _b = r[2]
            r[1] = (_b) & 0xFFFFFFFF
            r[2] = (_a) & 0xFFFFFFFF
            # 0x1230DB  894d10         mov
            _o = (sb["ss"] + r[5] + 0x10) & 0xFFFFFFFF
            mem.w32(_o, r[1])
            # 0x1230DE  895518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 4
        elif bb == 4:
            # 0x1230E1  3b056ee31400   cmp
            _o = (sb["ds"] + 0x14E36E) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1230E7  7d08           jcc
            bb = 6 if cpu._cond(0xD) else 5
        elif bb == 5:
            # 0x1230E9  a16ee31400     mov
            _o = (sb["ds"] + 0x14E36E) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1230EE  89450c         mov
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 6
        elif bb == 6:
            # 0x1230F1  3b1d76e31400   cmp
            _o = (sb["ds"] + 0x14E376) & 0xFFFFFFFF
            _a = r[3]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1230F7  7e09           jcc
            bb = 8 if cpu._cond(0xE) else 7
        elif bb == 7:
            # 0x1230F9  8b1d76e31400   mov
            _o = (sb["ds"] + 0x14E376) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1230FF  895d14         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            bb = 8
        elif bb == 8:
            # 0x123102  3b0d72e31400   cmp
            _o = (sb["ds"] + 0x14E372) & 0xFFFFFFFF
            _a = r[1]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x123108  7d09           jcc
            bb = 10 if cpu._cond(0xD) else 9
        elif bb == 9:
            # 0x12310A  8b0d72e31400   mov
            _o = (sb["ds"] + 0x14E372) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123110  894d10         mov
            _o = (sb["ss"] + r[5] + 0x10) & 0xFFFFFFFF
            mem.w32(_o, r[1])
            bb = 10
        elif bb == 10:
            # 0x123113  3b157ae31400   cmp
            _o = (sb["ds"] + 0x14E37A) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x123119  7e09           jcc
            bb = 12 if cpu._cond(0xE) else 11
        elif bb == 11:
            # 0x12311B  8b157ae31400   mov
            _o = (sb["ds"] + 0x14E37A) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123121  895518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 12
        elif bb == 12:
            # 0x123124  2bd8           sub
            _a = r[3]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123126  43             inc
            _old = r[3]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[3] = (_r) & 0xFFFFFFFF
            # 0x123127  895df0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            # 0x12312A  2bd1           sub
            _a = r[2]
            _b = r[1]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12312C  42             inc
            _old = r[2]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[2] = (_r) & 0xFFFFFFFF
            # 0x12312D  8955ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x123130  8b4520         mov
            _o = (sb["ss"] + r[5] + 0x20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123133  8b5d24         mov
            _o = (sb["ss"] + r[5] + 0x24) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123136  3b056ee31400   cmp
            _o = (sb["ds"] + 0x14E36E) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x12313C  7d08           jcc
            bb = 14 if cpu._cond(0xD) else 13
        elif bb == 13:
            # 0x12313E  a16ee31400     mov
            _o = (sb["ds"] + 0x14E36E) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123143  894520         mov
            _o = (sb["ss"] + r[5] + 0x20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 14
        elif bb == 14:
            # 0x123146  8b55f0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123149  03d0           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12314B  2b1576e31400   sub
            _o = (sb["ds"] + 0x14E376) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123151  7e1b           jcc
            bb = 17 if cpu._cond(0xE) else 15
        elif bb == 15:
            # 0x123153  8b0d76e31400   mov
            _o = (sb["ds"] + 0x14E376) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123159  2bc8           sub
            _a = r[1]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[1] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12315B  0f8c0f010000   jcc
            bb = 30 if cpu._cond(0xC) else 16
        elif bb == 16:
            # 0x123161  41             inc
            _old = r[1]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[1] = (_r) & 0xFFFFFFFF
            # 0x123162  8b55f0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123165  894df0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w32(_o, r[1])
            # 0x123168  295514         sub
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x12316B  014d14         add
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 17
        elif bb == 17:
            # 0x12316E  3b1d72e31400   cmp
            _o = (sb["ds"] + 0x14E372) & 0xFFFFFFFF
            _a = r[3]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x123174  7d09           jcc
            bb = 19 if cpu._cond(0xD) else 18
        elif bb == 18:
            # 0x123176  8b1d72e31400   mov
            _o = (sb["ds"] + 0x14E372) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12317C  895d24         mov
            _o = (sb["ss"] + r[5] + 0x24) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            bb = 19
        elif bb == 19:
            # 0x12317F  8b55ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123182  03d3           add
            _a = r[2]
            _b = r[3]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123184  2b157ae31400   sub
            _o = (sb["ds"] + 0x14E37A) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12318A  7e1b           jcc
            bb = 22 if cpu._cond(0xE) else 20
        elif bb == 20:
            # 0x12318C  8b0d7ae31400   mov
            _o = (sb["ds"] + 0x14E37A) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123192  2bcb           sub
            _a = r[1]
            _b = r[3]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[1] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123194  0f8cd6000000   jcc
            bb = 30 if cpu._cond(0xC) else 21
        elif bb == 21:
            # 0x12319A  41             inc
            _old = r[1]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[1] = (_r) & 0xFFFFFFFF
            # 0x12319B  8b55ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12319E  894dec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            mem.w32(_o, r[1])
            # 0x1231A1  295518         sub
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x1231A4  014d18         add
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 22
        elif bb == 22:
            # 0x1231A7  66833d24e3140000 grp1
            _o = (sb["ds"] + 0x14E324) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x1231AF  0f84c0000000   jcc
            bb = 31 if cpu._cond(0x4) else 23
        elif bb == 23:
            # 0x1231B5  803d85e314000f grp1
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xF
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x1231BC  7411           jcc
            bb = 25 if cpu._cond(0x4) else 24
        elif bb == 24:
            # 0x1231BE  c60585e314000f mov
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            mem.w8(_o, 0xF)
            # 0x1231C5  66b8020f       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0xF02) & 0xFFFF)
            # 0x1231C9  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x1231CD  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 25
        elif bb == 25:
            # 0x1231CF  66833d24e3140001 grp1
            _o = (sb["ds"] + 0x14E324) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x1231D7  751a           jcc
            bb = 28 if cpu._cond(0x5) else 26
        elif bb == 26:
            # 0x1231D9  803d84e3140041 grp1
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x41
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x1231E0  7411           jcc
            bb = 28 if cpu._cond(0x4) else 27
        elif bb == 27:
            # 0x1231E2  c60584e3140041 mov
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            mem.w8(_o, 0x41)
            # 0x1231E9  66b80541       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x4105) & 0xFFFF)
            # 0x1231ED  66bace03       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3CE) & 0xFFFF)
            # 0x1231F1  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 28
        elif bb == 28:
            # 0x1231F3  8b0d5ee31400   mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1231F9  8b4510         mov
            _o = (sb["ss"] + r[5] + 0x10) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1231FC  f7e1           grp3
            interp_one32(cpu, 0x1231FC)  # (interpreter fallback)
            # 0x1231FE  8bf0           mov
            r[6] = (r[0]) & 0xFFFFFFFF
            # 0x123200  8b5d08         mov
            _o = (sb["ss"] + r[5] + 0x8) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123203  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x123206  03b326e31400   add
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12320C  03b336e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123212  03b346e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123218  8b5d1c         mov
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12321B  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x12321E  8bbb26e31400   mov
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123224  03bb36e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12322A  03bb46e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123230  8b4524         mov
            _o = (sb["ss"] + r[5] + 0x24) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123233  f7e1           grp3
            interp_one32(cpu, 0x123233)  # (interpreter fallback)
            # 0x123235  034520         add
            _o = (sb["ss"] + r[5] + 0x20) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123238  03f8           add
            _a = r[7]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12323A  c1ef02         grp2
            cpu._shift(5, True, 7, 4, 0x02)
            # 0x12323D  8bd6           mov
            r[2] = (r[6]) & 0xFFFFFFFF
            # 0x12323F  83e203         grp1
            _a = r[2]
            _b = 0x3
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123242  03750c         add
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123245  c1ee02         grp2
            cpu._shift(5, True, 6, 4, 0x02)
            # 0x123248  8b450c         mov
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12324B  8b5d14         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12324E  03c2           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123250  03da           add
            _a = r[3]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123252  c1e802         grp2
            cpu._shift(5, True, 0, 4, 0x02)
            # 0x123255  c1eb02         grp2
            cpu._shift(5, True, 3, 4, 0x02)
            # 0x123258  2bd8           sub
            _a = r[3]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12325A  43             inc
            _old = r[3]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[3] = (_r) & 0xFFFFFFFF
            # 0x12325B  c1e902         grp2
            cpu._shift(5, True, 1, 4, 0x02)
            # 0x12325E  8bc1           mov
            r[0] = (r[1]) & 0xFFFFFFFF
            # 0x123260  2bc3           sub
            _a = r[0]
            _b = r[3]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123262  8b55ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            bb = 29
        elif bb == 29:
            # 0x123265  8bcb           mov
            r[1] = (r[3]) & 0xFFFFFFFF
            # 0x123267  f3a4           movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0xF3)
            # 0x123269  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12326B  03f8           add
            _a = r[7]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12326D  4a             dec
            _old = r[2]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[2] = (_r) & 0xFFFFFFFF
            # 0x12326E  75f5           jcc
            bb = 29 if cpu._cond(0x5) else 30
        elif bb == 30:
            # 0x123270  61             popad
            cpu._popa(4)
            # 0x123271  8be5           mov
            r[4] = (r[5]) & 0xFFFFFFFF
            # 0x123273  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x123274  c3             ret
            cpu.eip = cpu.pop(4)
            return
        elif bb == 31:
            # 0x123275  803d85e314000f grp1
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xF
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x12327C  7411           jcc
            bb = 33 if cpu._cond(0x4) else 32
        elif bb == 32:
            # 0x12327E  c60585e314000f mov
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            mem.w8(_o, 0xF)
            # 0x123285  66b8020f       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0xF02) & 0xFFFF)
            # 0x123289  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x12328D  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 33
        elif bb == 33:
            # 0x12328F  803d84e3140040 grp1
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x40
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x123296  7411           jcc
            bb = 35 if cpu._cond(0x4) else 34
        elif bb == 34:
            # 0x123298  c60584e3140040 mov
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            mem.w8(_o, 0x40)
            # 0x12329F  66b80540       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x4005) & 0xFFFF)
            # 0x1232A3  66bace03       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3CE) & 0xFFFF)
            # 0x1232A7  66ef           in/out
            cpu.port_writer(cpu, (r[2] & 0xFFFF), r[0] & 0xFFFF, 16) if cpu.port_writer else None
            bb = 35
        elif bb == 35:
            # 0x1232A9  8b0d5ee31400   mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232AF  8b4510         mov
            _o = (sb["ss"] + r[5] + 0x10) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232B2  f7e1           grp3
            interp_one32(cpu, 0x1232B2)  # (interpreter fallback)
            # 0x1232B4  8b750c         mov
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            r[6] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232B7  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232B9  8b5d08         mov
            _o = (sb["ss"] + r[5] + 0x8) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232BC  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x1232BF  03b326e31400   add
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232C5  03b336e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232CB  03b346e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232D1  8b5d1c         mov
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232D4  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x1232D7  8bbb26e31400   mov
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232DD  03bb36e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232E3  03bb46e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232E9  8b4524         mov
            _o = (sb["ss"] + r[5] + 0x24) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232EC  f7e1           grp3
            interp_one32(cpu, 0x1232EC)  # (interpreter fallback)
            # 0x1232EE  034520         add
            _o = (sb["ss"] + r[5] + 0x20) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232F1  03f8           add
            _a = r[7]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1232F3  8b55f0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1232F6  8bda           mov
            r[3] = (r[2]) & 0xFFFFFFFF
            # 0x1232F8  c1ea02         grp2
            cpu._shift(5, True, 2, 4, 0x02)
            # 0x1232FB  8955f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1232FE  83e303         grp1
            _a = r[3]
            _b = 0x3
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123301  895df4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            # 0x123304  2b4df0         sub
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = r[1]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[1] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123307  8bc1           mov
            r[0] = (r[1]) & 0xFFFFFFFF
            # 0x123309  8b5dec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            bb = 36
        elif bb == 36:
            # 0x12330C  8b4df8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12330F  f3a5           movsd
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA5, 0xF3)
            # 0x123311  8b4df4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x123314  f3a4           movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0xF3)
            # 0x123316  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x123318  03f8           add
            _a = r[7]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12331A  4b             dec
            _old = r[3]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[3] = (_r) & 0xFFFFFFFF
            # 0x12331B  75ef           jcc
            bb = 36 if cpu._cond(0x5) else 37
        elif bb == 37:
            # 0x12331D  61             popad
            cpu._popa(4)
            # 0x12331E  8be5           mov
            r[4] = (r[5]) & 0xFFFFFFFF
            # 0x123320  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x123321  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1230b7' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
