"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x117BF4  (136 instructions, 27 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, DF, IF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x117BF4
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 680000


def lift_117bf4(cpu):
    """Lifted replacement for flat 0x117BF4."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_117bf4')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x117BF4  53             push
            cpu.push(r[3], 4)
            # 0x117BF5  56             push
            cpu.push(r[6], 4)
            # 0x117BF6  57             push
            cpu.push(r[7], 4)
            # 0x117BF7  55             push
            cpu.push(r[5], 4)
            # 0x117BF8  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x117BFA  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x117C00  c7056cdd1400b8941400 mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            mem.w32(_o, 0x1494B8)
            # 0x117C0A  c70588dd140000000000 mov
            _o = (sb["ds"] + 0x14DD88) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 1
        elif bb == 1:
            # 0x117C14  a188dd1400     mov
            _o = (sb["ds"] + 0x14DD88) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C19  3b0584dd1400   cmp
            _o = (sb["ds"] + 0x14DD84) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117C1F  7c0d           jcc
            bb = 4 if cpu._cond(0xC) else 2
        elif bb == 2:
            # 0x117C21  e9e7010000     jmp
            bb = 26
        elif bb == 3:
            # 0x117C26  ff0588dd1400   inc
            _o = (sb["ds"] + 0x14DD88) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x117C2C  ebe6           jmp
            bb = 1
        elif bb == 4:
            # 0x117C2E  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C33  f6401c20       grp3
            interp_one32(cpu, 0x117C33)  # (interpreter fallback)
            # 0x117C37  7422           jcc
            bb = 6 if cpu._cond(0x4) else 5
        elif bb == 5:
            # 0x117C39  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C3F  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C44  8b12           mov
            _o = (sb["ds"] + r[2]) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C46  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x117C48  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C4D  8b156cdd1400   mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C53  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C56  894204         mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x117C59  eb49           jmp
            bb = 9
        elif bb == 6:
            # 0x117C5B  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C60  f6401c1e       grp3
            interp_one32(cpu, 0x117C60)  # (interpreter fallback)
            # 0x117C64  7523           jcc
            bb = 8 if cpu._cond(0x5) else 7
        elif bb == 7:
            # 0x117C66  8b156cdd1400   mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C6C  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C71  8b5208         mov
            _o = (sb["ds"] + r[2] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C74  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x117C76  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C7B  8b156cdd1400   mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C81  8b520c         mov
            _o = (sb["ds"] + r[2] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C84  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x117C87  eb1b           jmp
            bb = 9
        elif bb == 8:
            # 0x117C89  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C8E  8b501c         mov
            _o = (sb["ds"] + r[0] + 0x1C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117C91  c1e21b         grp2
            cpu._shift(4, True, 2, 4, 0x1B)
            # 0x117C94  c1ea1c         grp2
            cpu._shift(5, True, 2, 4, 0x1C)
            # 0x117C97  4a             dec
            _old = r[2]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[2] = (_r) & 0xFFFFFFFF
            # 0x117C98  83e20f         grp1
            _a = r[2]
            _b = 0xF
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x117C9B  80601ce1       grp1
            _o = (sb["ds"] + r[0] + 0x1C) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xE1
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x117C9F  01d2           add
            _a = r[2]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x117CA1  09501c         or
            _o = (sb["ds"] + r[0] + 0x1C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a | _b
            cpu._flags_logic(_r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 9
        elif bb == 9:
            # 0x117CA4  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CA9  ff4814         dec
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x117CAC  83781400       grp1
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117CB0  0f8f74000000   jcc
            bb = 17 if cpu._cond(0xF) else 10
        elif bb == 10:
            # 0x117CB6  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CBB  83401808       grp1
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x117CBF  8b4018         mov
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CC2  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CC5  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x117CCA  833d208e140000 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117CD1  7d49           jcc
            bb = 16 if cpu._cond(0xD) else 11
        elif bb == 11:
            # 0x117CD3  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CD8  f6401c40       grp3
            interp_one32(cpu, 0x117CD8)  # (interpreter fallback)
            # 0x117CDC  7408           jcc
            bb = 13 if cpu._cond(0x4) else 12
        elif bb == 12:
            # 0x117CDE  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CE3  800840         grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x40
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 13
        elif bb == 13:
            # 0x117CE6  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117CEB  f6401d01       grp3
            interp_one32(cpu, 0x117CEB)  # (interpreter fallback)
            # 0x117CEF  740a           jcc
            bb = 15 if cpu._cond(0x4) else 14
        elif bb == 14:
            # 0x117CF1  e81c010000     call
            emulate_call32(cpu, 0x117E12, 0x117CF6)
            # 0x117CF6  e92bffffff     jmp
            bb = 3
        elif bb == 15:
            # 0x117CFB  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D00  8b15208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D06  c1e203         grp2
            cpu._shift(4, True, 2, 4, 0x03)
            # 0x117D09  015018         add
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x117D0C  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D11  8b4018         mov
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D14  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D17  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 16
        elif bb == 16:
            # 0x117D1C  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D21  8b15208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D27  895014         mov
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 17
        elif bb == 17:
            # 0x117D2A  8b156cdd1400   mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D30  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D35  8b4018         mov
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D38  8b5210         mov
            _o = (sb["ds"] + r[2] + 0x10) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D3B  0310           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x117D3D  8915b48d1400   mov
            _o = (sb["ds"] + 0x148DB4) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x117D43  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D48  f6401c80       grp3
            interp_one32(cpu, 0x117D48)  # (interpreter fallback)
            # 0x117D4C  0f846b000000   jcc
            bb = 25 if cpu._cond(0x4) else 18
        elif bb == 18:
            # 0x117D52  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D57  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D59  a34ce21400     mov
            _o = (sb["ds"] + 0x14E24C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x117D5E  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D63  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D66  a350e21400     mov
            _o = (sb["ds"] + 0x14E250) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x117D6B  ff35b48d1400   push
            _o = (sb["ds"] + 0x148DB4) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x117D71  b84ce21400     mov
            r[0] = (0x14E24C) & 0xFFFFFFFF
            # 0x117D76  50             push
            cpu.push(r[0], 4)
            # 0x117D77  e888020000     call
            emulate_call32(cpu, 0x118004, 0x117D7C)
            # 0x117D7C  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x117D7F  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D84  813850010000   grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x150
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117D8A  7f0a           jcc
            bb = 20 if cpu._cond(0xF) else 19
        elif bb == 19:
            # 0x117D8C  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D91  8338f0         grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xFFFFFFF0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117D94  7d02           jcc
            bb = 21 if cpu._cond(0xD) else 20
        elif bb == 20:
            # 0x117D96  eb0e           jmp
            bb = 22
        elif bb == 21:
            # 0x117D98  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117D9D  817804d8000000 grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xD8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117DA4  7e02           jcc
            bb = 23 if cpu._cond(0xE) else 22
        elif bb == 22:
            # 0x117DA6  eb0b           jmp
            bb = 24
        elif bb == 23:
            # 0x117DA8  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DAD  837804f0       grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xFFFFFFF0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x117DB1  7d0a           jcc
            bb = 25 if cpu._cond(0xD) else 24
        elif bb == 24:
            # 0x117DB3  e85a000000     call
            emulate_call32(cpu, 0x117E12, 0x117DB8)
            # 0x117DB8  e969feffff     jmp
            bb = 3
        elif bb == 25:
            # 0x117DBD  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DC2  8b15b48d1400   mov
            _o = (sb["ds"] + 0x148DB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DC8  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x117DCA  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DCF  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DD5  668b00         mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x117DD8  66894204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x117DDC  a16cdd1400     mov
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DE1  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DE7  668b4004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x117DEB  66894206       mov
            _o = (sb["ds"] + r[2] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x117DEF  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x117DF4  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x117DFA  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x117E01  83056cdd140020 grp1
            _o = (sb["ds"] + 0x14DD6C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x20
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x117E08  e919feffff     jmp
            bb = 3
        elif bb == 26:
            # 0x117E0D  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x117E0E  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x117E0F  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x117E10  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x117E11  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_117bf4' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
