"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1191A3  (289 instructions, 64 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, DF, IF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x1191A3
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 1445000


def lift_1191a3(cpu):
    """Lifted replacement for flat 0x1191A3."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1191a3')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1191A3  53             push
            cpu.push(r[3], 4)
            # 0x1191A4  56             push
            cpu.push(r[6], 4)
            # 0x1191A5  57             push
            cpu.push(r[7], 4)
            # 0x1191A6  55             push
            cpu.push(r[5], 4)
            # 0x1191A7  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x1191A9  81ec0c000000   grp1
            _a = r[4]
            _b = 0xC
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1191AF  837d1818       grp1
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x18
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1191B3  7c09           jcc
            bb = 2 if cpu._cond(0xC) else 1
        elif bb == 1:
            # 0x1191B5  817d1898000000 grp1
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x98
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1191BC  7c05           jcc
            bb = 3 if cpu._cond(0xC) else 2
        elif bb == 2:
            # 0x1191BE  e950030000     jmp
            bb = 47
        elif bb == 3:
            # 0x1191C3  837d1410       grp1
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x10
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1191C7  7c09           jcc
            bb = 5 if cpu._cond(0xC) else 4
        elif bb == 4:
            # 0x1191C9  817d1430010000 grp1
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x130
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1191D0  7c05           jcc
            bb = 6 if cpu._cond(0xC) else 5
        elif bb == 5:
            # 0x1191D2  e93c030000     jmp
            bb = 47
        elif bb == 6:
            # 0x1191D7  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1191DA  83e810         grp1
            _a = r[0]
            _b = 0x10
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1191DD  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x1191E0  8945fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1191E3  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1191E6  83e818         grp1
            _a = r[0]
            _b = 0x18
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1191E9  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x1191EC  6bc012         imul
            _a = ((r[0]) - 0x100000000 if (r[0]) & 0x80000000 else (r[0]))
            cpu._imul_store(0, 4, _a, 18)
            # 0x1191EF  8945f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1191F2  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1191F5  3b0558dd1400   cmp
            _o = (sb["ds"] + 0x14DD58) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1191FB  750b           jcc
            bb = 8 if cpu._cond(0x5) else 7
        elif bb == 7:
            # 0x1191FD  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119200  3b055cdd1400   cmp
            _o = (sb["ds"] + 0x14DD5C) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119206  7402           jcc
            bb = 9 if cpu._cond(0x4) else 8
        elif bb == 8:
            # 0x119208  eb05           jmp
            bb = 10
        elif bb == 9:
            # 0x11920A  e972030000     jmp
            bb = 56
        elif bb == 10:
            # 0x11920F  c70580dd140008a61400 mov
            _o = (sb["ds"] + 0x14DD80) & 0xFFFFFFFF
            mem.w32(_o, 0x14A608)
            # 0x119219  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11921C  01c0           add
            _a = r[0]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11921E  010580dd1400   add
            _o = (sb["ds"] + 0x14DD80) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x119224  8b55fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119227  01d2           add
            _a = r[2]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119229  a180dd1400     mov
            _o = (sb["ds"] + 0x14DD80) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11922E  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119230  0fb64001       movzx/sx
            _o = (sb["ds"] + r[0] + 0x1) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x119234  a350dd1400     mov
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x119239  833d50dd140000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119240  0f84cd020000   jcc
            bb = 47 if cpu._cond(0x4) else 11
        elif bb == 11:
            # 0x119246  813d50dd1400f8000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xF8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119250  7533           jcc
            bb = 13 if cpu._cond(0x5) else 12
        elif bb == 12:
            # 0x119252  a168dd1400     mov
            _o = (sb["ds"] + 0x14DD68) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119257  2b0560dd1400   sub
            _o = (sb["ds"] + 0x14DD60) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11925D  c1e004         grp2
            cpu._shift(4, True, 0, 4, 0x04)
            # 0x119260  89c2           mov
            r[2] = (r[0]) & 0xFFFFFFFF
            # 0x119262  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119267  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x119269  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11926E  8b1570dd1400   mov
            _o = (sb["ds"] + 0x14DD70) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119274  2b1564dd1400   sub
            _o = (sb["ds"] + 0x14DD64) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11927A  c1e204         grp2
            cpu._shift(4, True, 2, 4, 0x04)
            # 0x11927D  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x119280  e99d020000     jmp
            bb = 48
        elif bb == 13:
            # 0x119285  813d50dd1400f9000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xF9
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11928F  7533           jcc
            bb = 15 if cpu._cond(0x5) else 14
        elif bb == 14:
            # 0x119291  a160dd1400     mov
            _o = (sb["ds"] + 0x14DD60) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119296  2b0568dd1400   sub
            _o = (sb["ds"] + 0x14DD68) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11929C  c1e004         grp2
            cpu._shift(4, True, 0, 4, 0x04)
            # 0x11929F  89c2           mov
            r[2] = (r[0]) & 0xFFFFFFFF
            # 0x1192A1  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1192A6  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x1192A8  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1192AD  8b1564dd1400   mov
            _o = (sb["ds"] + 0x14DD64) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1192B3  2b1570dd1400   sub
            _o = (sb["ds"] + 0x14DD70) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1192B9  c1e204         grp2
            cpu._shift(4, True, 2, 4, 0x04)
            # 0x1192BC  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x1192BF  e95e020000     jmp
            bb = 48
        elif bb == 15:
            # 0x1192C4  833d50dd140001 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1192CB  720c           jcc
            bb = 17 if cpu._cond(0x2) else 16
        elif bb == 16:
            # 0x1192CD  813d50dd140090000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x90
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1192D7  7605           jcc
            bb = 18 if cpu._cond(0x6) else 17
        elif bb == 17:
            # 0x1192D9  e9b4000000     jmp
            bb = 30
        elif bb == 18:
            # 0x1192DE  833d50dd140001 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1192E5  7209           jcc
            bb = 20 if cpu._cond(0x2) else 19
        elif bb == 19:
            # 0x1192E7  833d50dd140010 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x10
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1192EE  7614           jcc
            bb = 23 if cpu._cond(0x6) else 20
        elif bb == 20:
            # 0x1192F0  833d50dd140031 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x31
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1192F7  7209           jcc
            bb = 22 if cpu._cond(0x2) else 21
        elif bb == 21:
            # 0x1192F9  833d50dd140040 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x40
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119300  7602           jcc
            bb = 23 if cpu._cond(0x6) else 22
        elif bb == 22:
            # 0x119302  eb02           jmp
            bb = 24
        elif bb == 23:
            # 0x119304  eb14           jmp
            bb = 27
        elif bb == 24:
            # 0x119306  833d50dd140061 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x61
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11930D  7209           jcc
            bb = 26 if cpu._cond(0x2) else 25
        elif bb == 25:
            # 0x11930F  833d50dd140070 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x70
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119316  7602           jcc
            bb = 27 if cpu._cond(0x6) else 26
        elif bb == 26:
            # 0x119318  eb2a           jmp
            bb = 28
        elif bb == 27:
            # 0x11931A  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11931F  8b400c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119322  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x119325  50             push
            cpu.push(r[0], 4)
            # 0x119326  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11932B  8b4008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11932E  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x119331  50             push
            cpu.push(r[0], 4)
            # 0x119332  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119335  50             push
            cpu.push(r[0], 4)
            # 0x119336  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119339  50             push
            cpu.push(r[0], 4)
            # 0x11933A  e8d9a5ffff     call
            emulate_call32(cpu, 0x113918, 0x11933F)
            # 0x11933F  83c410         grp1
            _a = r[4]
            _b = 0x10
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119342  eb33           jmp
            bb = 29
        elif bb == 28:
            # 0x119344  832d50dd140010 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x10
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11934B  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11934E  01c0           add
            _a = r[0]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119350  8b1580dd1400   mov
            _o = (sb["ds"] + 0x14DD80) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119356  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119358  8a1550dd1400   mov
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x11935E  885001         mov
            _o = (sb["ds"] + r[0] + 0x1) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(2, 1))
            # 0x119361  ff3550dd1400   push
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x119367  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11936A  50             push
            cpu.push(r[0], 4)
            # 0x11936B  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11936E  50             push
            cpu.push(r[0], 4)
            # 0x11936F  e84ca7ffff     call
            emulate_call32(cpu, 0x113AC0, 0x119374)
            # 0x119374  83c40c         grp1
            _a = r[4]
            _b = 0xC
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 29
        elif bb == 29:
            # 0x119377  6a19           push
            cpu.push(0x19, 4)
            # 0x119379  6a0c           push
            cpu.push(0xC, 4)
            # 0x11937B  e8ea2e0000     call
            emulate_call32(cpu, 0x11C26A, 0x119380)
            # 0x119380  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119383  c705108e1400685e1400 mov
            _o = (sb["ds"] + 0x148E10) & 0xFFFFFFFF
            mem.w32(_o, 0x145E68)
            # 0x11938D  e95a010000     jmp
            bb = 46
        elif bb == 30:
            # 0x119392  813d50dd140091000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x91
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11939C  720c           jcc
            bb = 32 if cpu._cond(0x2) else 31
        elif bb == 31:
            # 0x11939E  813d50dd140000010000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x100
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1193A8  7605           jcc
            bb = 33 if cpu._cond(0x6) else 32
        elif bb == 32:
            # 0x1193AA  e964010000     jmp
            bb = 47
        elif bb == 33:
            # 0x1193AF  c705108e140098601400 mov
            _o = (sb["ds"] + 0x148E10) & 0xFFFFFFFF
            mem.w32(_o, 0x146098)
            # 0x1193B9  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193BE  f6400110       grp3
            _o = (sb["ds"] + r[0] + 0x1) & 0xFFFFFFFF
            cpu._grp3_op(0, False, _o, 1, 0x10)
            # 0x1193C2  742d           jcc
            bb = 35 if cpu._cond(0x4) else 34
        elif bb == 34:
            # 0x1193C4  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193C9  8b400c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193CC  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x1193CF  50             push
            cpu.push(r[0], 4)
            # 0x1193D0  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193D5  8b4008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193D8  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x1193DB  50             push
            cpu.push(r[0], 4)
            # 0x1193DC  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193DF  50             push
            cpu.push(r[0], 4)
            # 0x1193E0  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1193E3  50             push
            cpu.push(r[0], 4)
            # 0x1193E4  e82fa5ffff     call
            emulate_call32(cpu, 0x113918, 0x1193E9)
            # 0x1193E9  83c410         grp1
            _a = r[4]
            _b = 0x10
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1193EC  e9fb000000     jmp
            bb = 46
        elif bb == 35:
            # 0x1193F1  813d50dd1400f5000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xF5
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1193FB  720c           jcc
            bb = 37 if cpu._cond(0x2) else 36
        elif bb == 36:
            # 0x1193FD  813d50dd1400f7000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xF7
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119407  7602           jcc
            bb = 38 if cpu._cond(0x6) else 37
        elif bb == 37:
            # 0x119409  eb20           jmp
            bb = 39
        elif bb == 38:
            # 0x11940B  6a32           push
            cpu.push(0x32, 4)
            # 0x11940D  6a2e           push
            cpu.push(0x2E, 4)
            # 0x11940F  e8562e0000     call
            emulate_call32(cpu, 0x11C26A, 0x119414)
            # 0x119414  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119417  c705b8dd1400ffffffff mov
            _o = (sb["ds"] + 0x14DDB8) & 0xFFFFFFFF
            mem.w32(_o, 0xFFFFFFFF)
            # 0x119421  e86eafffff     call
            emulate_call32(cpu, 0x114394, 0x119426)
            # 0x119426  e9c1000000     jmp
            bb = 46
        elif bb == 39:
            # 0x11942B  813d50dd1400fa000000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xFA
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119435  720c           jcc
            bb = 41 if cpu._cond(0x2) else 40
        elif bb == 40:
            # 0x119437  813d50dd140000010000 grp1
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x100
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119441  7605           jcc
            bb = 42 if cpu._cond(0x6) else 41
        elif bb == 41:
            # 0x119443  e998000000     jmp
            bb = 45
        elif bb == 42:
            # 0x119448  6a09           push
            cpu.push(0x9, 4)
            # 0x11944A  6a01           push
            cpu.push(0x1, 4)
            # 0x11944C  e8192e0000     call
            emulate_call32(cpu, 0x11C26A, 0x119451)
            # 0x119451  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119454  8b55fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119457  01d2           add
            _a = r[2]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119459  a180dd1400     mov
            _o = (sb["ds"] + 0x14DD80) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11945E  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x119460  8a10           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x119462  c0ea02         grp2
            cpu._shift(5, True, 2, 1, 0x02)
            # 0x119465  feca           grp4
            _old = cpu.reg(2, 1)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(2, 1, _r)
            # 0x119467  88d6           mov
            cpu.set_reg(6, 1, cpu.reg(2, 1))
            # 0x119469  80e63f         grp1
            _a = cpu.reg(6, 1)
            _b = 0x3F
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(6, 1, _r & 0xFF)
            # 0x11946C  802003         grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x3
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x11946F  c0e602         grp2
            cpu._shift(4, True, 6, 1, 0x02)
            # 0x119472  0830           or
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = cpu.reg(6, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x119474  80e23f         grp1
            _a = cpu.reg(2, 1)
            _b = 0x3F
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(2, 1, _r & 0xFF)
            # 0x119477  88d0           mov
            cpu.set_reg(0, 1, cpu.reg(2, 1))
            # 0x119479  84c0           test
            cpu._flags_logic(cpu.reg(0, 1) & (cpu.reg(0, 1)), 8)
            # 0x11947B  7557           jcc
            bb = 44 if cpu._cond(0x5) else 43
        elif bb == 43:
            # 0x11947D  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119482  8b0de4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119488  8a4924         mov
            _o = (sb["ds"] + r[1] + 0x24) & 0xFFFFFFFF
            cpu.set_reg(1, 1, mem.r8(_o))
            # 0x11948B  ba02000000     mov
            r[2] = (0x2) & 0xFFFFFFFF
            # 0x119490  d3e2           grp2
            cpu._shift(4, True, 2, 4, r[1] & 0xFF)
            # 0x119492  89d1           mov
            r[1] = (r[2]) & 0xFFFFFFFF
            # 0x119494  014814         add
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x119497  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11949A  0345f8         add
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11949D  50             push
            cpu.push(r[0], 4)
            # 0x11949E  ff3550dd1400   push
            _o = (sb["ds"] + 0x14DD50) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1194A4  e866a9ffff     call
            emulate_call32(cpu, 0x113E0F, 0x1194A9)
            # 0x1194A9  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1194AC  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1194B1  8b400c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1194B4  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x1194B7  50             push
            cpu.push(r[0], 4)
            # 0x1194B8  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1194BD  8b4008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1194C0  c1f803         grp2
            cpu._shift(7, True, 0, 4, 0x03)
            # 0x1194C3  50             push
            cpu.push(r[0], 4)
            # 0x1194C4  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1194C7  50             push
            cpu.push(r[0], 4)
            # 0x1194C8  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1194CB  50             push
            cpu.push(r[0], 4)
            # 0x1194CC  e847a4ffff     call
            emulate_call32(cpu, 0x113918, 0x1194D1)
            # 0x1194D1  83c410         grp1
            _a = r[4]
            _b = 0x10
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 44
        elif bb == 44:
            # 0x1194D4  c705108e1400685e1400 mov
            _o = (sb["ds"] + 0x148E10) & 0xFFFFFFFF
            mem.w32(_o, 0x145E68)
            # 0x1194DE  eb0c           jmp
            bb = 46
        elif bb == 45:
            # 0x1194E0  6a2d           push
            cpu.push(0x2D, 4)
            # 0x1194E2  6a2a           push
            cpu.push(0x2A, 4)
            # 0x1194E4  e8812d0000     call
            emulate_call32(cpu, 0x11C26A, 0x1194E9)
            # 0x1194E9  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 46
        elif bb == 46:
            # 0x1194EC  6a01           push
            cpu.push(0x1, 4)
            # 0x1194EE  ff35108e1400   push
            _o = (sb["ds"] + 0x148E10) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1194F4  ff3534df1400   push
            _o = (sb["ds"] + 0x14DF34) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1194FA  6a00           push
            cpu.push(0x0, 4)
            # 0x1194FC  6a00           push
            cpu.push(0x0, 4)
            # 0x1194FE  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119501  50             push
            cpu.push(r[0], 4)
            # 0x119502  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119505  50             push
            cpu.push(r[0], 4)
            # 0x119506  e857e9ffff     call
            emulate_call32(cpu, 0x117E62, 0x11950B)
            # 0x11950B  83c41c         grp1
            _a = r[4]
            _b = 0x1C
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11950E  e96e000000     jmp
            bb = 56
        elif bb == 47:
            # 0x119513  c705208e140000000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            # 0x11951D  e9bc000000     jmp
            bb = 63
        elif bb == 48:
            # 0x119522  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119527  83780c00       grp1
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11952B  7e0e           jcc
            bb = 50 if cpu._cond(0xE) else 49
        elif bb == 49:
            # 0x11952D  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119532  81400480000000 grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x80
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x119539  eb0c           jmp
            bb = 51
        elif bb == 50:
            # 0x11953B  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119540  81680480000000 grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x80
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 51
        elif bb == 51:
            # 0x119547  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11954C  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119550  7e0d           jcc
            bb = 53 if cpu._cond(0xE) else 52
        elif bb == 52:
            # 0x119552  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119557  810000010000   grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x100
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11955D  eb16           jmp
            bb = 55
        elif bb == 53:
            # 0x11955F  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x119564  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119568  7d0b           jcc
            bb = 55 if cpu._cond(0xD) else 54
        elif bb == 54:
            # 0x11956A  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11956F  812800010000   grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x100
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 55
        elif bb == 55:
            # 0x119575  c705208e140003000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x3)
            # 0x11957F  eb5d           jmp
            bb = 63
        elif bb == 56:
            # 0x119581  c705208e140001000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x1)
            # 0x11958B  8365140f       grp1
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xF
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11958F  837d1407       grp1
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x7
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x119593  7e0b           jcc
            bb = 58 if cpu._cond(0xE) else 57
        elif bb == 57:
            # 0x119595  b80f000000     mov
            r[0] = (0xF) & 0xFFFFFFFF
            # 0x11959A  2b4514         sub
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11959D  894514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 58
        elif bb == 58:
            # 0x1195A0  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195A3  01c0           add
            _a = r[0]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1195A5  83e00f         grp1
            _a = r[0]
            _b = 0xF
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1195A8  894518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1195AB  837d1807       grp1
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x7
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1195AF  7e0b           jcc
            bb = 60 if cpu._cond(0xE) else 59
        elif bb == 59:
            # 0x1195B1  b80f000000     mov
            r[0] = (0xF) & 0xFFFFFFFF
            # 0x1195B6  2b4518         sub
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1195B9  894518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 60
        elif bb == 60:
            # 0x1195BC  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195BF  3b4514         cmp
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1195C2  7e0a           jcc
            bb = 62 if cpu._cond(0xE) else 61
        elif bb == 61:
            # 0x1195C4  c705208e140002000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x2)
            bb = 62
        elif bb == 62:
            # 0x1195CE  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195D1  a358dd1400     mov
            _o = (sb["ds"] + 0x14DD58) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1195D6  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195D9  a35cdd1400     mov
            _o = (sb["ds"] + 0x14DD5C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 63
        elif bb == 63:
            # 0x1195DE  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195E3  8945f4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1195E6  8b45f4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195E9  c9             leave
            r[4] = r[5]
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1195EA  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1195EB  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1195EC  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1195ED  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1191a3' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
