"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x11B1DF  (192 instructions, 56 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x11B1DF
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 960000


def lift_11b1df(cpu):
    """Lifted replacement for flat 0x11B1DF."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_11b1df')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x11B1DF  53             push
            cpu.push(r[3], 4)
            # 0x11B1E0  56             push
            cpu.push(r[6], 4)
            # 0x11B1E1  57             push
            cpu.push(r[7], 4)
            # 0x11B1E2  55             push
            cpu.push(r[5], 4)
            # 0x11B1E3  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11B1E5  81ec20000000   grp1
            _a = r[4]
            _b = 0x20
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B1EB  a100e21400     mov
            _o = (sb["ds"] + 0x14E200) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B1F0  8b1504e21400   mov
            _o = (sb["ds"] + 0x14E204) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B1F6  8b8008020000   mov
            _o = (sb["ds"] + r[0] + 0x208) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B1FC  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B1FE  8945e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B201  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B204  a311e21400     mov
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B209  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B20C  a315e21400     mov
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B211  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B214  6683780a00     grp1
            _o = (sb["ds"] + r[0] + 0xA) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x11B219  7d0d           jcc
            bb = 2 if cpu._cond(0xD) else 1
        elif bb == 1:
            # 0x11B21B  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B21E  0fbf400a       movzx/sx
            _o = (sb["ds"] + r[0] + 0xA) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B222  290511e21400   sub
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 2
        elif bb == 2:
            # 0x11B228  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B22B  6683780c00     grp1
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x11B230  7d0d           jcc
            bb = 4 if cpu._cond(0xD) else 3
        elif bb == 3:
            # 0x11B232  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B235  0fbf400c       movzx/sx
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B239  290515e21400   sub
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 4
        elif bb == 4:
            # 0x11B23F  8b451c         mov
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B242  ff451c         inc
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x11B245  8a00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x11B247  8845fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(0, 1))
            # 0x11B24A  8a45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x11B24D  8845e0         mov
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(0, 1))
            # 0x11B250  807de00a       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xA
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B254  722a           jcc
            bb = 11 if cpu._cond(0x2) else 5
        elif bb == 5:
            # 0x11B256  807de00a       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xA
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B25A  0f8694000000   jcc
            bb = 21 if cpu._cond(0x6) else 6
        elif bb == 6:
            # 0x11B260  807de012       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x12
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B264  7215           jcc
            bb = 10 if cpu._cond(0x2) else 7
        elif bb == 7:
            # 0x11B266  807de012       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x12
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B26A  0f86b4000000   jcc
            bb = 24 if cpu._cond(0x6) else 8
        elif bb == 8:
            # 0x11B270  807de020       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x20
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B274  7458           jcc
            bb = 18 if cpu._cond(0x4) else 9
        elif bb == 9:
            # 0x11B276  e9b3000000     jmp
            bb = 26
        elif bb == 10:
            # 0x11B27B  e9ae000000     jmp
            bb = 26
        elif bb == 11:
            # 0x11B280  807de000       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B284  0f869f000000   jcc
            bb = 25 if cpu._cond(0x6) else 12
        elif bb == 12:
            # 0x11B28A  807de009       grp1
            _o = (sb["ss"] + r[5] + -0x20) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x9
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B28E  740a           jcc
            bb = 14 if cpu._cond(0x4) else 13
        elif bb == 13:
            # 0x11B290  e999000000     jmp
            bb = 26
        elif bb == 14:
            # 0x11B29A  803d08e2140001 grp1
            _o = (sb["ds"] + 0x14E208) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B2A1  7518           jcc
            bb = 16 if cpu._cond(0x5) else 15
        elif bb == 15:
            # 0x11B2A3  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B2A6  0fbf4002       movzx/sx
            _o = (sb["ds"] + r[0] + 0x2) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B2AA  030509e21400   add
            _o = (sb["ds"] + 0x14E209) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B2B0  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11B2B3  010511e21400   add
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B2B9  eb0e           jmp
            bb = 17
        elif bb == 16:
            # 0x11B2BB  a109e21400     mov
            _o = (sb["ds"] + 0x14E209) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B2C0  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11B2C3  010511e21400   add
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 17
        elif bb == 17:
            # 0x11B2C9  e99d010000     jmp
            bb = 48
        elif bb == 18:
            # 0x11B2CE  a109e21400     mov
            _o = (sb["ds"] + 0x14E209) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B2D3  010511e21400   add
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B2D9  803d08e2140001 grp1
            _o = (sb["ds"] + 0x14E208) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B2E0  750d           jcc
            bb = 20 if cpu._cond(0x5) else 19
        elif bb == 19:
            # 0x11B2E2  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B2E5  0fbf4002       movzx/sx
            _o = (sb["ds"] + r[0] + 0x2) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B2E9  010511e21400   add
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 20
        elif bb == 20:
            # 0x11B2EF  e977010000     jmp
            bb = 48
        elif bb == 21:
            # 0x11B2F4  a119e21400     mov
            _o = (sb["ds"] + 0x14E219) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B2F9  a311e21400     mov
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B2FE  a10de21400     mov
            _o = (sb["ds"] + 0x14E20D) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B303  010515e21400   add
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B309  803d08e2140001 grp1
            _o = (sb["ds"] + 0x14E208) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B310  750d           jcc
            bb = 23 if cpu._cond(0x5) else 22
        elif bb == 22:
            # 0x11B312  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B315  0fbf4004       movzx/sx
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B319  010515e21400   add
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 23
        elif bb == 23:
            # 0x11B31F  e947010000     jmp
            bb = 48
        elif bb == 24:
            # 0x11B324  e942010000     jmp
            bb = 48
        elif bb == 25:
            # 0x11B329  e93d010000     jmp
            bb = 48
        elif bb == 26:
            # 0x11B32E  8b451c         mov
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B331  8945f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B334  0fb645fc       movzx/sx
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B338  8945f0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B33B  a111e21400     mov
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B340  8945f4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 27
        elif bb == 27:
            # 0x11B343  837df020       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x20
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B347  7406           jcc
            bb = 29 if cpu._cond(0x4) else 28
        elif bb == 28:
            # 0x11B349  837df009       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x9
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B34D  7502           jcc
            bb = 30 if cpu._cond(0x5) else 29
        elif bb == 29:
            # 0x11B34F  eb06           jmp
            bb = 31
        elif bb == 30:
            # 0x11B351  837df00a       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B355  7502           jcc
            bb = 32 if cpu._cond(0x5) else 31
        elif bb == 31:
            # 0x11B357  eb06           jmp
            bb = 33
        elif bb == 32:
            # 0x11B359  837df012       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x12
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B35D  7502           jcc
            bb = 34 if cpu._cond(0x5) else 33
        elif bb == 33:
            # 0x11B35F  eb06           jmp
            bb = 35
        elif bb == 34:
            # 0x11B361  837df000       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B365  7502           jcc
            bb = 36 if cpu._cond(0x5) else 35
        elif bb == 35:
            # 0x11B367  eb58           jmp
            bb = 41
        elif bb == 36:
            # 0x11B369  a109e21400     mov
            _o = (sb["ds"] + 0x14E209) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B36E  0145f4         add
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B371  803d08e2140001 grp1
            _o = (sb["ds"] + 0x14E208) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B378  7524           jcc
            bb = 38 if cpu._cond(0x5) else 37
        elif bb == 37:
            # 0x11B37A  8b55f0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B37D  c1e203         grp2
            cpu._shift(4, True, 2, 4, 0x03)
            # 0x11B380  a100e21400     mov
            _o = (sb["ds"] + 0x14E200) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B385  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B387  8b1504e21400   mov
            _o = (sb["ds"] + 0x14E204) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B38D  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B38F  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B391  8945ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B394  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B397  0fbf4002       movzx/sx
            _o = (sb["ds"] + r[0] + 0x2) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B39B  0145f4         add
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 38
        elif bb == 38:
            # 0x11B39E  8b45f4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3A1  48             dec
            _old = r[0]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[0] = (_r) & 0xFFFFFFFF
            # 0x11B3A2  3b051de21400   cmp
            _o = (sb["ds"] + 0x14E21D) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B3A8  7e09           jcc
            bb = 40 if cpu._cond(0xE) else 39
        elif bb == 39:
            # 0x11B3AA  83451cff       grp1
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xFFFFFFFF
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B3AE  e941ffffff     jmp
            bb = 21
        elif bb == 40:
            # 0x11B3B3  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3B6  ff45f8         inc
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x11B3B9  0fb600         movzx/sx
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B3BC  8945f0         mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B3BF  eb82           jmp
            bb = 27
        elif bb == 41:
            # 0x11B3C1  0fb645fc       movzx/sx
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B3C5  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11B3C8  89c2           mov
            r[2] = (r[0]) & 0xFFFFFFFF
            # 0x11B3CA  a100e21400     mov
            _o = (sb["ds"] + 0x14E200) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3CF  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B3D1  8b1504e21400   mov
            _o = (sb["ds"] + 0x14E204) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3D7  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3D9  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B3DB  8945ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B3DE  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3E1  0fbf4002       movzx/sx
            _o = (sb["ds"] + r[0] + 0x2) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B3E5  8b1511e21400   mov
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3EB  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B3ED  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B3F0  0fbf400a       movzx/sx
            _o = (sb["ds"] + r[0] + 0xA) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B3F4  01d0           add
            _a = r[0]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B3F6  48             dec
            _old = r[0]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[0] = (_r) & 0xFFFFFFFF
            # 0x11B3F7  3b051de21400   cmp
            _o = (sb["ds"] + 0x14E21D) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B3FD  7f3b           jcc
            bb = 45 if cpu._cond(0xF) else 42
        elif bb == 42:
            # 0x11B3FF  ff3515e21400   push
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x11B405  ff3511e21400   push
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x11B40B  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B40E  50             push
            cpu.push(r[0], 4)
            # 0x11B40F  e8a9780000     call
            emulate_call32(cpu, 0x122CBD, 0x11B414)
            # 0x11B414  83c40c         grp1
            _a = r[4]
            _b = 0xC
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11B417  a109e21400     mov
            _o = (sb["ds"] + 0x14E209) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B41C  010511e21400   add
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B422  803d08e2140001 grp1
            _o = (sb["ds"] + 0x14E208) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B429  750d           jcc
            bb = 44 if cpu._cond(0x5) else 43
        elif bb == 43:
            # 0x11B42B  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B42E  0fbf4002       movzx/sx
            _o = (sb["ds"] + r[0] + 0x2) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B432  010511e21400   add
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 44
        elif bb == 44:
            # 0x11B438  eb31           jmp
            bb = 48
        elif bb == 45:
            # 0x11B43A  a119e21400     mov
            _o = (sb["ds"] + 0x14E219) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B43F  a311e21400     mov
            _o = (sb["ds"] + 0x14E211) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11B444  a10de21400     mov
            _o = (sb["ds"] + 0x14E20D) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B449  010515e21400   add
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11B44F  803d08e2140001 grp1
            _o = (sb["ds"] + 0x14E208) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B456  750d           jcc
            bb = 47 if cpu._cond(0x5) else 46
        elif bb == 46:
            # 0x11B458  8b45e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B45B  0fbf4004       movzx/sx
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11B45F  010515e21400   add
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 47
        elif bb == 47:
            # 0x11B465  8b451c         mov
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B468  ff4d1c         dec
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            bb = 48
        elif bb == 48:
            # 0x11B46B  a115e21400     mov
            _o = (sb["ds"] + 0x14E215) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B470  3b0525e21400   cmp
            _o = (sb["ds"] + 0x14E225) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11B476  7f06           jcc
            bb = 50 if cpu._cond(0xF) else 49
        elif bb == 49:
            # 0x11B478  807dfc12       grp1
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x12
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B47C  7502           jcc
            bb = 51 if cpu._cond(0x5) else 50
        elif bb == 50:
            # 0x11B47E  eb0a           jmp
            bb = 52
        elif bb == 51:
            # 0x11B480  807dfc00       grp1
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B484  0f85b5fdffff   jcc
            bb = 4 if cpu._cond(0x5) else 52
        elif bb == 52:
            # 0x11B48A  807dfc00       grp1
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11B48E  7509           jcc
            bb = 54 if cpu._cond(0x5) else 53
        elif bb == 53:
            # 0x11B490  c745e400000000 mov
            _o = (sb["ss"] + r[5] + -0x1C) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            # 0x11B497  eb06           jmp
            bb = 55
        elif bb == 54:
            # 0x11B499  8b451c         mov
            _o = (sb["ss"] + r[5] + 0x1C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B49C  8945e4         mov
            _o = (sb["ss"] + r[5] + -0x1C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 55
        elif bb == 55:
            # 0x11B49F  8b45e4         mov
            _o = (sb["ss"] + r[5] + -0x1C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11B4A2  c9             leave
            interp_one32(cpu, 0x11B4A2)  # (interpreter fallback)
            # 0x11B4A3  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11B4A4  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11B4A5  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11B4A6  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_11b1df' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
