"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x122A9C  (56 instructions, 6 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x122A9C
SIGNATURE = bytes.fromhex('608d6c241c803d84')
MAX_ITERATIONS = 280000


def lift_122a9c(cpu):
    """Lifted replacement for flat 0x122A9C."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_122a9c')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x122A9C  60             pushad
            interp_one32(cpu, 0x122A9C)  # (interpreter fallback)
            # 0x122A9D  8d6c241c       lea
            r[5] = ((r[4] + 0x1C)) & 0xFFFFFFFF
            # 0x122AA1  803d84e3140040 grp1
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x40
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x122AA8  7411           jcc
            bb = 2 if cpu._cond(0x4) else 1
        elif bb == 1:
            # 0x122AAA  c60584e3140040 mov
            _o = (sb["ds"] + 0x14E384) & 0xFFFFFFFF
            mem.w8(_o, 0x40)
            # 0x122AB1  66b80540       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x4005) & 0xFFFF)
            # 0x122AB5  66bace03       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3CE) & 0xFFFF)
            # 0x122AB9  66ef           in/out
            interp_one32(cpu, 0x122AB9)  # (interpreter fallback)
            bb = 2
        elif bb == 2:
            # 0x122ABB  0fb71d167b1400 movzx/sx
            _o = (sb["ds"] + 0x147B16) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[3] = (_v) & 0xFFFFFFFF
            # 0x122AC2  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x122AC5  8bbb26e31400   mov
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122ACB  03bb36e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122AD1  03bb46e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122AD7  0fb71d187b1400 movzx/sx
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[3] = (_v) & 0xFFFFFFFF
            # 0x122ADE  c1e302         grp2
            cpu._shift(4, True, 3, 4, 0x02)
            # 0x122AE1  8bb326e31400   mov
            _o = (sb["ds"] + r[3] + 0x14E326) & 0xFFFFFFFF
            r[6] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122AE7  03b336e31400   add
            _o = (sb["ds"] + r[3] + 0x14E336) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122AED  03b346e31400   add
            _o = (sb["ds"] + r[3] + 0x14E346) & 0xFFFFFFFF
            _a = r[6]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122AF3  893de4e21400   mov
            _o = (sb["ds"] + 0x14E2E4) & 0xFFFFFFFF
            mem.w32(_o, r[7])
            # 0x122AF9  8935e0e21400   mov
            _o = (sb["ds"] + 0x14E2E0) & 0xFFFFFFFF
            mem.w32(_o, r[6])
            # 0x122AFF  037d08         add
            _o = (sb["ss"] + r[5] + 0x8) & 0xFFFFFFFF
            _a = r[7]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122B02  a15ee31400     mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B07  f7650c         grp3
            interp_one32(cpu, 0x122B07)  # (interpreter fallback)
            # 0x122B0A  03f8           add
            _a = r[7]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122B0C  893d68831400   mov
            _o = (sb["ds"] + 0x148368) & 0xFFFFFFFF
            mem.w32(_o, r[7])
            # 0x122B12  8b4508         mov
            _o = (sb["ss"] + r[5] + 0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B15  a306841400     mov
            _o = (sb["ds"] + 0x148406) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x122B1A  8b450c         mov
            _o = (sb["ss"] + r[5] + 0xC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B1D  a30a841400     mov
            _o = (sb["ds"] + 0x14840A) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x122B22  8b7d14         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B25  893d60831400   mov
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            mem.w32(_o, r[7])
            # 0x122B2B  8b7d10         mov
            _o = (sb["ss"] + r[5] + 0x10) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B2E  893d0e841400   mov
            _o = (sb["ds"] + 0x14840E) & 0xFFFFFFFF
            mem.w32(_o, r[7])
            # 0x122B34  eb29           jmp
            bb = 4
        elif bb == 3:
            # 0x122B36  0fbf5f04       movzx/sx
            _o = (sb["ds"] + r[7] + 0x4) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[3] = (_v) & 0xFFFFFFFF
            # 0x122B3A  2b1d06841400   sub
            _o = (sb["ds"] + 0x148406) & 0xFFFFFFFF
            _a = r[3]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[3] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122B40  0fbf5706       movzx/sx
            _o = (sb["ds"] + r[7] + 0x6) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[2] = (_v) & 0xFFFFFFFF
            # 0x122B44  2b150a841400   sub
            _o = (sb["ds"] + 0x14840A) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122B4A  668b4708       mov
            _o = (sb["ds"] + r[7] + 0x8) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x122B4E  66a374831400   mov
            _o = (sb["ds"] + 0x148374) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x122B54  e806020000     call
            emulate_call32(cpu, 0x122D5F, 0x122B59)
            # 0x122B59  8b3d0e841400   mov
            _o = (sb["ds"] + 0x14840E) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            bb = 4
        elif bb == 4:
            # 0x122B5F  83050e8414000a grp1
            _o = (sb["ds"] + 0x14840E) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x122B66  8b37           mov
            _o = (sb["ds"] + r[7]) & 0xFFFFFFFF
            r[6] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B68  83fe00         grp1
            _a = r[6]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122B6B  75c9           jcc
            bb = 3 if cpu._cond(0x5) else 5
        elif bb == 5:
            # 0x122B6D  c60585e314000f mov
            _o = (sb["ds"] + 0x14E385) & 0xFFFFFFFF
            mem.w8(_o, 0xF)
            # 0x122B74  66b8020f       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0xF02) & 0xFFFF)
            # 0x122B78  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x122B7C  66ef           in/out
            interp_one32(cpu, 0x122B7C)  # (interpreter fallback)
            # 0x122B7E  a160831400     mov
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B83  a3e8e21400     mov
            _o = (sb["ds"] + 0x14E2E8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x122B88  a10e841400     mov
            _o = (sb["ds"] + 0x14840E) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122B8D  a3ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x122B92  61             popad
            interp_one32(cpu, 0x122B92)  # (interpreter fallback)
            # 0x122B93  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_122a9c' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
