"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x118345  (38 instructions, 9 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x118345
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 190000


def lift_118345(cpu):
    """Lifted replacement for flat 0x118345."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_118345')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x118345  53             push
            cpu.push(r[3], 4)
            # 0x118346  56             push
            cpu.push(r[6], 4)
            # 0x118347  57             push
            cpu.push(r[7], 4)
            # 0x118348  55             push
            cpu.push(r[5], 4)
            # 0x118349  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11834B  81ec08000000   grp1
            _a = r[4]
            _b = 0x8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118351  ff054ce11400   inc
            _o = (sb["ds"] + 0x14E14C) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x118357  a150e11400     mov
            _o = (sb["ds"] + 0x14E150) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11835C  8945fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11835F  c745f800000000 mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 1
        elif bb == 1:
            # 0x118366  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118369  3b0548e11400   cmp
            _o = (sb["ds"] + 0x14E148) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11836F  7c0a           jcc
            bb = 4 if cpu._cond(0xC) else 2
        elif bb == 2:
            # 0x118371  eb39           jmp
            bb = 8
        elif bb == 3:
            # 0x118373  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118376  ff45f8         inc
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x118379  ebeb           jmp
            bb = 1
        elif bb == 4:
            # 0x11837B  8b154ce11400   mov
            _o = (sb["ds"] + 0x14E14C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118381  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118384  3b5010         cmp
            _o = (sb["ds"] + r[0] + 0x10) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118387  7c0e           jcc
            bb = 6 if cpu._cond(0xC) else 5
        elif bb == 5:
            # 0x118389  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11838C  8b5004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11838F  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118392  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118395  eb0c           jmp
            bb = 7
        elif bb == 6:
            # 0x118397  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11839A  8b500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11839D  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183A0  015008         add
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 7
        elif bb == 7:
            # 0x1183A3  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183A6  8345fc18       grp1
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x18
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x1183AA  ebc7           jmp
            bb = 3
        elif bb == 8:
            # 0x1183AC  c9             leave
            interp_one32(cpu, 0x1183AC)  # (interpreter fallback)
            # 0x1183AD  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1183AE  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1183AF  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1183B0  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_118345' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
