"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1195EE  (23 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x1195EE
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 115000


def lift_1195ee(cpu):
    """Lifted replacement for flat 0x1195EE."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1195ee')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1195EE  53             push
            cpu.push(r[3], 4)
            # 0x1195EF  56             push
            cpu.push(r[6], 4)
            # 0x1195F0  57             push
            cpu.push(r[7], 4)
            # 0x1195F1  55             push
            cpu.push(r[5], 4)
            # 0x1195F2  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x1195F4  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1195FA  a158e11400     mov
            _o = (sb["ds"] + 0x14E158) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1195FF  668b4002       mov
            _o = (sb["ds"] + r[0] + 0x2) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x119603  66a360e11400   mov
            _o = (sb["ds"] + 0x14E160) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x119609  a158e11400     mov
            _o = (sb["ds"] + 0x14E158) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11960E  668b4004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x119612  66a362e11400   mov
            _o = (sb["ds"] + 0x14E162) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x119618  a158e11400     mov
            _o = (sb["ds"] + 0x14E158) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11961D  668b400a       mov
            _o = (sb["ds"] + r[0] + 0xA) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x119621  66a35ce11400   mov
            _o = (sb["ds"] + 0x14E15C) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x119627  a158e11400     mov
            _o = (sb["ds"] + 0x14E158) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11962C  668b400c       mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x119630  66a35ee11400   mov
            _o = (sb["ds"] + 0x14E15E) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x119636  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x119637  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x119638  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x119639  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11963A  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1195ee' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
