"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1183B1  (44 instructions, 6 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x1183B1
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 220000


def lift_1183b1(cpu):
    """Lifted replacement for flat 0x1183B1."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1183b1')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1183B1  53             push
            cpu.push(r[3], 4)
            # 0x1183B2  56             push
            cpu.push(r[6], 4)
            # 0x1183B3  57             push
            cpu.push(r[7], 4)
            # 0x1183B4  55             push
            cpu.push(r[5], 4)
            # 0x1183B5  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x1183B7  81ec08000000   grp1
            _a = r[4]
            _b = 0x8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1183BD  a150e11400     mov
            _o = (sb["ds"] + 0x14E150) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183C2  8945fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1183C5  c745f800000000 mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 1
        elif bb == 1:
            # 0x1183CC  a148e11400     mov
            _o = (sb["ds"] + 0x14E148) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183D1  d1f8           grp2
            cpu._shift(7, True, 0, 4, 1)
            # 0x1183D3  3b45f8         cmp
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1183D6  7f0a           jcc
            bb = 4 if cpu._cond(0xF) else 2
        elif bb == 2:
            # 0x1183D8  eb5b           jmp
            bb = 5
        elif bb == 3:
            # 0x1183DA  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183DD  ff45f8         inc
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x1183E0  ebea           jmp
            bb = 1
        elif bb == 4:
            # 0x1183E2  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183E5  8b4014         mov
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183E8  8b1554e11400   mov
            _o = (sb["ds"] + 0x14E154) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183EE  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1183F0  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183F5  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1183F7  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183FA  8b5008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1183FD  c1fa04         grp2
            cpu._shift(7, True, 2, 4, 0x04)
            # 0x118400  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118405  66895004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x118409  8b45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11840C  8b4020         mov
            _o = (sb["ds"] + r[0] + 0x20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11840F  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x118412  89c2           mov
            r[2] = (r[0]) & 0xFFFFFFFF
            # 0x118414  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118419  66895006       mov
            _o = (sb["ds"] + r[0] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x11841D  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118422  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x118428  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11842F  8345fc30       grp1
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x30
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118433  eba5           jmp
            bb = 3
        elif bb == 5:
            # 0x118435  c9             leave
            interp_one32(cpu, 0x118435)  # (interpreter fallback)
            # 0x118436  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118437  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118438  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118439  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1183b1' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
