"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x11FD7B  (64 instructions, 24 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x11FD7B
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 320000


def lift_11fd7b(cpu):
    """Lifted replacement for flat 0x11FD7B."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_11fd7b')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x11FD7B  53             push
            cpu.push(r[3], 4)
            # 0x11FD7C  56             push
            cpu.push(r[6], 4)
            # 0x11FD7D  57             push
            cpu.push(r[7], 4)
            # 0x11FD7E  55             push
            cpu.push(r[5], 4)
            # 0x11FD7F  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11FD81  81ec10000000   grp1
            _a = r[4]
            _b = 0x10
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11FD87  a08ce41400     mov
            _o = (sb["ds"] + 0x14E48C) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x11FD8C  8845fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(0, 1))
            # 0x11FD8F  803d8be4140046 grp1
            _o = (sb["ds"] + 0x14E48B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x46
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FD96  7409           jcc
            bb = 2 if cpu._cond(0x4) else 1
        elif bb == 1:
            # 0x11FD98  803d8ee4140046 grp1
            _o = (sb["ds"] + 0x14E48E) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x46
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FD9F  7402           jcc
            bb = 3 if cpu._cond(0x4) else 2
        elif bb == 2:
            # 0x11FDA1  eb09           jmp
            bb = 4
        elif bb == 3:
            # 0x11FDA3  c745f801000000 mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, 0x1)
            # 0x11FDAA  eb07           jmp
            bb = 5
        elif bb == 4:
            # 0x11FDAC  c745f800000000 mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 5
        elif bb == 5:
            # 0x11FDB3  837df800       grp1
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11FDB7  7407           jcc
            bb = 7 if cpu._cond(0x4) else 6
        elif bb == 6:
            # 0x11FDB9  80358ce4140001 grp1
            _o = (sb["ds"] + 0x14E48C) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a ^ _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 7
        elif bb == 7:
            # 0x11FDC0  803d8be4140045 grp1
            _o = (sb["ds"] + 0x14E48B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x45
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FDC7  7409           jcc
            bb = 9 if cpu._cond(0x4) else 8
        elif bb == 8:
            # 0x11FDC9  803d8ee4140045 grp1
            _o = (sb["ds"] + 0x14E48E) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x45
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FDD0  7402           jcc
            bb = 10 if cpu._cond(0x4) else 9
        elif bb == 9:
            # 0x11FDD2  eb09           jmp
            bb = 11
        elif bb == 10:
            # 0x11FDD4  c745f401000000 mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w32(_o, 0x1)
            # 0x11FDDB  eb07           jmp
            bb = 12
        elif bb == 11:
            # 0x11FDDD  c745f400000000 mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 12
        elif bb == 12:
            # 0x11FDE4  837df400       grp1
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11FDE8  7407           jcc
            bb = 14 if cpu._cond(0x4) else 13
        elif bb == 13:
            # 0x11FDEA  80358ce4140002 grp1
            _o = (sb["ds"] + 0x14E48C) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a ^ _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 14
        elif bb == 14:
            # 0x11FDF1  803d8be414003a grp1
            _o = (sb["ds"] + 0x14E48B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x3A
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FDF8  7409           jcc
            bb = 16 if cpu._cond(0x4) else 15
        elif bb == 15:
            # 0x11FDFA  803d8ee414003a grp1
            _o = (sb["ds"] + 0x14E48E) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x3A
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FE01  7402           jcc
            bb = 17 if cpu._cond(0x4) else 16
        elif bb == 16:
            # 0x11FE03  eb09           jmp
            bb = 18
        elif bb == 17:
            # 0x11FE05  c745f001000000 mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w32(_o, 0x1)
            # 0x11FE0C  eb07           jmp
            bb = 19
        elif bb == 18:
            # 0x11FE0E  c745f000000000 mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 19
        elif bb == 19:
            # 0x11FE15  837df000       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11FE19  7407           jcc
            bb = 21 if cpu._cond(0x4) else 20
        elif bb == 20:
            # 0x11FE1B  80358ce4140004 grp1
            _o = (sb["ds"] + 0x14E48C) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x4
            _r = _a ^ _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 21
        elif bb == 21:
            # 0x11FE22  8a45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x11FE25  3a058ce41400   cmp
            _o = (sb["ds"] + 0x14E48C) & 0xFFFFFFFF
            _a = cpu.reg(0, 1)
            _b = mem.r8(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x11FE2B  7438           jcc
            bb = 23 if cpu._cond(0x4) else 22
        elif bb == 22:
            # 0x11FE2D  e86d410000     call
            emulate_call32(cpu, 0x123F9F, 0x11FE32)
            # 0x11FE32  e8d6000000     call
            emulate_call32(cpu, 0x11FF0D, 0x11FE37)
            # 0x11FE37  68ed000000     push
            cpu.push(0xED, 4)
            # 0x11FE3C  6a60           push
            cpu.push(0x60, 4)
            # 0x11FE3E  e860410000     call
            emulate_call32(cpu, 0x123FA3, 0x11FE43)
            # 0x11FE43  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11FE46  e8c2000000     call
            emulate_call32(cpu, 0x11FF0D, 0x11FE4B)
            # 0x11FE4B  a08ce41400     mov
            _o = (sb["ds"] + 0x14E48C) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x11FE50  2407           and
            _a = cpu.reg(0, 1)
            _b = 0x7
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x11FE52  0fb6c0         movzx/sx
            _v = cpu.reg(0, 1)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11FE55  50             push
            cpu.push(r[0], 4)
            # 0x11FE56  6a60           push
            cpu.push(0x60, 4)
            # 0x11FE58  e846410000     call
            emulate_call32(cpu, 0x123FA3, 0x11FE5D)
            # 0x11FE5D  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11FE60  e83c410000     call
            emulate_call32(cpu, 0x123FA1, 0x11FE65)
            bb = 23
        elif bb == 23:
            # 0x11FE65  c9             leave
            interp_one32(cpu, 0x11FE65)  # (interpreter fallback)
            # 0x11FE66  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11FE67  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11FE68  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11FE69  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_11fd7b' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
