"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x122288  (273 instructions, 75 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet — they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x122288
SIGNATURE = bytes.fromhex('8b15608314008305')
MAX_ITERATIONS = 1365000


def lift_122288(cpu):
    """Lifted replacement for flat 0x122288."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_122288')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x122288  8b1560831400   mov
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12228E  83056083140014 grp1
            _o = (sb["ds"] + 0x148360) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x14
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x122295  66c7020500     mov
            _o = (sb["ds"] + r[2]) & 0xFFFFFFFF
            mem.w16(_o, 0x5)
            # 0x12229A  66895a04       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[3] & 0xFFFF)
            # 0x12229E  66896a02       mov
            _o = (sb["ds"] + r[2] + 0x2) & 0xFFFFFFFF
            mem.w16(_o, r[5] & 0xFFFF)
            # 0x1222A2  0fb746fe       movzx/sx
            _o = (sb["ds"] + r[6] + -0x2) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1222A6  03c6           add
            _a = r[0]
            _b = r[6]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1222A8  894206         mov
            _o = (sb["ds"] + r[2] + 0x6) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1222AB  8bc7           mov
            r[0] = (r[7]) & 0xFFFFFFFF
            # 0x1222AD  2b05e4e21400   sub
            _o = (sb["ds"] + 0x14E2E4) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1222B3  89420a         mov
            _o = (sb["ds"] + r[2] + 0xA) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1222B6  a180831400     mov
            _o = (sb["ds"] + 0x148380) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1222BB  6689420e       mov
            _o = (sb["ds"] + r[2] + 0xE) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1222BF  a188831400     mov
            _o = (sb["ds"] + 0x148388) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1222C4  66894210       mov
            _o = (sb["ds"] + r[2] + 0x10) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1222C8  a178831400     mov
            _o = (sb["ds"] + 0x148378) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1222CD  66894212       mov
            _o = (sb["ds"] + r[2] + 0x12) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1222D1  8bcf           mov
            r[1] = (r[7]) & 0xFFFFFFFF
            # 0x1222D3  c1ef02         grp2
            cpu._shift(5, True, 7, 4, 0x02)
            # 0x1222D6  80e103         grp1
            _a = cpu.reg(1, 1)
            _b = 0x3
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(1, 1, _r & 0xFF)
            # 0x1222D9  b511           mov
            cpu.set_reg(5, 1, 0x11)
            # 0x1222DB  d2c5           grp2
            cpu._shift(0, True, 5, 1, r[1] & 0xFF)
            # 0x1222DD  882da4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(5, 1))
            # 0x1222E3  882da5831400   mov
            _o = (sb["ds"] + 0x1483A5) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(5, 1))
            # 0x1222E9  f7dd           grp3
            interp_one32(cpu, 0x1222E9)  # (interpreter fallback)
            # 0x1222EB  833d8083140000 grp1
            _o = (sb["ds"] + 0x148380) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1222F2  0f85c1000000   jcc
            bb = 23 if cpu._cond(0x5) else 1
        elif bb == 1:
            # 0x1222F8  833d8883140000 grp1
            _o = (sb["ds"] + 0x148388) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1222FF  0f85b3010000   jcc
            bb = 49 if cpu._cond(0x5) else 2
        elif bb == 2:
            # 0x122305  66c705768314000a00 mov
            _o = (sb["ds"] + 0x148376) & 0xFFFFFFFF
            mem.w16(_o, 0xA)
            bb = 3
        elif bb == 3:
            # 0x12230E  53             push
            cpu.push(r[3], 4)
            # 0x12230F  55             push
            cpu.push(r[5], 4)
            # 0x122310  56             push
            cpu.push(r[6], 4)
            # 0x122311  57             push
            cpu.push(r[7], 4)
            # 0x122312  b002           mov
            cpu.set_reg(0, 1, 0x02)
            # 0x122314  8a25a4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu.set_reg(4, 1, mem.r8(_o))
            # 0x12231A  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x12231E  66ef           in/out
            interp_one32(cpu, 0x12231E)  # (interpreter fallback)
            # 0x122320  0fb70576831400 movzx/sx
            _o = (sb["ds"] + 0x148376) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x122327  2bf0           sub
            _a = r[6]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122329  660306         add
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            _a = r[0] & 0xFFFF
            _b = mem.r16(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            r[0] = (r[0] & 0xFFFF0000) | ((_r & 0xFFFF) & 0xFFFF)
            # 0x12232C  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12232E  66830576831400fe grp1
            _o = (sb["ds"] + 0x148376) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0xFFFE
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            mem.w16(_o, _r & 0xFFFF)
            # 0x122336  2bc0           sub
            _a = r[0]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122338  8b0d78831400   mov
            _o = (sb["ds"] + 0x148378) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12233E  67e310         jecxz
            bb = 9 if ((r[1] & 0xFFFF) == 0) else 4
        elif bb == 4:
            # 0x122341  8a16           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x122343  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            bb = 5
        elif bb == 5:
            # 0x122344  ac             lodsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xAC, 0)
            # 0x122345  0ac0           or
            _a = cpu.reg(0, 1)
            _b = cpu.reg(0, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x122347  7c02           jcc
            bb = 7 if cpu._cond(0xC) else 6
        elif bb == 6:
            # 0x122349  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 7
        elif bb == 7:
            # 0x12234B  feca           grp4
            _old = cpu.reg(2, 1)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(2, 1, _r)
            # 0x12234D  75f5           jcc
            bb = 5 if cpu._cond(0x5) else 8
        elif bb == 8:
            # 0x12234F  e2f0           loop
            r[1] = (r[1] - 1) & 0xFFFFFFFF
            bb = 4 if (r[1] != 0) else 9
        elif bb == 9:
            # 0x122351  8b155ee31400   mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122357  2bd3           sub
            _a = r[2]
            _b = r[3]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122359  c1ea02         grp2
            cpu._shift(5, True, 2, 4, 0x02)
            # 0x12235C  89156c831400   mov
            _o = (sb["ds"] + 0x14836C) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 10
        elif bb == 10:
            # 0x122362  8a3e           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(7, 1, mem.r8(_o))
            # 0x122364  f6df           grp3
            interp_one32(cpu, 0x122364)  # (interpreter fallback)
            # 0x122366  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            bb = 11
        elif bb == 11:
            # 0x122367  8a0e           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(1, 1, mem.r8(_o))
            # 0x122369  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            # 0x12236A  0ac9           or
            _a = cpu.reg(1, 1)
            _b = cpu.reg(1, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(1, 1, _r & 0xFF)
            # 0x12236C  7c1d           jcc
            bb = 19 if cpu._cond(0xC) else 12
        elif bb == 12:
            # 0x12236E  f7c701000000   grp3
            interp_one32(cpu, 0x12236E)  # (interpreter fallback)
            # 0x122374  7402           jcc
            bb = 14 if cpu._cond(0x4) else 13
        elif bb == 13:
            # 0x122376  a4             movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0)
            # 0x122377  49             dec
            _old = r[1]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[1] = (_r) & 0xFFFFFFFF
            bb = 14
        elif bb == 14:
            # 0x122378  d1e9           grp2
            cpu._shift(5, True, 1, 4, 1)
            # 0x12237A  f366a5         movsd
            cpu._opsize = 2; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA5, 0xF3)
            # 0x12237D  7301           jcc
            bb = 16 if cpu._cond(0x3) else 15
        elif bb == 15:
            # 0x12237F  a4             movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0)
            bb = 16
        elif bb == 16:
            # 0x122380  fec7           grp4
            _old = cpu.reg(7, 1)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(7, 1, _r)
            # 0x122382  75e3           jcc
            bb = 11 if cpu._cond(0x5) else 17
        elif bb == 17:
            # 0x122384  03fa           add
            _a = r[7]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122386  45             inc
            _old = r[5]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[5] = (_r) & 0xFFFFFFFF
            # 0x122387  75d9           jcc
            bb = 10 if cpu._cond(0x5) else 18
        elif bb == 18:
            # 0x122389  eb0d           jmp
            bb = 21
        elif bb == 19:
            # 0x12238B  f6d9           grp3
            interp_one32(cpu, 0x12238B)  # (interpreter fallback)
            # 0x12238D  03f9           add
            _a = r[7]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12238F  fec7           grp4
            _old = cpu.reg(7, 1)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(7, 1, _r)
            # 0x122391  75d4           jcc
            bb = 11 if cpu._cond(0x5) else 20
        elif bb == 20:
            # 0x122393  03fa           add
            _a = r[7]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122395  45             inc
            _old = r[5]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[5] = (_r) & 0xFFFFFFFF
            # 0x122396  75ca           jcc
            bb = 10 if cpu._cond(0x5) else 21
        elif bb == 21:
            # 0x122398  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x122399  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12239A  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12239B  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12239C  4b             dec
            _old = r[3]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[3] = (_r) & 0xFFFFFFFF
            # 0x12239D  d005a4831400   grp2
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu._shift(0, False, _o, 1, 1)
            # 0x1223A3  83d700         grp1
            _a = r[7]
            _b = 0x0
            _c = 1 if cpu.eflags & CF else 0
            _r = _a + _b + _c
            cpu._flags_add(_a, _b, _r, 32, _c)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1223A6  8a15a4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x1223AC  3a15a5831400   cmp
            _o = (sb["ds"] + 0x1483A5) & 0xFFFFFFFF
            _a = cpu.reg(2, 1)
            _b = mem.r8(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x1223B2  0f8556ffffff   jcc
            bb = 3 if cpu._cond(0x5) else 22
        elif bb == 22:
            # 0x1223B8  c3             ret
            cpu.eip = cpu.pop(4)
            return
        elif bb == 23:
            # 0x1223B9  8b1580831400   mov
            _o = (sb["ds"] + 0x148380) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1223BF  83e203         grp1
            _a = r[2]
            _b = 0x3
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1223C2  89158c831400   mov
            _o = (sb["ds"] + 0x14838C) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1223C8  c13d8083140002 grp2
            _o = (sb["ds"] + 0x148380) & 0xFFFFFFFF
            cpu._shift(7, False, _o, 4, 0x02)
            # 0x1223CF  8b155ee31400   mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1223D5  c1ea02         grp2
            cpu._shift(5, True, 2, 4, 0x02)
            # 0x1223D8  89156c831400   mov
            _o = (sb["ds"] + 0x14836C) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 24
        elif bb == 24:
            # 0x1223DE  53             push
            cpu.push(r[3], 4)
            # 0x1223DF  55             push
            cpu.push(r[5], 4)
            # 0x1223E0  56             push
            cpu.push(r[6], 4)
            # 0x1223E1  57             push
            cpu.push(r[7], 4)
            # 0x1223E2  b002           mov
            cpu.set_reg(0, 1, 0x02)
            # 0x1223E4  8a25a4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu.set_reg(4, 1, mem.r8(_o))
            # 0x1223EA  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x1223EE  66ef           in/out
            interp_one32(cpu, 0x1223EE)  # (interpreter fallback)
            # 0x1223F0  bafbffffff     mov
            r[2] = (0xFFFFFFFB) & 0xFFFFFFFF
            # 0x1223F5  03158c831400   add
            _o = (sb["ds"] + 0x14838C) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1223FB  03d2           add
            _a = r[2]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1223FD  0fb71416       movzx/sx
            _o = (sb["ds"] + r[2] + r[6]) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[2] = (_v) & 0xFFFFFFFF
            # 0x122401  03f2           add
            _a = r[6]
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122403  2bc0           sub
            _a = r[0]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122405  8b0d78831400   mov
            _o = (sb["ds"] + 0x148378) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12240B  67e310         jecxz
            bb = 30 if ((r[1] & 0xFFFF) == 0) else 25
        elif bb == 25:
            # 0x12240E  8a16           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x122410  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            bb = 26
        elif bb == 26:
            # 0x122411  ac             lodsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xAC, 0)
            # 0x122412  0ac0           or
            _a = cpu.reg(0, 1)
            _b = cpu.reg(0, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x122414  7c02           jcc
            bb = 28 if cpu._cond(0xC) else 27
        elif bb == 27:
            # 0x122416  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 28
        elif bb == 28:
            # 0x122418  feca           grp4
            _old = cpu.reg(2, 1)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(2, 1, _r)
            # 0x12241A  75f5           jcc
            bb = 26 if cpu._cond(0x5) else 29
        elif bb == 29:
            # 0x12241C  e2f0           loop
            r[1] = (r[1] - 1) & 0xFFFFFFFF
            bb = 25 if (r[1] != 0) else 30
        elif bb == 30:
            # 0x12241E  8bd7           mov
            r[2] = (r[7]) & 0xFFFFFFFF
            bb = 31
        elif bb == 31:
            # 0x122420  8bfa           mov
            r[7] = (r[2]) & 0xFFFFFFFF
            # 0x122422  8b1d80831400   mov
            _o = (sb["ds"] + 0x148380) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122428  2bfb           sub
            _a = r[7]
            _b = r[3]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12242A  8a3e           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(7, 1, mem.r8(_o))
            # 0x12242C  f6df           grp3
            interp_one32(cpu, 0x12242C)  # (interpreter fallback)
            # 0x12242E  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            bb = 32
        elif bb == 32:
            # 0x12242F  8a0e           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(1, 1, mem.r8(_o))
            # 0x122431  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            # 0x122432  0ac9           or
            _a = cpu.reg(1, 1)
            _b = cpu.reg(1, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(1, 1, _r & 0xFF)
            # 0x122434  7c32           jcc
            bb = 43 if cpu._cond(0xC) else 33
        elif bb == 33:
            # 0x122436  8bc7           mov
            r[0] = (r[7]) & 0xFFFFFFFF
            # 0x122438  2bc2           sub
            _a = r[0]
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12243A  7d12           jcc
            bb = 37 if cpu._cond(0xD) else 34
        elif bb == 34:
            # 0x12243C  03c1           add
            _a = r[0]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12243E  7f06           jcc
            bb = 36 if cpu._cond(0xF) else 35
        elif bb == 35:
            # 0x122440  03f1           add
            _a = r[6]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122442  03f9           add
            _a = r[7]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122444  eb1a           jmp
            bb = 41
        elif bb == 36:
            # 0x122446  2bc8           sub
            _a = r[1]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[1] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122448  03f1           add
            _a = r[6]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12244A  03f9           add
            _a = r[7]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12244C  8bc8           mov
            r[1] = (r[0]) & 0xFFFFFFFF
            bb = 37
        elif bb == 37:
            # 0x12244E  f7c701000000   grp3
            interp_one32(cpu, 0x12244E)  # (interpreter fallback)
            # 0x122454  7402           jcc
            bb = 39 if cpu._cond(0x4) else 38
        elif bb == 38:
            # 0x122456  a4             movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0)
            # 0x122457  49             dec
            _old = r[1]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[1] = (_r) & 0xFFFFFFFF
            bb = 39
        elif bb == 39:
            # 0x122458  d1e9           grp2
            cpu._shift(5, True, 1, 4, 1)
            # 0x12245A  f366a5         movsd
            cpu._opsize = 2; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA5, 0xF3)
            # 0x12245D  7301           jcc
            bb = 41 if cpu._cond(0x3) else 40
        elif bb == 40:
            # 0x12245F  a4             movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0)
            bb = 41
        elif bb == 41:
            # 0x122460  2bc0           sub
            _a = r[0]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122462  fec7           grp4
            _old = cpu.reg(7, 1)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(7, 1, _r)
            # 0x122464  75c9           jcc
            bb = 32 if cpu._cond(0x5) else 42
        elif bb == 42:
            # 0x122466  eb08           jmp
            bb = 44
        elif bb == 43:
            # 0x122468  f6d9           grp3
            interp_one32(cpu, 0x122468)  # (interpreter fallback)
            # 0x12246A  03f9           add
            _a = r[7]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12246C  fec7           grp4
            _old = cpu.reg(7, 1)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(7, 1, _r)
            # 0x12246E  75bf           jcc
            bb = 32 if cpu._cond(0x5) else 44
        elif bb == 44:
            # 0x122470  03156c831400   add
            _o = (sb["ds"] + 0x14836C) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122476  45             inc
            _old = r[5]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[5] = (_r) & 0xFFFFFFFF
            # 0x122477  75a7           jcc
            bb = 31 if cpu._cond(0x5) else 45
        elif bb == 45:
            # 0x122479  ff058c831400   inc
            _o = (sb["ds"] + 0x14838C) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x12247F  833d8c83140004 grp1
            _o = (sb["ds"] + 0x14838C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x4
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x122486  7510           jcc
            bb = 47 if cpu._cond(0x5) else 46
        elif bb == 46:
            # 0x122488  c7058c83140000000000 mov
            _o = (sb["ds"] + 0x14838C) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            # 0x122492  ff0580831400   inc
            _o = (sb["ds"] + 0x148380) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            bb = 47
        elif bb == 47:
            # 0x122498  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x122499  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12249A  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12249B  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12249C  d005a4831400   grp2
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu._shift(0, False, _o, 1, 1)
            # 0x1224A2  83d700         grp1
            _a = r[7]
            _b = 0x0
            _c = 1 if cpu.eflags & CF else 0
            _r = _a + _b + _c
            cpu._flags_add(_a, _b, _r, 32, _c)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1224A5  8a15a4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x1224AB  3a15a5831400   cmp
            _o = (sb["ds"] + 0x1483A5) & 0xFFFFFFFF
            _a = cpu.reg(2, 1)
            _b = mem.r8(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x1224B1  0f8527ffffff   jcc
            bb = 24 if cpu._cond(0x5) else 48
        elif bb == 48:
            # 0x1224B7  c3             ret
            cpu.eip = cpu.pop(4)
            return
        elif bb == 49:
            # 0x1224B8  66c705768314000a00 mov
            _o = (sb["ds"] + 0x148376) & 0xFFFFFFFF
            mem.w16(_o, 0xA)
            # 0x1224C1  8b1588831400   mov
            _o = (sb["ds"] + 0x148388) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1224C7  891590831400   mov
            _o = (sb["ds"] + 0x148390) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1224CD  8b155ee31400   mov
            _o = (sb["ds"] + 0x14E35E) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1224D3  c1ea02         grp2
            cpu._shift(5, True, 2, 4, 0x02)
            # 0x1224D6  89156c831400   mov
            _o = (sb["ds"] + 0x14836C) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 50
        elif bb == 50:
            # 0x1224DC  53             push
            cpu.push(r[3], 4)
            # 0x1224DD  55             push
            cpu.push(r[5], 4)
            # 0x1224DE  56             push
            cpu.push(r[6], 4)
            # 0x1224DF  57             push
            cpu.push(r[7], 4)
            # 0x1224E0  b002           mov
            cpu.set_reg(0, 1, 0x02)
            # 0x1224E2  8a25a4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu.set_reg(4, 1, mem.r8(_o))
            # 0x1224E8  66bac403       mov
            r[2] = (r[2] & 0xFFFF0000) | ((0x3C4) & 0xFFFF)
            # 0x1224EC  66ef           in/out
            interp_one32(cpu, 0x1224EC)  # (interpreter fallback)
            # 0x1224EE  0fb70576831400 movzx/sx
            _o = (sb["ds"] + 0x148376) & 0xFFFFFFFF
            _v = mem.r16(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1224F5  2bf0           sub
            _a = r[6]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1224F7  660306         add
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            _a = r[0] & 0xFFFF
            _b = mem.r16(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            r[0] = (r[0] & 0xFFFF0000) | ((_r & 0xFFFF) & 0xFFFF)
            # 0x1224FA  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1224FC  66830576831400fe grp1
            _o = (sb["ds"] + 0x148376) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = 0xFFFE
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            mem.w16(_o, _r & 0xFFFF)
            # 0x122504  2bc0           sub
            _a = r[0]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122506  8b0d78831400   mov
            _o = (sb["ds"] + 0x148378) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12250C  67e310         jecxz
            bb = 56 if ((r[1] & 0xFFFF) == 0) else 51
        elif bb == 51:
            # 0x12250F  8a16           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x122511  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            bb = 52
        elif bb == 52:
            # 0x122512  ac             lodsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xAC, 0)
            # 0x122513  0ac0           or
            _a = cpu.reg(0, 1)
            _b = cpu.reg(0, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x122515  7c02           jcc
            bb = 54 if cpu._cond(0xC) else 53
        elif bb == 53:
            # 0x122517  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 54
        elif bb == 54:
            # 0x122519  feca           grp4
            _old = cpu.reg(2, 1)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(2, 1, _r)
            # 0x12251B  75f5           jcc
            bb = 52 if cpu._cond(0x5) else 55
        elif bb == 55:
            # 0x12251D  e2f0           loop
            r[1] = (r[1] - 1) & 0xFFFFFFFF
            bb = 51 if (r[1] != 0) else 56
        elif bb == 56:
            # 0x12251F  8b1590831400   mov
            _o = (sb["ds"] + 0x148390) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x122525  83c203         grp1
            _a = r[2]
            _b = 0x3
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122528  c1fa02         grp2
            cpu._shift(7, True, 2, 4, 0x02)
            # 0x12252B  891588831400   mov
            _o = (sb["ds"] + 0x148388) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x122531  ff0d90831400   dec
            _o = (sb["ds"] + 0x148390) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x122537  8bd7           mov
            r[2] = (r[7]) & 0xFFFFFFFF
            bb = 57
        elif bb == 57:
            # 0x122539  8bfa           mov
            r[7] = (r[2]) & 0xFFFFFFFF
            # 0x12253B  8a3e           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(7, 1, mem.r8(_o))
            # 0x12253D  f6df           grp3
            interp_one32(cpu, 0x12253D)  # (interpreter fallback)
            # 0x12253F  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            bb = 58
        elif bb == 58:
            # 0x122540  8a0e           mov
            _o = (sb["ds"] + r[6]) & 0xFFFFFFFF
            cpu.set_reg(1, 1, mem.r8(_o))
            # 0x122542  46             inc
            _old = r[6]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[6] = (_r) & 0xFFFFFFFF
            # 0x122543  0ac9           or
            _a = cpu.reg(1, 1)
            _b = cpu.reg(1, 1)
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(1, 1, _r & 0xFF)
            # 0x122545  7c36           jcc
            bb = 71 if cpu._cond(0xC) else 59
        elif bb == 59:
            # 0x122547  8bc7           mov
            r[0] = (r[7]) & 0xFFFFFFFF
            # 0x122549  2bc2           sub
            _a = r[0]
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12254B  2b0588831400   sub
            _o = (sb["ds"] + 0x148388) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122551  7d08           jcc
            bb = 62 if cpu._cond(0xD) else 60
        elif bb == 60:
            # 0x122553  03c1           add
            _a = r[0]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122555  7c08           jcc
            bb = 63 if cpu._cond(0xC) else 61
        elif bb == 61:
            # 0x122557  2bc8           sub
            _a = r[1]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[1] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122559  eb06           jmp
            bb = 64
        elif bb == 62:
            # 0x12255B  03f1           add
            _a = r[6]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12255D  eb16           jmp
            bb = 69
        elif bb == 63:
            # 0x12255F  2bc0           sub
            _a = r[0]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 64
        elif bb == 64:
            # 0x122561  f7c701000000   grp3
            interp_one32(cpu, 0x122561)  # (interpreter fallback)
            # 0x122567  7402           jcc
            bb = 66 if cpu._cond(0x4) else 65
        elif bb == 65:
            # 0x122569  a4             movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0)
            # 0x12256A  49             dec
            _old = r[1]
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[1] = (_r) & 0xFFFFFFFF
            bb = 66
        elif bb == 66:
            # 0x12256B  d1e9           grp2
            cpu._shift(5, True, 1, 4, 1)
            # 0x12256D  f366a5         movsd
            cpu._opsize = 2; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA5, 0xF3)
            # 0x122570  7301           jcc
            bb = 68 if cpu._cond(0x3) else 67
        elif bb == 67:
            # 0x122572  a4             movsb
            cpu._opsize = 4; cpu._adsize = 4; cpu._segovr = None
            cpu._string(0xA4, 0)
            bb = 68
        elif bb == 68:
            # 0x122573  03f0           add
            _a = r[6]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[6] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 69
        elif bb == 69:
            # 0x122575  2bc0           sub
            _a = r[0]
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122577  fec7           grp4
            _old = cpu.reg(7, 1)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(7, 1, _r)
            # 0x122579  75c5           jcc
            bb = 58 if cpu._cond(0x5) else 70
        elif bb == 70:
            # 0x12257B  eb08           jmp
            bb = 72
        elif bb == 71:
            # 0x12257D  f6d9           grp3
            interp_one32(cpu, 0x12257D)  # (interpreter fallback)
            # 0x12257F  03f9           add
            _a = r[7]
            _b = r[1]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x122581  fec7           grp4
            _old = cpu.reg(7, 1)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            cpu.set_reg(7, 1, _r)
            # 0x122583  75bb           jcc
            bb = 58 if cpu._cond(0x5) else 72
        elif bb == 72:
            # 0x122585  03156c831400   add
            _o = (sb["ds"] + 0x14836C) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12258B  45             inc
            _old = r[5]
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            r[5] = (_r) & 0xFFFFFFFF
            # 0x12258C  75ab           jcc
            bb = 57 if cpu._cond(0x5) else 73
        elif bb == 73:
            # 0x12258E  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x12258F  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x122590  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x122591  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x122592  d005a4831400   grp2
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu._shift(0, False, _o, 1, 1)
            # 0x122598  83d700         grp1
            _a = r[7]
            _b = 0x0
            _c = 1 if cpu.eflags & CF else 0
            _r = _a + _b + _c
            cpu._flags_add(_a, _b, _r, 32, _c)
            r[7] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x12259B  8a15a4831400   mov
            _o = (sb["ds"] + 0x1483A4) & 0xFFFFFFFF
            cpu.set_reg(2, 1, mem.r8(_o))
            # 0x1225A1  3a15a5831400   cmp
            _o = (sb["ds"] + 0x1483A5) & 0xFFFFFFFF
            _a = cpu.reg(2, 1)
            _b = mem.r8(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x1225A7  0f852fffffff   jcc
            bb = 50 if cpu._cond(0x5) else 74
        elif bb == 74:
            # 0x1225AD  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_122288' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
