"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x115381  (238 instructions, 34 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x115381
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 1190000


def lift_115381(cpu):
    """Lifted replacement for flat 0x115381."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_115381')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x115381  53             push
            cpu.push(r[3], 4)
            # 0x115382  56             push
            cpu.push(r[6], 4)
            # 0x115383  57             push
            cpu.push(r[7], 4)
            # 0x115384  55             push
            cpu.push(r[5], 4)
            # 0x115385  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x115387  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11538D  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115392  f6400102       grp3
            interp_one32(cpu, 0x115392)  # (interpreter fallback)
            # 0x115396  744b           jcc
            bb = 2 if cpu._cond(0x4) else 1
        elif bb == 1:
            # 0x115398  8b15e0de1400   mov
            _o = (sb["ds"] + 0x14DEE0) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11539E  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153A3  81c236750000   grp1
            _a = r[2]
            _b = 0x7536
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1153A9  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1153AB  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153B0  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153B6  668b4074       mov
            _o = (sb["ds"] + r[0] + 0x74) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1153BA  66894204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1153BE  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153C3  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153C9  668b4004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1153CD  66894206       mov
            _o = (sb["ds"] + r[2] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1153D1  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153D6  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x1153DC  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 2
        elif bb == 2:
            # 0x1153E3  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153E8  f60001         grp3
            interp_one32(cpu, 0x1153E8)  # (interpreter fallback)
            # 0x1153EB  7440           jcc
            bb = 6 if cpu._cond(0x4) else 3
        elif bb == 3:
            # 0x1153ED  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153F2  8b404c         mov
            _o = (sb["ds"] + r[0] + 0x4C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1153F5  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1153FA  833d208e14000c grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xC
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x115401  7d12           jcc
            bb = 5 if cpu._cond(0xD) else 4
        elif bb == 4:
            # 0x115403  b80c000000     mov
            r[0] = (0xC) & 0xFFFFFFFF
            # 0x115408  2b05208e1400   sub
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11540E  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115413  eb63           jmp
            bb = 11
        elif bb == 5:
            # 0x115415  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11541A  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11541D  8b8078631400   mov
            _o = (sb["ds"] + r[0] + 0x146378) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115423  a3c88d1400     mov
            _o = (sb["ds"] + 0x148DC8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115428  e97d000000     jmp
            bb = 14
        elif bb == 6:
            # 0x11542D  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115432  f60002         grp3
            interp_one32(cpu, 0x115432)  # (interpreter fallback)
            # 0x115435  7434           jcc
            bb = 10 if cpu._cond(0x4) else 7
        elif bb == 7:
            # 0x115437  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11543C  8b4054         mov
            _o = (sb["ds"] + r[0] + 0x54) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11543F  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115444  833d208e140008 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11544B  7c09           jcc
            bb = 9 if cpu._cond(0xC) else 8
        elif bb == 8:
            # 0x11544D  832d208e140008 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x115454  eb22           jmp
            bb = 11
        elif bb == 9:
            # 0x115456  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11545B  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11545E  8b80d0611400   mov
            _o = (sb["ds"] + r[0] + 0x1461D0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115464  a3c88d1400     mov
            _o = (sb["ds"] + 0x148DC8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115469  eb3f           jmp
            bb = 14
        elif bb == 10:
            # 0x11546B  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115470  8b401c         mov
            _o = (sb["ds"] + r[0] + 0x1C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115473  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 11
        elif bb == 11:
            # 0x115478  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11547D  f60080         grp3
            interp_one32(cpu, 0x11547D)  # (interpreter fallback)
            # 0x115480  7415           jcc
            bb = 13 if cpu._cond(0x4) else 12
        elif bb == 12:
            # 0x115482  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115487  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11548A  8b8088621400   mov
            _o = (sb["ds"] + r[0] + 0x146288) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115490  a3c88d1400     mov
            _o = (sb["ds"] + 0x148DC8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115495  eb13           jmp
            bb = 14
        elif bb == 13:
            # 0x115497  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11549C  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11549F  8b8018621400   mov
            _o = (sb["ds"] + r[0] + 0x146218) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154A5  a3c88d1400     mov
            _o = (sb["ds"] + 0x148DC8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 14
        elif bb == 14:
            # 0x1154AA  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154AF  f60004         grp3
            interp_one32(cpu, 0x1154AF)  # (interpreter fallback)
            # 0x1154B2  0f854b020000   jcc
            bb = 31 if cpu._cond(0x5) else 15
        elif bb == 15:
            # 0x1154B8  a1e0de1400     mov
            _o = (sb["ds"] + 0x14DEE0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154BD  8b15c88d1400   mov
            _o = (sb["ds"] + 0x148DC8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154C3  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1154C5  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154CA  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1154CC  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154D2  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154D7  668b12         mov
            _o = (sb["ds"] + r[2]) & 0xFFFFFFFF
            r[2] = (r[2] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1154DA  66895004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x1154DE  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154E3  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154E9  668b4004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1154ED  66894206       mov
            _o = (sb["ds"] + r[2] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1154F1  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1154F6  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x1154FC  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x115503  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115508  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11550E  8b40f6         mov
            _o = (sb["ds"] + r[0] + -0xA) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115511  894278         mov
            _o = (sb["ds"] + r[2] + 0x78) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115514  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115519  f60040         grp3
            interp_one32(cpu, 0x115519)  # (interpreter fallback)
            # 0x11551C  745e           jcc
            bb = 17 if cpu._cond(0x4) else 16
        elif bb == 16:
            # 0x11551E  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115523  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x115526  8b8068631400   mov
            _o = (sb["ds"] + r[0] + 0x146368) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11552C  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115531  a1e0de1400     mov
            _o = (sb["ds"] + 0x14DEE0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115536  8b15dc8d1400   mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11553C  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11553E  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115543  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x115545  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11554A  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115550  668b00         mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x115553  66894204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x115557  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11555D  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115562  668b5204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[2] = (r[2] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x115566  66895006       mov
            _o = (sb["ds"] + r[0] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x11556A  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11556F  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x115575  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 17
        elif bb == 17:
            # 0x11557C  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115581  f6400104       grp3
            interp_one32(cpu, 0x115581)  # (interpreter fallback)
            # 0x115585  7463           jcc
            bb = 19 if cpu._cond(0x4) else 18
        elif bb == 18:
            # 0x115587  a1248e1400     mov
            _o = (sb["ds"] + 0x148E24) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11558C  c1f802         grp2
            cpu._shift(7, True, 0, 4, 0x02)
            # 0x11558F  83e001         grp1
            _a = r[0]
            _b = 0x1
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x115592  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x115595  8b80f05e1400   mov
            _o = (sb["ds"] + r[0] + 0x145EF0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11559B  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1155A0  8b1534df1400   mov
            _o = (sb["ds"] + 0x14DF34) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155A6  0315dc8d1400   add
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1155AC  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155B1  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1155B3  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155B8  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155BE  668b00         mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1155C1  66894204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1155C5  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155CA  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155D0  668b4004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1155D4  66894206       mov
            _o = (sb["ds"] + r[2] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1155D8  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155DD  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x1155E3  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 19
        elif bb == 19:
            # 0x1155EA  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155EF  83782800       grp1
            _o = (sb["ds"] + r[0] + 0x28) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1155F3  7f0a           jcc
            bb = 21 if cpu._cond(0xF) else 20
        elif bb == 20:
            # 0x1155F5  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1155FA  f60008         grp3
            interp_one32(cpu, 0x1155FA)  # (interpreter fallback)
            # 0x1155FD  740a           jcc
            bb = 22 if cpu._cond(0x4) else 21
        elif bb == 21:
            # 0x1155FF  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115604  f60001         grp3
            interp_one32(cpu, 0x115604)  # (interpreter fallback)
            # 0x115607  7405           jcc
            bb = 23 if cpu._cond(0x4) else 22
        elif bb == 22:
            # 0x115609  e9f5000000     jmp
            bb = 31
        elif bb == 23:
            # 0x11560E  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115613  ff4840         dec
            _o = (sb["ds"] + r[0] + 0x40) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old - 1
            cpu._flags_sub(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x115616  83784000       grp1
            _o = (sb["ds"] + r[0] + 0x40) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11561A  7f54           jcc
            bb = 27 if cpu._cond(0xF) else 24
        elif bb == 24:
            # 0x11561C  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115621  ff4044         inc
            _o = (sb["ds"] + r[0] + 0x44) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x115624  8b4044         mov
            _o = (sb["ds"] + r[0] + 0x44) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115627  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11562A  8b806c5e1400   mov
            _o = (sb["ds"] + r[0] + 0x145E6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115630  a31c8e1400     mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115635  833d1c8e140000 grp1
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11563C  7d24           jcc
            bb = 26 if cpu._cond(0xD) else 25
        elif bb == 25:
            # 0x11563E  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115643  8b151c8e1400   mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115649  015044         add
            _o = (sb["ds"] + r[0] + 0x44) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11564C  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115651  8b4044         mov
            _o = (sb["ds"] + r[0] + 0x44) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115654  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x115657  8b806c5e1400   mov
            _o = (sb["ds"] + r[0] + 0x145E6C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11565D  a31c8e1400     mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 26
        elif bb == 26:
            # 0x115662  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115667  8b151c8e1400   mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11566D  895040         mov
            _o = (sb["ds"] + r[0] + 0x40) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 27
        elif bb == 27:
            # 0x115670  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115675  83782801       grp1
            _o = (sb["ds"] + r[0] + 0x28) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x115679  7518           jcc
            bb = 29 if cpu._cond(0x5) else 28
        elif bb == 28:
            # 0x11567B  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115680  8b4044         mov
            _o = (sb["ds"] + r[0] + 0x44) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115683  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x115686  8b80685e1400   mov
            _o = (sb["ds"] + r[0] + 0x145E68) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11568C  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115691  eb16           jmp
            bb = 30
        elif bb == 29:
            # 0x115693  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115698  8b4044         mov
            _o = (sb["ds"] + r[0] + 0x44) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11569B  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x11569E  8b8098601400   mov
            _o = (sb["ds"] + r[0] + 0x146098) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156A4  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 30
        elif bb == 30:
            # 0x1156A9  a134df1400     mov
            _o = (sb["ds"] + 0x14DF34) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156AE  8b15dc8d1400   mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156B4  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1156B6  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156BB  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x1156BD  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156C2  8b5020         mov
            _o = (sb["ds"] + r[0] + 0x20) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156C5  d1fa           grp2
            cpu._shift(7, True, 2, 4, 1)
            # 0x1156C7  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156CC  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156CE  29d0           sub
            _a = r[0]
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1156D0  83c004         grp1
            _a = r[0]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1156D3  89c2           mov
            r[2] = (r[0]) & 0xFFFFFFFF
            # 0x1156D5  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156DA  66895004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x1156DE  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156E4  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156E9  668b5204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[2] = (r[2] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1156ED  66895006       mov
            _o = (sb["ds"] + r[0] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x1156F1  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1156F6  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x1156FC  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 31
        elif bb == 31:
            # 0x115703  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115708  f6400101       grp3
            interp_one32(cpu, 0x115708)  # (interpreter fallback)
            # 0x11570C  745e           jcc
            bb = 33 if cpu._cond(0x4) else 32
        elif bb == 32:
            # 0x11570E  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115713  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x115716  8b80f8621400   mov
            _o = (sb["ds"] + r[0] + 0x1462F8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11571C  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x115721  a1e0de1400     mov
            _o = (sb["ds"] + 0x14DEE0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115726  8b15dc8d1400   mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11572C  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11572E  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115733  8910           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x115735  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11573A  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115740  668b00         mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x115743  66894204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x115747  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11574D  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x115752  668b5204       mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[2] = (r[2] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x115756  66895006       mov
            _o = (sb["ds"] + r[0] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x11575A  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11575F  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x115765  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 33
        elif bb == 33:
            # 0x11576C  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11576D  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11576E  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11576F  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x115770  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_115381' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
