"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x113702  (146 instructions, 10 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x113702
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 730000


def lift_113702(cpu):
    """Lifted replacement for flat 0x113702."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_113702')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x113702  53             push
            cpu.push(r[3], 4)
            # 0x113703  56             push
            cpu.push(r[6], 4)
            # 0x113704  57             push
            cpu.push(r[7], 4)
            # 0x113705  55             push
            cpu.push(r[5], 4)
            # 0x113706  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x113708  81ec08000000   grp1
            _a = r[4]
            _b = 0x8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11370E  a0167b1400     mov
            _o = (sb["ds"] + 0x147B16) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x113713  8845fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(0, 1))
            # 0x113716  0fbf056e741400 movzx/sx
            _o = (sb["ds"] + 0x14746E) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11371D  8945f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x113720  66c7056e7414000800 mov
            _o = (sb["ds"] + 0x14746E) & 0xFFFFFFFF
            mem.w16(_o, 0x8)
            # 0x113729  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11372E  8b15b08d1400   mov
            _o = (sb["ds"] + 0x148DB0) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113734  3b5014         cmp
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x113737  7d1d           jcc
            bb = 2 if cpu._cond(0xD) else 1
        elif bb == 1:
            # 0x113739  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11373E  83400471       grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x71
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x113742  8105b08d1400d0070000 grp1
            _o = (sb["ds"] + 0x148DB0) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x7D0
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x11374C  6a3c           push
            cpu.push(0x3C, 4)
            # 0x11374E  e8ba8a0000     call
            emulate_call32(cpu, 0x11C20D, 0x113753)
            # 0x113753  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 2
        elif bb == 2:
            # 0x113756  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11375C  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113761  8b5214         mov
            _o = (sb["ds"] + r[2] + 0x14) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113764  3b5018         cmp
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x113767  7513           jcc
            bb = 4 if cpu._cond(0x5) else 3
        elif bb == 3:
            # 0x113769  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11376F  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113774  8b5204         mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113777  3b5008         cmp
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11377A  741b           jcc
            bb = 5 if cpu._cond(0x4) else 4
        elif bb == 4:
            # 0x11377C  6a08           push
            cpu.push(0x8, 4)
            # 0x11377E  6a08           push
            cpu.push(0x8, 4)
            # 0x113780  31c0           xor
            _a = r[0]
            _b = r[0]
            _r = _a ^ _b
            cpu._flags_logic(_r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x113782  50             push
            cpu.push(r[0], 4)
            # 0x113783  ff3520df1400   push
            _o = (sb["ds"] + 0x14DF20) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x113789  b89c261400     mov
            r[0] = (0x14269C) & 0xFFFFFFFF
            # 0x11378E  50             push
            cpu.push(r[0], 4)
            # 0x11378F  e8ad7d0000     call
            emulate_call32(cpu, 0x11B541, 0x113794)
            # 0x113794  83c414         grp1
            _a = r[4]
            _b = 0x14
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 5
        elif bb == 5:
            # 0x113797  ff357ae31400   push
            _o = (sb["ds"] + 0x14E37A) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x11379D  ff3576e31400   push
            _o = (sb["ds"] + 0x14E376) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1137A3  ff3572e31400   push
            _o = (sb["ds"] + 0x14E372) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1137A9  ff356ee31400   push
            _o = (sb["ds"] + 0x14E36E) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1137AF  e8c67d0000     call
            emulate_call32(cpu, 0x11B57A, 0x1137B4)
            # 0x1137B4  83c410         grp1
            _a = r[4]
            _b = 0x10
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1137B7  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137BD  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137C2  8b5214         mov
            _o = (sb["ds"] + r[2] + 0x14) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137C5  3b5018         cmp
            _o = (sb["ds"] + r[0] + 0x18) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1137C8  747d           jcc
            bb = 7 if cpu._cond(0x4) else 6
        elif bb == 6:
            # 0x1137CA  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137CF  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137D5  8b4014         mov
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137D8  894218         mov
            _o = (sb["ds"] + r[2] + 0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1137DB  66a1187b1400   mov
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1137E1  66a3167b1400   mov
            _o = (sb["ds"] + 0x147B16) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x1137E7  6a06           push
            cpu.push(0x6, 4)
            # 0x1137E9  6a0a           push
            cpu.push(0xA, 4)
            # 0x1137EB  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1137F0  ff7014         push
            _o = (sb["ds"] + r[0] + 0x14) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1137F3  6a04           push
            cpu.push(0x4, 4)
            # 0x1137F5  6a38           push
            cpu.push(0x38, 4)
            # 0x1137F7  e8ab7c0000     call
            emulate_call32(cpu, 0x11B4A7, 0x1137FC)
            # 0x1137FC  83c414         grp1
            _a = r[4]
            _b = 0x14
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1137FF  6a04           push
            cpu.push(0x4, 4)
            # 0x113801  6a38           push
            cpu.push(0x38, 4)
            # 0x113803  0fbf05207b1400 movzx/sx
            _o = (sb["ds"] + 0x147B20) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11380A  50             push
            cpu.push(r[0], 4)
            # 0x11380B  6a0b           push
            cpu.push(0xB, 4)
            # 0x11380D  6a66           push
            cpu.push(0x66, 4)
            # 0x11380F  6a04           push
            cpu.push(0x4, 4)
            # 0x113811  6a38           push
            cpu.push(0x38, 4)
            # 0x113813  0fbf05187b1400 movzx/sx
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11381A  50             push
            cpu.push(r[0], 4)
            # 0x11381B  e897f80000     call
            emulate_call32(cpu, 0x1230B7, 0x113820)
            # 0x113820  83c420         grp1
            _a = r[4]
            _b = 0x20
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x113823  6a04           push
            cpu.push(0x4, 4)
            # 0x113825  6a38           push
            cpu.push(0x38, 4)
            # 0x113827  0fbf05227b1400 movzx/sx
            _o = (sb["ds"] + 0x147B22) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11382E  50             push
            cpu.push(r[0], 4)
            # 0x11382F  6a0b           push
            cpu.push(0xB, 4)
            # 0x113831  6a66           push
            cpu.push(0x66, 4)
            # 0x113833  6a04           push
            cpu.push(0x4, 4)
            # 0x113835  6a38           push
            cpu.push(0x38, 4)
            # 0x113837  0fbf05187b1400 movzx/sx
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11383E  50             push
            cpu.push(r[0], 4)
            # 0x11383F  e873f80000     call
            emulate_call32(cpu, 0x1230B7, 0x113844)
            # 0x113844  83c420         grp1
            _a = r[4]
            _b = 0x20
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 7
        elif bb == 7:
            # 0x113847  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11384D  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113852  8b5204         mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113855  3b5008         cmp
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x113858  0f84a1000000   jcc
            bb = 9 if cpu._cond(0x4) else 8
        elif bb == 8:
            # 0x11385E  a1dcdd1400     mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113863  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113869  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11386C  894208         mov
            _o = (sb["ds"] + r[2] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11386F  66a1187b1400   mov
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x113875  66a3167b1400   mov
            _o = (sb["ds"] + 0x147B16) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x11387B  6a02           push
            cpu.push(0x2, 4)
            # 0x11387D  6a0a           push
            cpu.push(0xA, 4)
            # 0x11387F  8b15dcdd1400   mov
            _o = (sb["ds"] + 0x14DDDC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113885  bb71000000     mov
            r[3] = (0x71) & 0xFFFFFFFF
            # 0x11388A  8b4204         mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11388D  8b5204         mov
            _o = (sb["ds"] + r[2] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x113890  c1fa1f         grp2
            cpu._shift(7, True, 2, 4, 0x1F)
            # 0x113893  f7fb           grp3
            interp_one32(cpu, 0x113893)  # (interpreter fallback)
            # 0x113895  50             push
            cpu.push(r[0], 4)
            # 0x113896  6a04           push
            cpu.push(0x4, 4)
            # 0x113898  6899000000     push
            cpu.push(0x99, 4)
            # 0x11389D  e8057c0000     call
            emulate_call32(cpu, 0x11B4A7, 0x1138A2)
            # 0x1138A2  83c414         grp1
            _a = r[4]
            _b = 0x14
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1138A5  6a04           push
            cpu.push(0x4, 4)
            # 0x1138A7  6899000000     push
            cpu.push(0x99, 4)
            # 0x1138AC  0fbf05207b1400 movzx/sx
            _o = (sb["ds"] + 0x147B20) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1138B3  50             push
            cpu.push(r[0], 4)
            # 0x1138B4  6a0b           push
            cpu.push(0xB, 4)
            # 0x1138B6  68a6000000     push
            cpu.push(0xA6, 4)
            # 0x1138BB  6a04           push
            cpu.push(0x4, 4)
            # 0x1138BD  6899000000     push
            cpu.push(0x99, 4)
            # 0x1138C2  0fbf05187b1400 movzx/sx
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1138C9  50             push
            cpu.push(r[0], 4)
            # 0x1138CA  e8e8f70000     call
            emulate_call32(cpu, 0x1230B7, 0x1138CF)
            # 0x1138CF  83c420         grp1
            _a = r[4]
            _b = 0x20
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1138D2  6a04           push
            cpu.push(0x4, 4)
            # 0x1138D4  6899000000     push
            cpu.push(0x99, 4)
            # 0x1138D9  0fbf05227b1400 movzx/sx
            _o = (sb["ds"] + 0x147B22) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1138E0  50             push
            cpu.push(r[0], 4)
            # 0x1138E1  6a0b           push
            cpu.push(0xB, 4)
            # 0x1138E3  68a6000000     push
            cpu.push(0xA6, 4)
            # 0x1138E8  6a04           push
            cpu.push(0x4, 4)
            # 0x1138EA  6899000000     push
            cpu.push(0x99, 4)
            # 0x1138EF  0fbf05187b1400 movzx/sx
            _o = (sb["ds"] + 0x147B18) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[0] = (_v) & 0xFFFFFFFF
            # 0x1138F6  50             push
            cpu.push(r[0], 4)
            # 0x1138F7  e8bbf70000     call
            emulate_call32(cpu, 0x1230B7, 0x1138FC)
            # 0x1138FC  83c420         grp1
            _a = r[4]
            _b = 0x20
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 9
        elif bb == 9:
            # 0x1138FF  660fb645fc     movzx/sx
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (r[0] & 0xFFFF0000) | ((_v) & 0xFFFF)
            # 0x113904  66a3167b1400   mov
            _o = (sb["ds"] + 0x147B16) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x11390A  8b45f8         mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11390D  66a36e741400   mov
            _o = (sb["ds"] + 0x14746E) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x113913  c9             leave
            interp_one32(cpu, 0x113913)  # (interpreter fallback)
            # 0x113914  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x113915  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x113916  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x113917  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_113702' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
