"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x11C960  (33 instructions, 3 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x11C960
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 165000


def lift_11c960(cpu):
    """Lifted replacement for flat 0x11C960."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_11c960')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x11C960  53             push
            cpu.push(r[3], 4)
            # 0x11C961  56             push
            cpu.push(r[6], 4)
            # 0x11C962  57             push
            cpu.push(r[7], 4)
            # 0x11C963  55             push
            cpu.push(r[5], 4)
            # 0x11C964  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11C966  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11C96C  ff35e8e21400   push
            _o = (sb["ds"] + 0x14E2E8) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x11C972  ff35dce21400   push
            _o = (sb["ds"] + 0x14E2DC) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x11C978  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C97B  50             push
            cpu.push(r[0], 4)
            # 0x11C97C  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C97F  50             push
            cpu.push(r[0], 4)
            # 0x11C980  e817610000     call
            emulate_call32(cpu, 0x122A9C, 0x11C985)
            # 0x11C985  83c410         grp1
            _a = r[4]
            _b = 0x10
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11C988  8b15e8e21400   mov
            _o = (sb["ds"] + 0x14E2E8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C98E  66c7020000     mov
            _o = (sb["ds"] + r[2]) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x11C993  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C999  2b15dce21400   sub
            _o = (sb["ds"] + 0x14E2DC) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11C99F  bb0a000000     mov
            r[3] = (0xA) & 0xFFFFFFFF
            # 0x11C9A4  89d0           mov
            r[0] = (r[2]) & 0xFFFFFFFF
            # 0x11C9A6  c1fa1f         grp2
            cpu._shift(7, True, 2, 4, 0x1F)
            # 0x11C9A9  f7fb           grp3
            interp_one32(cpu, 0x11C9A9)  # (interpreter fallback)
            # 0x11C9AB  6b15707414000a imul
            interp_one32(cpu, 0x11C9AB)  # (interpreter fallback)
            # 0x11C9B2  39d0           cmp
            _a = r[0]
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11C9B4  7609           jcc
            bb = 2 if cpu._cond(0x6) else 1
        elif bb == 1:
            # 0x11C9B6  66c7056c7414000704 mov
            _o = (sb["ds"] + 0x14746C) & 0xFFFFFFFF
            mem.w16(_o, 0x407)
            bb = 2
        elif bb == 2:
            # 0x11C9BF  a1dce21400     mov
            _o = (sb["ds"] + 0x14E2DC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C9C4  a3ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11C9C9  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9CA  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9CB  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9CC  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9CD  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_11c960' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
