"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1245AD  (16 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x1245AD
SIGNATURE = bytes.fromhex('535657558b6c241c')
MAX_ITERATIONS = 80000


def lift_1245ad(cpu):
    """Lifted replacement for flat 0x1245AD."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1245ad')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1245AD  53             push
            cpu.push(r[3], 4)
            # 0x1245AE  56             push
            cpu.push(r[6], 4)
            # 0x1245AF  57             push
            cpu.push(r[7], 4)
            # 0x1245B0  55             push
            cpu.push(r[5], 4)
            # 0x1245B1  8b6c241c       mov
            _o = (sb["ss"] + r[4] + 0x1C) & 0xFFFFFFFF
            r[5] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245B5  8b742414       mov
            _o = (sb["ss"] + r[4] + 0x14) & 0xFFFFFFFF
            r[6] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245B9  8b7c2418       mov
            _o = (sb["ss"] + r[4] + 0x18) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245BD  8b5c2420       mov
            _o = (sb["ss"] + r[4] + 0x20) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245C1  89ea           mov
            r[2] = (r[5]) & 0xFFFFFFFF
            # 0x1245C3  e822110000     call
            emulate_call32(cpu, 0x1256EA, 0x1245C8)
            # 0x1245C8  8b4500         mov
            _o = (sb["ss"] + r[5]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245CB  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1245CC  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1245CD  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1245CE  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1245CF  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1245ad' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
