"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1245D0  (19 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x1245D0
SIGNATURE = bytes.fromhex('5383ec0c89e050e8')
MAX_ITERATIONS = 95000


def lift_1245d0(cpu):
    """Lifted replacement for flat 0x1245D0."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1245d0')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1245D0  53             push
            cpu.push(r[3], 4)
            # 0x1245D1  83ec0c         grp1
            _a = r[4]
            _b = 0xC
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1245D4  89e0           mov
            r[0] = (r[4]) & 0xFFFFFFFF
            # 0x1245D6  50             push
            cpu.push(r[0], 4)
            # 0x1245D7  e8ec140000     call
            emulate_call32(cpu, 0x125AC8, 0x1245DC)
            # 0x1245DC  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1245DF  89e0           mov
            r[0] = (r[4]) & 0xFFFFFFFF
            # 0x1245E1  50             push
            cpu.push(r[0], 4)
            # 0x1245E2  8b542420       mov
            _o = (sb["ss"] + r[4] + 0x20) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245E6  52             push
            cpu.push(r[2], 4)
            # 0x1245E7  8b5c2420       mov
            _o = (sb["ss"] + r[4] + 0x20) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245EB  53             push
            cpu.push(r[3], 4)
            # 0x1245EC  8b4c2420       mov
            _o = (sb["ss"] + r[4] + 0x20) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1245F0  51             push
            cpu.push(r[1], 4)
            # 0x1245F1  e8b7ffffff     call
            emulate_call32(cpu, 0x1245AD, 0x1245F6)
            # 0x1245F6  83c410         grp1
            _a = r[4]
            _b = 0x10
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1245F9  83c40c         grp1
            _a = r[4]
            _b = 0xC
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1245FC  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1245FD  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1245d0' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
