"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x121258  (58 instructions, 12 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x121258
SIGNATURE = bytes.fromhex('505152668cdac1c2')
MAX_ITERATIONS = 290000


def lift_121258(cpu):
    """Lifted replacement for flat 0x121258."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_121258')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x121258  50             push
            cpu.push(r[0], 4)
            # 0x121259  51             push
            cpu.push(r[1], 4)
            # 0x12125A  52             push
            cpu.push(r[2], 4)
            # 0x12125B  668cda         mov sreg
            interp_one32(cpu, 0x12125B)  # (interpreter fallback)
            # 0x12125E  c1c210         grp2
            cpu._shift(0, True, 2, 4, 0x10)
            # 0x121261  66b81400       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x14) & 0xFFFF)
            # 0x121265  8ed8           mov sreg
            interp_one32(cpu, 0x121265)  # (interpreter fallback)
            # 0x121267  668b15fce21400 mov
            _o = (sb["ds"] + 0x14E2FC) & 0xFFFFFFFF
            r[2] = (r[2] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x12126E  6683c20e       grp1
            _a = r[2] & 0xFFFF
            _b = 0xE
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            r[2] = (r[2] & 0xFFFF0000) | ((_r & 0xFFFF) & 0xFFFF)
            # 0x121272  ec             in/out
            interp_one32(cpu, 0x121272)  # (interpreter fallback)
            # 0x121273  833d5874140000 grp1
            _o = (sb["ds"] + 0x147458) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x12127A  7453           jcc
            bb = 10 if cpu._cond(0x4) else 1
        elif bb == 1:
            # 0x12127C  a14c741400     mov
            _o = (sb["ds"] + 0x14744C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x121281  39055c741400   cmp
            _o = (sb["ds"] + 0x14745C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x121287  7536           jcc
            bb = 9 if cpu._cond(0x5) else 2
        elif bb == 2:
            # 0x121289  6683c2fe       grp1
            _a = r[2] & 0xFFFF
            _b = 0xFFFE
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            r[2] = (r[2] & 0xFFFF0000) | ((_r & 0xFFFF) & 0xFFFF)
            # 0x12128D  b9e8030000     mov
            r[1] = (0x3E8) & 0xFFFFFFFF
            bb = 3
        elif bb == 3:
            # 0x121292  ec             in/out
            interp_one32(cpu, 0x121292)  # (interpreter fallback)
            # 0x121293  a880           test
            cpu._flags_logic((cpu.reg(0, 1)) & 0x80, 8)
            # 0x121295  e0fb           loopnz
            r[1] = (r[1] - 1) & 0xFFFFFFFF
            bb = 3 if (r[1] != 0 and not (cpu.eflags & ZF)) else 4
        elif bb == 4:
            # 0x121297  b014           mov
            cpu.set_reg(0, 1, 0x14)
            # 0x121299  ee             in/out
            interp_one32(cpu, 0x121299)  # (interpreter fallback)
            # 0x12129A  b9e8030000     mov
            r[1] = (0x3E8) & 0xFFFFFFFF
            bb = 5
        elif bb == 5:
            # 0x12129F  ec             in/out
            interp_one32(cpu, 0x12129F)  # (interpreter fallback)
            # 0x1212A0  a880           test
            cpu._flags_logic((cpu.reg(0, 1)) & 0x80, 8)
            # 0x1212A2  e0fb           loopnz
            r[1] = (r[1] - 1) & 0xFFFFFFFF
            bb = 5 if (r[1] != 0 and not (cpu.eflags & ZF)) else 6
        elif bb == 6:
            # 0x1212A4  b07f           mov
            cpu.set_reg(0, 1, 0x7F)
            # 0x1212A6  ee             in/out
            interp_one32(cpu, 0x1212A6)  # (interpreter fallback)
            # 0x1212A7  b9e8030000     mov
            r[1] = (0x3E8) & 0xFFFFFFFF
            bb = 7
        elif bb == 7:
            # 0x1212AC  ec             in/out
            interp_one32(cpu, 0x1212AC)  # (interpreter fallback)
            # 0x1212AD  a880           test
            cpu._flags_logic((cpu.reg(0, 1)) & 0x80, 8)
            # 0x1212AF  e0fb           loopnz
            r[1] = (r[1] - 1) & 0xFFFFFFFF
            bb = 7 if (r[1] != 0 and not (cpu.eflags & ZF)) else 8
        elif bb == 8:
            # 0x1212B1  b002           mov
            cpu.set_reg(0, 1, 0x02)
            # 0x1212B3  ee             in/out
            interp_one32(cpu, 0x1212B3)  # (interpreter fallback)
            # 0x1212B4  66c7052c741400ffff mov
            _o = (sb["ds"] + 0x14742C) & 0xFFFFFFFF
            mem.w16(_o, 0xFFFF)
            # 0x1212BD  eb19           jmp
            bb = 11
        elif bb == 9:
            # 0x1212BF  a35c741400     mov
            _o = (sb["ds"] + 0x14745C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1212C4  50             push
            cpu.push(r[0], 4)
            # 0x1212C5  e8ad000000     call
            emulate_call32(cpu, 0x121377, 0x1212CA)
            # 0x1212CA  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1212CD  ebba           jmp
            bb = 2
        elif bb == 10:
            # 0x1212CF  66c7052c7414000000 mov
            _o = (sb["ds"] + 0x14742C) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            bb = 11
        elif bb == 11:
            # 0x1212D8  668cc2         mov sreg
            interp_one32(cpu, 0x1212D8)  # (interpreter fallback)
            # 0x1212DB  fc             cld
            interp_one32(cpu, 0x1212DB)  # (interpreter fallback)
            # 0x1212DC  66b81400       mov
            r[0] = (r[0] & 0xFFFF0000) | ((0x14) & 0xFFFF)
            # 0x1212E0  8ec0           mov sreg
            interp_one32(cpu, 0x1212E0)  # (interpreter fallback)
            # 0x1212E2  60             pushad
            interp_one32(cpu, 0x1212E2)  # (interpreter fallback)
            # 0x1212E3  fb             sti
            interp_one32(cpu, 0x1212E3)  # (interpreter fallback)
            # 0x1212E4  e8d4000000     call
            emulate_call32(cpu, 0x1213BD, 0x1212E9)
            # 0x1212E9  e80db1ffff     call
            emulate_call32(cpu, 0x11C3FB, 0x1212EE)
            # 0x1212EE  61             popad
            interp_one32(cpu, 0x1212EE)  # (interpreter fallback)
            # 0x1212EF  8ec2           mov sreg
            interp_one32(cpu, 0x1212EF)  # (interpreter fallback)
            # 0x1212F1  c1c210         grp2
            cpu._shift(0, True, 2, 4, 0x10)
            # 0x1212F4  8eda           mov sreg
            interp_one32(cpu, 0x1212F4)  # (interpreter fallback)
            # 0x1212F6  5a             pop
            r[2] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1212F7  59             pop
            r[1] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1212F8  58             pop
            r[0] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x1212F9  cf             iretd
            cpu.eip = cpu.pop(4)
            cpu.set_seg("cs", cpu.pop(4))
            cpu.eflags = (cpu.pop(4) & 0x0FD5) | 0x0002
            return
    raise LiftRuntimeError(
        'lift_121258' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
