"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x118004  (32 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x118004
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 160000


def lift_118004(cpu):
    """Lifted replacement for flat 0x118004."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_118004')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x118004  53             push
            cpu.push(r[3], 4)
            # 0x118005  56             push
            cpu.push(r[6], 4)
            # 0x118006  57             push
            cpu.push(r[7], 4)
            # 0x118007  55             push
            cpu.push(r[5], 4)
            # 0x118008  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11800A  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118010  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118013  a358e11400     mov
            _o = (sb["ds"] + 0x14E158) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118018  e8d1150000     call
            emulate_call32(cpu, 0x1195EE, 0x11801D)
            # 0x11801D  0fbf155ce11400 movzx/sx
            _o = (sb["ds"] + 0x14E15C) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[2] = (_v) & 0xFFFFFFFF
            # 0x118024  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118027  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118029  0fbf155ee11400 movzx/sx
            _o = (sb["ds"] + 0x14E15E) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[2] = (_v) & 0xFFFFFFFF
            # 0x118030  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118033  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118036  0fbf1560e11400 movzx/sx
            _o = (sb["ds"] + 0x14E160) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[2] = (_v) & 0xFFFFFFFF
            # 0x11803D  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118040  0310           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118042  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118045  83ea02         grp1
            _a = r[2]
            _b = 0x2
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118048  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x11804B  0fbf1562e11400 movzx/sx
            _o = (sb["ds"] + 0x14E162) & 0xFFFFFFFF
            _v = mem.r16(_o)
            _v = (_v - 0x10000) if _v & 0x8000 else _v
            r[2] = (_v) & 0xFFFFFFFF
            # 0x118052  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118055  035004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = r[2]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118058  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11805B  83ea02         grp1
            _a = r[2]
            _b = 0x2
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11805E  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118061  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118062  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118063  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118064  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118065  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_118004' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
