"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1256EA  (28 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x1256EA
SIGNATURE = bytes.fromhex('5506531e52e82e00')
MAX_ITERATIONS = 140000


def lift_1256ea(cpu):
    """Lifted replacement for flat 0x1256EA."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1256ea')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1256EA  55             push
            cpu.push(r[5], 4)
            # 0x1256EB  06             push es
            interp_one32(cpu, 0x1256EB)  # (interpreter fallback)
            # 0x1256EC  53             push
            cpu.push(r[3], 4)
            # 0x1256ED  1e             push ds
            interp_one32(cpu, 0x1256ED)  # (interpreter fallback)
            # 0x1256EE  52             push
            cpu.push(r[2], 4)
            # 0x1256EF  e82e000000     call
            emulate_call32(cpu, 0x125722, 0x1256F4)
            # 0x1256F4  1e             push ds
            interp_one32(cpu, 0x1256F4)  # (interpreter fallback)
            # 0x1256F5  57             push
            cpu.push(r[7], 4)
            # 0x1256F6  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x1256F8  8b7d08         mov
            _o = (sb["ss"] + r[5] + 0x8) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1256FB  8e5d0c         mov sreg
            interp_one32(cpu, 0x1256FB)  # (interpreter fallback)
            # 0x1256FE  8907           mov
            _o = (sb["ds"] + r[7]) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x125700  895f04         mov
            _o = (sb["ds"] + r[7] + 0x4) & 0xFFFFFFFF
            mem.w32(_o, r[3])
            # 0x125703  894f08         mov
            _o = (sb["ds"] + r[7] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[1])
            # 0x125706  89570c         mov
            _o = (sb["ds"] + r[7] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x125709  897710         mov
            _o = (sb["ds"] + r[7] + 0x10) & 0xFFFFFFFF
            mem.w32(_o, r[6])
            # 0x12570C  8f4714         pop
            _o = (sb["ds"] + r[7] + 0x14) & 0xFFFFFFFF
            _v = cpu.pop(4)
            mem.w32(_o, _v)
            # 0x12570F  19c0           sbb
            _a = r[0]
            _b = r[0]
            _c = 1 if cpu.eflags & CF else 0
            _r = _a - _b - _c
            cpu._flags_sub(_a, _b, _r, 32, _c)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x125711  894718         mov
            _o = (sb["ds"] + r[7] + 0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x125714  58             pop
            r[0] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x125715  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x125716  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x125717  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x125718  66894306       mov
            _o = (sb["ds"] + r[3] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x12571C  668c03         mov sreg
            interp_one32(cpu, 0x12571C)  # (interpreter fallback)
            # 0x12571F  07             pop es
            interp_one32(cpu, 0x12571F)  # (interpreter fallback)
            # 0x125720  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x125721  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1256ea' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
