"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x125AC8  (16 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x125AC8
SIGNATURE = bytes.fromhex('538b5c24088cc866')
MAX_ITERATIONS = 80000


def lift_125ac8(cpu):
    """Lifted replacement for flat 0x125AC8."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_125ac8')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x125AC8  53             push
            cpu.push(r[3], 4)
            # 0x125AC9  8b5c2408       mov
            _o = (sb["ss"] + r[4] + 0x8) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x125ACD  8cc8           mov sreg
            interp_one32(cpu, 0x125ACD)  # (interpreter fallback)
            # 0x125ACF  66894302       mov
            _o = (sb["ds"] + r[3] + 0x2) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x125AD3  8cd8           mov sreg
            interp_one32(cpu, 0x125AD3)  # (interpreter fallback)
            # 0x125AD5  66894306       mov
            _o = (sb["ds"] + r[3] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x125AD9  8cc0           mov sreg
            interp_one32(cpu, 0x125AD9)  # (interpreter fallback)
            # 0x125ADB  668903         mov
            _o = (sb["ds"] + r[3]) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x125ADE  8cd0           mov sreg
            interp_one32(cpu, 0x125ADE)  # (interpreter fallback)
            # 0x125AE0  66894304       mov
            _o = (sb["ds"] + r[3] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x125AE4  8ce0           mov sreg
            interp_one32(cpu, 0x125AE4)  # (interpreter fallback)
            # 0x125AE6  66894308       mov
            _o = (sb["ds"] + r[3] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x125AEA  8ce8           mov sreg
            interp_one32(cpu, 0x125AEA)  # (interpreter fallback)
            # 0x125AEC  6689430a       mov
            _o = (sb["ds"] + r[3] + 0xA) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            # 0x125AF0  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x125AF1  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_125ac8' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
