"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x11C9CE  (18 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x11C9CE
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 90000


def lift_11c9ce(cpu):
    """Lifted replacement for flat 0x11C9CE."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_11c9ce')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x11C9CE  53             push
            cpu.push(r[3], 4)
            # 0x11C9CF  56             push
            cpu.push(r[6], 4)
            # 0x11C9D0  57             push
            cpu.push(r[7], 4)
            # 0x11C9D1  55             push
            cpu.push(r[5], 4)
            # 0x11C9D2  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11C9D4  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11C9DA  e857ffffff     call
            emulate_call32(cpu, 0x11C936, 0x11C9DF)
            # 0x11C9DF  8b4518         mov
            _o = (sb["ss"] + r[5] + 0x18) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C9E2  50             push
            cpu.push(r[0], 4)
            # 0x11C9E3  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11C9E6  50             push
            cpu.push(r[0], 4)
            # 0x11C9E7  e874ffffff     call
            emulate_call32(cpu, 0x11C960, 0x11C9EC)
            # 0x11C9EC  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11C9EF  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9F0  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9F1  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9F2  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11C9F3  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_11c9ce' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
