"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x125722  (13 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, call_linked32,
                                   check_signature, emulate_call32,
                                   emulate_int32, interp_one32)

ENTRY = 0x125722
SIGNATURE = bytes.fromhex('8d34762e8d86c857')
MAX_ITERATIONS = 65000


def lift_125722(cpu):
    """Lifted replacement for flat 0x125722."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_125722')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x125722  8d3476         lea
            r[6] = (((r[6] << 1) + r[6])) & 0xFFFFFFFF
            # 0x125725  2e8d86c8571200 lea
            r[0] = ((r[6] + 0x1257C8)) & 0xFFFFFFFF
            # 0x12572C  50             push
            cpu.push(r[0], 4)
            # 0x12572D  8e03           mov sreg
            interp_one32(cpu, 0x12572D)  # (interpreter fallback)
            # 0x12572F  668b6b06       mov
            _o = (sb["ds"] + r[3] + 0x6) & 0xFFFFFFFF
            r[5] = (r[5] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x125733  8b07           mov
            _o = (sb["ds"] + r[7]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x125735  8b5f04         mov
            _o = (sb["ds"] + r[7] + 0x4) & 0xFFFFFFFF
            r[3] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x125738  8b4f08         mov
            _o = (sb["ds"] + r[7] + 0x8) & 0xFFFFFFFF
            r[1] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12573B  8b570c         mov
            _o = (sb["ds"] + r[7] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x12573E  8b7710         mov
            _o = (sb["ds"] + r[7] + 0x10) & 0xFFFFFFFF
            r[6] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x125741  8b7f14         mov
            _o = (sb["ds"] + r[7] + 0x14) & 0xFFFFFFFF
            r[7] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x125744  8edd           mov sreg
            interp_one32(cpu, 0x125744)  # (interpreter fallback)
            # 0x125746  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_125722' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
