"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x11EE65  (27 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x11EE65
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 135000


def lift_11ee65(cpu):
    """Lifted replacement for flat 0x11EE65."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_11ee65')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x11EE65  53             push
            cpu.push(r[3], 4)
            # 0x11EE66  56             push
            cpu.push(r[6], 4)
            # 0x11EE67  57             push
            cpu.push(r[7], 4)
            # 0x11EE68  55             push
            cpu.push(r[5], 4)
            # 0x11EE69  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x11EE6B  81ec00000000   grp1
            _a = r[4]
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11EE71  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11EE74  c1f802         grp2
            cpu._shift(7, True, 0, 4, 0x02)
            # 0x11EE77  2500ff0000     and
            _a = r[0]
            _b = 0xFF00
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11EE7C  0c0c           or
            _a = cpu.reg(0, 1)
            _b = 0xC
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x11EE7E  50             push
            cpu.push(r[0], 4)
            # 0x11EE7F  68d4030000     push
            cpu.push(0x3D4, 4)
            # 0x11EE84  e8e8580000     call
            emulate_call32(cpu, 0x124771, 0x11EE89)
            # 0x11EE89  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11EE8C  8b4514         mov
            _o = (sb["ss"] + r[5] + 0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11EE8F  c1e006         grp2
            cpu._shift(4, True, 0, 4, 0x06)
            # 0x11EE92  2500ff0000     and
            _a = r[0]
            _b = 0xFF00
            _r = _a & _b
            cpu._flags_logic(_r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11EE97  0c0d           or
            _a = cpu.reg(0, 1)
            _b = 0xD
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x11EE99  50             push
            cpu.push(r[0], 4)
            # 0x11EE9A  68d4030000     push
            cpu.push(0x3D4, 4)
            # 0x11EE9F  e8cd580000     call
            emulate_call32(cpu, 0x124771, 0x11EEA4)
            # 0x11EEA4  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x11EEA7  5d             pop
            r[5] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11EEA8  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11EEA9  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11EEAA  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x11EEAB  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_11ee65' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
