"""AUTOGENERATED by dos_re.lift (32-bit). DO NOT hand-edit in place.

Function 0x1185A4  (622 instructions, 146 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import CF, ZF
from dos_re.lift.runtime32 import (LiftRuntimeError, check_signature,
                                   emulate_call32, emulate_int32, interp_one32)

ENTRY = 0x1185A4
SIGNATURE = bytes.fromhex('5356575589e581ec')
MAX_ITERATIONS = 3110000


def lift_1185a4(cpu):
    """Lifted replacement for flat 0x1185A4."""
    check_signature(cpu, ENTRY, SIGNATURE, 'lift_1185a4')
    r, mem, sb = cpu.r, cpu.mem, cpu.sbase
    bb = 0
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            # 0x1185A4  53             push
            cpu.push(r[3], 4)
            # 0x1185A5  56             push
            cpu.push(r[6], 4)
            # 0x1185A6  57             push
            cpu.push(r[7], 4)
            # 0x1185A7  55             push
            cpu.push(r[5], 4)
            # 0x1185A8  89e5           mov
            r[5] = (r[4]) & 0xFFFFFFFF
            # 0x1185AA  81ec40000000   grp1
            _a = r[4]
            _b = 0x40
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1185B0  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1185B5  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1185B7  a34ce21400     mov
            _o = (sb["ds"] + 0x14E24C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1185BC  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1185C1  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1185C4  a350e21400     mov
            _o = (sb["ds"] + 0x14E250) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1185C9  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1185CE  ff7078         push
            _o = (sb["ds"] + r[0] + 0x78) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1185D1  b84ce21400     mov
            r[0] = (0x14E24C) & 0xFFFFFFFF
            # 0x1185D6  50             push
            cpu.push(r[0], 4)
            # 0x1185D7  e828faffff     call
            emulate_call32(cpu, 0x118004, 0x1185DC)
            # 0x1185DC  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1185DF  830550e2140003 grp1
            _o = (sb["ds"] + 0x14E250) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x3
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x1185E6  a150e21400     mov
            _o = (sb["ds"] + 0x14E250) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1185EB  83c00a         grp1
            _a = r[0]
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1185EE  a358e21400     mov
            _o = (sb["ds"] + 0x14E258) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1185F3  83054ce2140002 grp1
            _o = (sb["ds"] + 0x14E24C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x2
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x1185FA  832d54e2140002 grp1
            _o = (sb["ds"] + 0x14E254) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x2
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118601  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118606  8b4074         mov
            _o = (sb["ds"] + r[0] + 0x74) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118609  a33ce21400     mov
            _o = (sb["ds"] + 0x14E23C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x11860E  a1e0de1400     mov
            _o = (sb["ds"] + 0x14DEE0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118613  0536750000     add
            _a = r[0]
            _b = 0x7536
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118618  50             push
            cpu.push(r[0], 4)
            # 0x118619  b83ce21400     mov
            r[0] = (0x14E23C) & 0xFFFFFFFF
            # 0x11861E  50             push
            cpu.push(r[0], 4)
            # 0x11861F  e8e0f9ffff     call
            emulate_call32(cpu, 0x118004, 0x118624)
            # 0x118624  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118627  c705b4dd140078df1400 mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            mem.w32(_o, 0x14DF78)
            # 0x118631  c705acdd140000000000 mov
            _o = (sb["ds"] + 0x14DDAC) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 1
        elif bb == 1:
            # 0x11863B  a1acdd1400     mov
            _o = (sb["ds"] + 0x14DDAC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118640  3b05a8dd1400   cmp
            _o = (sb["ds"] + 0x14DDA8) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118646  7c0d           jcc
            bb = 4 if cpu._cond(0xC) else 2
        elif bb == 2:
            # 0x118648  e92c090000     jmp
            bb = 145
        elif bb == 3:
            # 0x11864D  ff05acdd1400   inc
            _o = (sb["ds"] + 0x14DDAC) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x118653  ebe6           jmp
            bb = 1
        elif bb == 4:
            # 0x118655  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11865A  0fb64010       movzx/sx
            _o = (sb["ds"] + r[0] + 0x10) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x11865E  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118663  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118668  f6401102       grp3
            interp_one32(cpu, 0x118668)  # (interpreter fallback)
            # 0x11866C  7439           jcc
            bb = 10 if cpu._cond(0x4) else 5
        elif bb == 5:
            # 0x11866E  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118673  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x118676  8b80305e1400   mov
            _o = (sb["ds"] + r[0] + 0x145E30) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11867C  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118681  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118686  f6400120       grp3
            interp_one32(cpu, 0x118686)  # (interpreter fallback)
            # 0x11868A  750e           jcc
            bb = 7 if cpu._cond(0x5) else 6
        elif bb == 6:
            # 0x11868C  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118691  81780480090000 grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x980
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118698  7f02           jcc
            bb = 8 if cpu._cond(0xF) else 7
        elif bb == 7:
            # 0x11869A  eb09           jmp
            bb = 9
        elif bb == 8:
            # 0x11869C  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186A1  806011fd       grp1
            _o = (sb["ds"] + r[0] + 0x11) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xFD
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 9
        elif bb == 9:
            # 0x1186A5  eb33           jmp
            bb = 13
        elif bb == 10:
            # 0x1186A7  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186AC  f6400110       grp3
            interp_one32(cpu, 0x1186AC)  # (interpreter fallback)
            # 0x1186B0  7415           jcc
            bb = 12 if cpu._cond(0x4) else 11
        elif bb == 11:
            # 0x1186B2  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186B7  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x1186BA  8b80f85d1400   mov
            _o = (sb["ds"] + r[0] + 0x145DF8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186C0  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1186C5  eb13           jmp
            bb = 13
        elif bb == 12:
            # 0x1186C7  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186CC  c1e003         grp2
            cpu._shift(4, True, 0, 4, 0x03)
            # 0x1186CF  8b80c05d1400   mov
            _o = (sb["ds"] + r[0] + 0x145DC0) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186D5  a3dc8d1400     mov
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 13
        elif bb == 13:
            # 0x1186DA  a134df1400     mov
            _o = (sb["ds"] + 0x14DF34) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186DF  0305dc8d1400   add
            _o = (sb["ds"] + 0x148DDC) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1186E5  8945ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1186E8  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186ED  f6401101       grp3
            interp_one32(cpu, 0x1186ED)  # (interpreter fallback)
            # 0x1186F1  7523           jcc
            bb = 15 if cpu._cond(0x5) else 14
        elif bb == 14:
            # 0x1186F3  8b15b4dd1400   mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186F9  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1186FE  8b5208         mov
            _o = (sb["ds"] + r[2] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118701  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118703  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118708  8b15b4dd1400   mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11870E  8b520c         mov
            _o = (sb["ds"] + r[2] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118711  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118714  eb6a           jmp
            bb = 21
        elif bb == 15:
            # 0x118716  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11871B  8b5004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11871E  c1e204         grp2
            cpu._shift(4, True, 2, 4, 0x04)
            # 0x118721  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118726  895004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118729  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11872E  f60002         grp3
            interp_one32(cpu, 0x11872E)  # (interpreter fallback)
            # 0x118731  7548           jcc
            bb = 20 if cpu._cond(0x5) else 16
        elif bb == 16:
            # 0x118733  66a1007c1400   mov
            _o = (sb["ds"] + 0x147C00) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x118739  663b05fe7b1400 cmp
            _o = (sb["ds"] + 0x147BFE) & 0xFFFFFFFF
            _a = r[0] & 0xFFFF
            _b = mem.r16(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 16)
            # 0x118740  7409           jcc
            bb = 18 if cpu._cond(0x4) else 17
        elif bb == 17:
            # 0x118742  f605fe7b140001 grp3
            interp_one32(cpu, 0x118742)  # (interpreter fallback)
            # 0x118749  750a           jcc
            bb = 19 if cpu._cond(0x5) else 18
        elif bb == 18:
            # 0x11874B  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118750  f60008         grp3
            interp_one32(cpu, 0x118750)  # (interpreter fallback)
            # 0x118753  7426           jcc
            bb = 20 if cpu._cond(0x4) else 19
        elif bb == 19:
            # 0x118755  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11875A  8b10           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11875C  c1e204         grp2
            cpu._shift(4, True, 2, 4, 0x04)
            # 0x11875F  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118764  0110           add
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118766  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11876B  806011fe       grp1
            _o = (sb["ds"] + r[0] + 0x11) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xFE
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x11876F  66a1fe7b1400   mov
            _o = (sb["ds"] + 0x147BFE) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x118775  66a3007c1400   mov
            _o = (sb["ds"] + 0x147C00) & 0xFFFFFFFF
            mem.w16(_o, r[0] & 0xFFFF)
            bb = 20
        elif bb == 20:
            # 0x11877B  e985070000     jmp
            bb = 142
        elif bb == 21:
            # 0x118780  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118785  813800140000   grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x1400
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x11878B  7f0a           jcc
            bb = 23 if cpu._cond(0xF) else 22
        elif bb == 22:
            # 0x11878D  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118792  833800         grp1
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118795  7d02           jcc
            bb = 24 if cpu._cond(0xD) else 23
        elif bb == 23:
            # 0x118797  eb0e           jmp
            bb = 25
        elif bb == 24:
            # 0x118799  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11879E  817804c00d0000 grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xDC0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1187A5  7e02           jcc
            bb = 26 if cpu._cond(0xE) else 25
        elif bb == 25:
            # 0x1187A7  eb0b           jmp
            bb = 27
        elif bb == 26:
            # 0x1187A9  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187AE  83780400       grp1
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1187B2  7d0a           jcc
            bb = 28 if cpu._cond(0xD) else 27
        elif bb == 27:
            # 0x1187B4  e8c5070000     call
            emulate_call32(cpu, 0x118F7E, 0x1187B9)
            # 0x1187B9  e98ffeffff     jmp
            bb = 3
        elif bb == 28:
            # 0x1187BE  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187C3  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187C5  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x1187C8  a32ce21400     mov
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1187CD  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187D2  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187D5  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x1187D8  a330e21400     mov
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x1187DD  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187E0  50             push
            cpu.push(r[0], 4)
            # 0x1187E1  b82ce21400     mov
            r[0] = (0x14E22C) & 0xFFFFFFFF
            # 0x1187E6  50             push
            cpu.push(r[0], 4)
            # 0x1187E7  e818f8ffff     call
            emulate_call32(cpu, 0x118004, 0x1187EC)
            # 0x1187EC  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1187EF  833d2ce2140010 grp1
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x10
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1187F6  7f17           jcc
            bb = 31 if cpu._cond(0xF) else 29
        elif bb == 29:
            # 0x1187F8  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1187FD  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118801  7d0c           jcc
            bb = 31 if cpu._cond(0xD) else 30
        elif bb == 30:
            # 0x118803  c705208e140010000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x10)
            # 0x11880D  eb45           jmp
            bb = 38
        elif bb == 31:
            # 0x11880F  813d34e2140030010000 grp1
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x130
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118819  7c17           jcc
            bb = 34 if cpu._cond(0xC) else 32
        elif bb == 32:
            # 0x11881B  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118820  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118824  7e0c           jcc
            bb = 34 if cpu._cond(0xE) else 33
        elif bb == 33:
            # 0x118826  c705208e140030010000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x130)
            # 0x118830  eb22           jmp
            bb = 38
        elif bb == 34:
            # 0x118832  833d30e2140018 grp1
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x18
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118839  7f17           jcc
            bb = 37 if cpu._cond(0xF) else 35
        elif bb == 35:
            # 0x11883B  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118840  83780c00       grp1
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118844  7d0c           jcc
            bb = 37 if cpu._cond(0xD) else 36
        elif bb == 36:
            # 0x118846  c7051c8e140018000000 mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            mem.w32(_o, 0x18)
            # 0x118850  eb26           jmp
            bb = 39
        elif bb == 37:
            # 0x118852  eb75           jmp
            bb = 41
        elif bb == 38:
            # 0x118854  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118859  8b5008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11885C  f7da           grp3
            interp_one32(cpu, 0x11885C)  # (interpreter fallback)
            # 0x11885E  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118863  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118866  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11886B  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11886E  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x118871  a31c8e1400     mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118876  eb21           jmp
            bb = 40
        elif bb == 39:
            # 0x118878  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11887D  8b500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118880  f7da           grp3
            interp_one32(cpu, 0x118880)  # (interpreter fallback)
            # 0x118882  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118887  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x11888A  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11888F  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118891  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x118894  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 40
        elif bb == 40:
            # 0x118899  6a24           push
            cpu.push(0x24, 4)
            # 0x11889B  e86d390000     call
            emulate_call32(cpu, 0x11C20D, 0x1188A0)
            # 0x1188A0  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1188A3  6a01           push
            cpu.push(0x1, 4)
            # 0x1188A5  b898601400     mov
            r[0] = (0x146098) & 0xFFFFFFFF
            # 0x1188AA  50             push
            cpu.push(r[0], 4)
            # 0x1188AB  ff3534df1400   push
            _o = (sb["ds"] + 0x14DF34) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1188B1  6a00           push
            cpu.push(0x0, 4)
            # 0x1188B3  6a00           push
            cpu.push(0x0, 4)
            # 0x1188B5  ff351c8e1400   push
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1188BB  ff35208e1400   push
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x1188C1  e89cf5ffff     call
            emulate_call32(cpu, 0x117E62, 0x1188C6)
            # 0x1188C6  83c41c         grp1
            _a = r[4]
            _b = 0x1C
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 41
        elif bb == 41:
            # 0x1188C9  813d30e21400be000000 grp1
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xBE
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1188D3  0f8f2c060000   jcc
            bb = 142 if cpu._cond(0xF) else 42
        elif bb == 42:
            # 0x1188D9  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1188DE  83780c00       grp1
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1188E2  0f8c9d020000   jcc
            bb = 86 if cpu._cond(0xC) else 43
        elif bb == 43:
            # 0x1188E8  a150e21400     mov
            _o = (sb["ds"] + 0x14E250) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1188ED  3b0538e21400   cmp
            _o = (sb["ds"] + 0x14E238) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1188F3  0f8f70010000   jcc
            bb = 70 if cpu._cond(0xF) else 44
        elif bb == 44:
            # 0x1188F9  a158e21400     mov
            _o = (sb["ds"] + 0x14E258) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1188FE  3b0530e21400   cmp
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118904  0f8c5f010000   jcc
            bb = 70 if cpu._cond(0xC) else 45
        elif bb == 45:
            # 0x11890A  a14ce21400     mov
            _o = (sb["ds"] + 0x14E24C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11890F  3b0534e21400   cmp
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118915  0f8ffb000000   jcc
            bb = 63 if cpu._cond(0xF) else 46
        elif bb == 46:
            # 0x11891B  a154e21400     mov
            _o = (sb["ds"] + 0x14E254) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118920  3b052ce21400   cmp
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118926  0f8cea000000   jcc
            bb = 63 if cpu._cond(0xC) else 47
        elif bb == 47:
            # 0x11892C  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118931  f60008         grp3
            interp_one32(cpu, 0x118931)  # (interpreter fallback)
            # 0x118934  7526           jcc
            bb = 51 if cpu._cond(0x5) else 48
        elif bb == 48:
            # 0x118936  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11893B  f60040         grp3
            interp_one32(cpu, 0x11893B)  # (interpreter fallback)
            # 0x11893E  741a           jcc
            bb = 50 if cpu._cond(0x4) else 49
        elif bb == 49:
            # 0x118940  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118945  8b10           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118947  c1e204         grp2
            cpu._shift(4, True, 2, 4, 0x04)
            # 0x11894A  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11894F  2910           sub
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118951  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118956  80481101       grp1
            _o = (sb["ds"] + r[0] + 0x11) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 50
        elif bb == 50:
            # 0x11895A  eb14           jmp
            bb = 53
        elif bb == 51:
            # 0x11895C  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118961  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118965  7509           jcc
            bb = 53 if cpu._cond(0x5) else 52
        elif bb == 52:
            # 0x118967  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11896C  83680804       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x4
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 53
        elif bb == 53:
            # 0x118970  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118975  0fb64010       movzx/sx
            _o = (sb["ds"] + r[0] + 0x10) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118979  d1f8           grp2
            cpu._shift(7, True, 0, 4, 1)
            # 0x11897B  24fe           and
            _a = cpu.reg(0, 1)
            _b = 0xFE
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            cpu.set_reg(0, 1, _r & 0xFF)
            # 0x11897D  83c003         grp1
            _a = r[0]
            _b = 0x3
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118980  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118985  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x11898A  f6401102       grp3
            interp_one32(cpu, 0x11898A)  # (interpreter fallback)
            # 0x11898E  7529           jcc
            bb = 55 if cpu._cond(0x5) else 54
        elif bb == 54:
            # 0x118990  66a1208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x118996  660105bce41400 add
            _o = (sb["ds"] + 0x14E4BC) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = r[0] & 0xFFFF
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            mem.w16(_o, _r & 0xFFFF)
            # 0x11899D  66a1208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1189A3  660105b4e41400 add
            _o = (sb["ds"] + 0x14E4B4) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = r[0] & 0xFFFF
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            mem.w16(_o, _r & 0xFFFF)
            # 0x1189AA  66a1208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (r[0] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x1189B0  660105b0e41400 add
            _o = (sb["ds"] + 0x14E4B0) & 0xFFFFFFFF
            _a = mem.r16(_o)
            _b = r[0] & 0xFFFF
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 16)
            mem.w16(_o, _r & 0xFFFF)
            # 0x1189B7  eb14           jmp
            bb = 57
        elif bb == 55:
            # 0x1189B9  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1189BE  f6400120       grp3
            interp_one32(cpu, 0x1189BE)  # (interpreter fallback)
            # 0x1189C2  7509           jcc
            bb = 57 if cpu._cond(0x5) else 56
        elif bb == 56:
            # 0x1189C4  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1189C9  806011fd       grp1
            _o = (sb["ds"] + r[0] + 0x11) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0xFD
            _r = _a & _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            bb = 57
        elif bb == 57:
            # 0x1189CD  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1189D2  f60080         grp3
            interp_one32(cpu, 0x1189D2)  # (interpreter fallback)
            # 0x1189D5  740c           jcc
            bb = 59 if cpu._cond(0x4) else 58
        elif bb == 58:
            # 0x1189D7  6a20           push
            cpu.push(0x20, 4)
            # 0x1189D9  e82f380000     call
            emulate_call32(cpu, 0x11C20D, 0x1189DE)
            # 0x1189DE  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1189E1  eb0a           jmp
            bb = 60
        elif bb == 59:
            # 0x1189E3  6a65           push
            cpu.push(0x65, 4)
            # 0x1189E5  e823380000     call
            emulate_call32(cpu, 0x11C20D, 0x1189EA)
            # 0x1189EA  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            bb = 60
        elif bb == 60:
            # 0x1189ED  a14ce21400     mov
            _o = (sb["ds"] + 0x14E24C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x1189F2  83c003         grp1
            _a = r[0]
            _b = 0x3
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x1189F5  3b0534e21400   cmp
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x1189FB  0f8d8c000000   jcc
            bb = 74 if cpu._cond(0xD) else 61
        elif bb == 61:
            # 0x118A01  a154e21400     mov
            _o = (sb["ds"] + 0x14E254) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A06  83e803         grp1
            _a = r[0]
            _b = 0x3
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118A09  3b052ce21400   cmp
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A0F  7e5d           jcc
            bb = 71 if cpu._cond(0xE) else 62
        elif bb == 62:
            # 0x118A11  e9bc000000     jmp
            bb = 77
        elif bb == 63:
            # 0x118A16  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A1B  f6400102       grp3
            interp_one32(cpu, 0x118A1B)  # (interpreter fallback)
            # 0x118A1F  740d           jcc
            bb = 65 if cpu._cond(0x4) else 64
        elif bb == 64:
            # 0x118A21  a13ce21400     mov
            _o = (sb["ds"] + 0x14E23C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A26  3b0534e21400   cmp
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A2C  7e02           jcc
            bb = 66 if cpu._cond(0xE) else 65
        elif bb == 65:
            # 0x118A2E  eb39           jmp
            bb = 70
        elif bb == 66:
            # 0x118A30  a144e21400     mov
            _o = (sb["ds"] + 0x14E244) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A35  3b052ce21400   cmp
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A3B  7c2c           jcc
            bb = 70 if cpu._cond(0xC) else 67
        elif bb == 67:
            # 0x118A3D  6a21           push
            cpu.push(0x21, 4)
            # 0x118A3F  e8c9370000     call
            emulate_call32(cpu, 0x11C20D, 0x118A44)
            # 0x118A44  83c404         grp1
            _a = r[4]
            _b = 0x4
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118A47  a13ce21400     mov
            _o = (sb["ds"] + 0x14E23C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A4C  83c003         grp1
            _a = r[0]
            _b = 0x3
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118A4F  3b0534e21400   cmp
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A55  7d36           jcc
            bb = 74 if cpu._cond(0xD) else 68
        elif bb == 68:
            # 0x118A57  a144e21400     mov
            _o = (sb["ds"] + 0x14E244) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A5C  83e803         grp1
            _a = r[0]
            _b = 0x3
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118A5F  3b052ce21400   cmp
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A65  7e07           jcc
            bb = 71 if cpu._cond(0xE) else 69
        elif bb == 69:
            # 0x118A67  eb69           jmp
            bb = 77
        elif bb == 70:
            # 0x118A69  e917010000     jmp
            bb = 86
        elif bb == 71:
            # 0x118A6E  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A73  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A77  7d12           jcc
            bb = 73 if cpu._cond(0xD) else 72
        elif bb == 72:
            # 0x118A79  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A7E  8b5008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A81  f7da           grp3
            interp_one32(cpu, 0x118A81)  # (interpreter fallback)
            # 0x118A83  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A88  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 73
        elif bb == 73:
            # 0x118A8B  eb1d           jmp
            bb = 76
        elif bb == 74:
            # 0x118A8D  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A92  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118A96  7e12           jcc
            bb = 76 if cpu._cond(0xE) else 75
        elif bb == 75:
            # 0x118A98  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118A9D  8b5008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AA0  f7da           grp3
            interp_one32(cpu, 0x118AA0)  # (interpreter fallback)
            # 0x118AA2  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AA7  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 76
        elif bb == 76:
            # 0x118AAA  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AAF  8b500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AB2  f7da           grp3
            interp_one32(cpu, 0x118AB2)  # (interpreter fallback)
            # 0x118AB4  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AB9  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118ABC  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AC1  8b15b4dd1400   mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AC7  8b520c         mov
            _o = (sb["ds"] + r[2] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118ACA  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118ACD  e9b3000000     jmp
            bb = 86
        elif bb == 77:
            # 0x118AD2  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AD7  8b500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118ADA  f7da           grp3
            interp_one32(cpu, 0x118ADA)  # (interpreter fallback)
            # 0x118ADC  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AE1  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118AE4  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AE9  8b15b4dd1400   mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AEF  8b520c         mov
            _o = (sb["ds"] + r[2] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AF2  015004         add
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118AF5  8b15e4de1400   mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118AFB  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B00  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B02  2b4208         sub
            _o = (sb["ds"] + r[2] + 0x8) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118B05  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118B0A  833d208e140018 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x18
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118B11  7e0a           jcc
            bb = 79 if cpu._cond(0xE) else 78
        elif bb == 78:
            # 0x118B13  c705208e140018000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x18)
            bb = 79
        elif bb == 79:
            # 0x118B1D  833d208e1400e8 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xFFFFFFE8
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118B24  7d0a           jcc
            bb = 81 if cpu._cond(0xD) else 80
        elif bb == 80:
            # 0x118B26  c705208e1400e8ffffff mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0xFFFFFFE8)
            bb = 81
        elif bb == 81:
            # 0x118B30  a1208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B35  01c0           add
            _a = r[0]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[0] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118B37  8b15208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B3D  d1fa           grp2
            cpu._shift(7, True, 2, 4, 1)
            # 0x118B3F  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118B41  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B46  8b4008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B49  01c2           add
            _a = r[2]
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[2] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118B4B  8915208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118B51  833d208e140020 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x20
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118B58  7e0a           jcc
            bb = 83 if cpu._cond(0xE) else 82
        elif bb == 82:
            # 0x118B5A  c705208e140020000000 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0x20)
            bb = 83
        elif bb == 83:
            # 0x118B64  833d208e1400e0 grp1
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xFFFFFFE0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118B6B  7d0a           jcc
            bb = 85 if cpu._cond(0xD) else 84
        elif bb == 84:
            # 0x118B6D  c705208e1400e0ffffff mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, 0xFFFFFFE0)
            bb = 85
        elif bb == 85:
            # 0x118B77  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B7C  8b15208e1400   mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B82  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 86
        elif bb == 86:
            # 0x118B85  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118B8A  f6401102       grp3
            interp_one32(cpu, 0x118B8A)  # (interpreter fallback)
            # 0x118B8E  0f8571030000   jcc
            bb = 142 if cpu._cond(0x5) else 87
        elif bb == 87:
            # 0x118B94  c70594dd140048a81400 mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            mem.w32(_o, 0x14A848)
            # 0x118B9E  c705c4dd140000000000 mov
            _o = (sb["ds"] + 0x14DDC4) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            bb = 88
        elif bb == 88:
            # 0x118BA8  a1c4dd1400     mov
            _o = (sb["ds"] + 0x14DDC4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118BAD  3b05ccdd1400   cmp
            _o = (sb["ds"] + 0x14DDCC) & 0xFFFFFFFF
            _a = r[0]
            _b = mem.r32(_o)
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118BB3  7c0d           jcc
            bb = 91 if cpu._cond(0xC) else 89
        elif bb == 89:
            # 0x118BB5  e918010000     jmp
            bb = 102
        elif bb == 90:
            # 0x118BBA  ff05c4dd1400   inc
            _o = (sb["ds"] + 0x14DDC4) & 0xFFFFFFFF
            _old = mem.r32(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 32)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w32(_o, _r)
            # 0x118BC0  ebe6           jmp
            bb = 88
        elif bb == 91:
            # 0x118BC2  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118BC7  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118BC9  a35ce21400     mov
            _o = (sb["ds"] + 0x14E25C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118BCE  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118BD3  8b4004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118BD6  a360e21400     mov
            _o = (sb["ds"] + 0x14E260) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118BDB  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118BE0  ff7010         push
            _o = (sb["ds"] + r[0] + 0x10) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x118BE3  b85ce21400     mov
            r[0] = (0x14E25C) & 0xFFFFFFFF
            # 0x118BE8  50             push
            cpu.push(r[0], 4)
            # 0x118BE9  e878f4ffff     call
            emulate_call32(cpu, 0x118066, 0x118BEE)
            # 0x118BEE  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118BF1  b85ce21400     mov
            r[0] = (0x14E25C) & 0xFFFFFFFF
            # 0x118BF6  50             push
            cpu.push(r[0], 4)
            # 0x118BF7  b82ce21400     mov
            r[0] = (0x14E22C) & 0xFFFFFFFF
            # 0x118BFC  50             push
            cpu.push(r[0], 4)
            # 0x118BFD  e8dd290000     call
            emulate_call32(cpu, 0x11B5DF, 0x118C02)
            # 0x118C02  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118C05  85c0           test
            cpu._flags_logic(r[0] & (r[0]), 32)
            # 0x118C07  0f84b9000000   jcc
            bb = 101 if cpu._cond(0x4) else 92
        elif bb == 92:
            # 0x118C0D  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C12  80482402       grp1
            _o = (sb["ds"] + r[0] + 0x24) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a | _b
            cpu._flags_logic(_r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x118C16  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C1B  c7402000000000 mov
            _o = (sb["ds"] + r[0] + 0x20) & 0xFFFFFFFF
            mem.w32(_o, 0x0)
            # 0x118C22  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C27  8b15b4dd1400   mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C2D  8b5208         mov
            _o = (sb["ds"] + r[2] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C30  c1fa04         grp2
            cpu._shift(7, True, 2, 4, 0x04)
            # 0x118C33  015008         add
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118C36  a194dd1400     mov
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C3B  8b15b4dd1400   mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C41  8b520c         mov
            _o = (sb["ds"] + r[2] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C44  c1fa04         grp2
            cpu._shift(7, True, 2, 4, 0x04)
            # 0x118C47  01500c         add
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[2]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118C4A  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C4F  f6400110       grp3
            interp_one32(cpu, 0x118C4F)  # (interpreter fallback)
            # 0x118C53  0f856d000000   jcc
            bb = 101 if cpu._cond(0x5) else 93
        elif bb == 93:
            # 0x118C59  f605248e140010 grp3
            interp_one32(cpu, 0x118C59)  # (interpreter fallback)
            # 0x118C60  7414           jcc
            bb = 95 if cpu._cond(0x4) else 94
        elif bb == 94:
            # 0x118C62  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C67  8b500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C6A  f7da           grp3
            interp_one32(cpu, 0x118C6A)  # (interpreter fallback)
            # 0x118C6C  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C71  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            # 0x118C74  eb12           jmp
            bb = 96
        elif bb == 95:
            # 0x118C76  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C7B  8b5008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C7E  f7da           grp3
            interp_one32(cpu, 0x118C7E)  # (interpreter fallback)
            # 0x118C80  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C85  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 96
        elif bb == 96:
            # 0x118C88  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C8D  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118C91  750b           jcc
            bb = 98 if cpu._cond(0x5) else 97
        elif bb == 97:
            # 0x118C93  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118C98  83680804       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x4
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118C9C  eb28           jmp
            bb = 101
        elif bb == 98:
            # 0x118C9E  c705b8dd140002000000 mov
            _o = (sb["ds"] + 0x14DDB8) & 0xFFFFFFFF
            mem.w32(_o, 0x2)
            # 0x118CA8  f605248e140001 grp3
            interp_one32(cpu, 0x118CA8)  # (interpreter fallback)
            # 0x118CAF  7406           jcc
            bb = 100 if cpu._cond(0x4) else 99
        elif bb == 99:
            # 0x118CB1  f71db8dd1400   grp3
            interp_one32(cpu, 0x118CB1)  # (interpreter fallback)
            bb = 100
        elif bb == 100:
            # 0x118CB7  c7051c8e140001000000 mov
            _o = (sb["ds"] + 0x148E1C) & 0xFFFFFFFF
            mem.w32(_o, 0x1)
            # 0x118CC1  e88d030000     call
            emulate_call32(cpu, 0x119053, 0x118CC6)
            bb = 101
        elif bb == 101:
            # 0x118CC6  830594dd140028 grp1
            _o = (sb["ds"] + 0x14DD94) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x28
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118CCD  e9e8feffff     jmp
            bb = 90
        elif bb == 102:
            # 0x118CD2  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118CD7  83780c00       grp1
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118CDB  7d32           jcc
            bb = 104 if cpu._cond(0xD) else 103
        elif bb == 103:
            # 0x118CDD  c645c401       mov
            _o = (sb["ss"] + r[5] + -0x3C) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118CE1  c645ce01       mov
            _o = (sb["ss"] + r[5] + -0x32) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118CE5  c645d800       mov
            _o = (sb["ss"] + r[5] + -0x28) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118CE9  c645e200       mov
            _o = (sb["ss"] + r[5] + -0x1E) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118CED  a12ce21400     mov
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118CF2  8945c6         mov
            _o = (sb["ss"] + r[5] + -0x3A) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118CF5  a130e21400     mov
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118CFA  8945ca         mov
            _o = (sb["ss"] + r[5] + -0x36) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118CFD  a134e21400     mov
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D02  8945d0         mov
            _o = (sb["ss"] + r[5] + -0x30) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D05  a130e21400     mov
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D0A  8945d4         mov
            _o = (sb["ss"] + r[5] + -0x2C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D0D  eb30           jmp
            bb = 105
        elif bb == 104:
            # 0x118D0F  c645c400       mov
            _o = (sb["ss"] + r[5] + -0x3C) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118D13  c645ce00       mov
            _o = (sb["ss"] + r[5] + -0x32) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118D17  c645d801       mov
            _o = (sb["ss"] + r[5] + -0x28) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118D1B  c645e201       mov
            _o = (sb["ss"] + r[5] + -0x1E) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118D1F  a134e21400     mov
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D24  8945da         mov
            _o = (sb["ss"] + r[5] + -0x26) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D27  a138e21400     mov
            _o = (sb["ds"] + 0x14E238) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D2C  8945de         mov
            _o = (sb["ss"] + r[5] + -0x22) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D2F  a12ce21400     mov
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D34  8945e4         mov
            _o = (sb["ss"] + r[5] + -0x1C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D37  a138e21400     mov
            _o = (sb["ds"] + 0x14E238) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D3C  8945e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 105
        elif bb == 105:
            # 0x118D3F  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D44  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118D48  7d2a           jcc
            bb = 107 if cpu._cond(0xD) else 106
        elif bb == 106:
            # 0x118D4A  8045c402       grp1
            _o = (sb["ss"] + r[5] + -0x3C) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x118D4E  8045e202       grp1
            _o = (sb["ss"] + r[5] + -0x1E) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x118D52  a12ce21400     mov
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D57  8945c6         mov
            _o = (sb["ss"] + r[5] + -0x3A) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D5A  a130e21400     mov
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D5F  8945ca         mov
            _o = (sb["ss"] + r[5] + -0x36) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D62  a12ce21400     mov
            _o = (sb["ds"] + 0x14E22C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D67  8945e4         mov
            _o = (sb["ss"] + r[5] + -0x1C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D6A  a138e21400     mov
            _o = (sb["ds"] + 0x14E238) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D6F  8945e8         mov
            _o = (sb["ss"] + r[5] + -0x18) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D72  eb33           jmp
            bb = 109
        elif bb == 107:
            # 0x118D74  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D79  83780800       grp1
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 32)
            # 0x118D7D  7e28           jcc
            bb = 109 if cpu._cond(0xE) else 108
        elif bb == 108:
            # 0x118D7F  8045ce02       grp1
            _o = (sb["ss"] + r[5] + -0x32) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x118D83  8045d802       grp1
            _o = (sb["ss"] + r[5] + -0x28) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 8)
            mem.w8(_o, _r & 0xFF)
            # 0x118D87  a134e21400     mov
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D8C  8945d0         mov
            _o = (sb["ss"] + r[5] + -0x30) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D8F  a130e21400     mov
            _o = (sb["ds"] + 0x14E230) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D94  8945d4         mov
            _o = (sb["ss"] + r[5] + -0x2C) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D97  a134e21400     mov
            _o = (sb["ds"] + 0x14E234) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118D9C  8945da         mov
            _o = (sb["ss"] + r[5] + -0x26) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118D9F  a138e21400     mov
            _o = (sb["ds"] + 0x14E238) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118DA4  8945de         mov
            _o = (sb["ss"] + r[5] + -0x22) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            bb = 109
        elif bb == 109:
            # 0x118DA7  c645fc00       mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118DAB  c70558dd1400ffffffff mov
            _o = (sb["ds"] + 0x14DD58) & 0xFFFFFFFF
            mem.w32(_o, 0xFFFFFFFF)
            # 0x118DB5  c7055cdd1400ffffffff mov
            _o = (sb["ds"] + 0x14DD5C) & 0xFFFFFFFF
            mem.w32(_o, 0xFFFFFFFF)
            # 0x118DBF  c645f400       mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            bb = 110
        elif bb == 110:
            # 0x118DC3  807df404       grp1
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x4
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118DC7  720d           jcc
            bb = 113 if cpu._cond(0x2) else 111
        elif bb == 111:
            # 0x118DC9  e977000000     jmp
            bb = 120
        elif bb == 112:
            # 0x118DCE  8a45f4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x118DD1  fe45f4         grp4
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _old = mem.r8(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w8(_o, _r)
            # 0x118DD4  ebed           jmp
            bb = 110
        elif bb == 113:
            # 0x118DD6  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118DDA  6bc00a         imul
            interp_one32(cpu, 0x118DDA)  # (interpreter fallback)
            # 0x118DDD  807c28c400     grp1
            _o = (sb["ds"] + r[5] + r[0] + -0x3C) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118DE2  7453           jcc
            bb = 118 if cpu._cond(0x4) else 114
        elif bb == 114:
            # 0x118DE4  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118DE8  6bc00a         imul
            interp_one32(cpu, 0x118DE8)  # (interpreter fallback)
            # 0x118DEB  ff7428ca       push
            _o = (sb["ds"] + r[5] + r[0] + -0x36) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x118DEF  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118DF3  6bc00a         imul
            interp_one32(cpu, 0x118DF3)  # (interpreter fallback)
            # 0x118DF6  ff7428c6       push
            _o = (sb["ds"] + r[5] + r[0] + -0x3A) & 0xFFFFFFFF
            cpu.push(mem.r32(_o), 4)
            # 0x118DFA  e8a4030000     call
            emulate_call32(cpu, 0x1191A3, 0x118DFF)
            # 0x118DFF  89c2           mov
            r[2] = (r[0]) & 0xFFFFFFFF
            # 0x118E01  83c408         grp1
            _a = r[4]
            _b = 0x8
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            r[4] = (_r & 0xFFFFFFFF) & 0xFFFFFFFF
            # 0x118E04  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118E08  6bc00a         imul
            interp_one32(cpu, 0x118E08)  # (interpreter fallback)
            # 0x118E0B  885428c5       mov
            _o = (sb["ds"] + r[5] + r[0] + -0x3B) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(2, 1))
            # 0x118E0F  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118E13  6bc00a         imul
            interp_one32(cpu, 0x118E13)  # (interpreter fallback)
            # 0x118E16  807c28c500     grp1
            _o = (sb["ds"] + r[5] + r[0] + -0x3B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E1B  7406           jcc
            bb = 116 if cpu._cond(0x4) else 115
        elif bb == 115:
            # 0x118E1D  8a45fc         mov
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x118E20  fe45fc         grp4
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _old = mem.r8(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w8(_o, _r)
            bb = 116
        elif bb == 116:
            # 0x118E23  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118E27  6bc00a         imul
            interp_one32(cpu, 0x118E27)  # (interpreter fallback)
            # 0x118E2A  807c28c503     grp1
            _o = (sb["ds"] + r[5] + r[0] + -0x3B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x3
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E2F  0f84d0000000   jcc
            bb = 142 if cpu._cond(0x4) else 117
        elif bb == 117:
            # 0x118E35  eb0c           jmp
            bb = 119
        elif bb == 118:
            # 0x118E37  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118E3B  6bc00a         imul
            interp_one32(cpu, 0x118E3B)  # (interpreter fallback)
            # 0x118E3E  c64428c500     mov
            _o = (sb["ds"] + r[5] + r[0] + -0x3B) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            bb = 119
        elif bb == 119:
            # 0x118E43  eb89           jmp
            bb = 112
        elif bb == 120:
            # 0x118E45  c645f800       mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118E49  c645f000       mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            # 0x118E4D  a15cde1400     mov
            _o = (sb["ds"] + 0x14DE5C) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118E52  f6400110       grp3
            interp_one32(cpu, 0x118E52)  # (interpreter fallback)
            # 0x118E56  0f85a9000000   jcc
            bb = 142 if cpu._cond(0x5) else 121
        elif bb == 121:
            # 0x118E5C  c645f400       mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            mem.w8(_o, 0x0)
            bb = 122
        elif bb == 122:
            # 0x118E60  807df404       grp1
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x4
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E64  720d           jcc
            bb = 125 if cpu._cond(0x2) else 123
        elif bb == 123:
            # 0x118E66  e96a000000     jmp
            bb = 138
        elif bb == 124:
            # 0x118E6B  8a45f4         mov
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x118E6E  fe45f4         grp4
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _old = mem.r8(_o)
            _cf = cpu.eflags & CF
            _r = _old + 1
            cpu._flags_add(_old, 1, _r, 8)
            cpu.eflags = (cpu.eflags & ~CF) | _cf
            mem.w8(_o, _r)
            # 0x118E71  ebed           jmp
            bb = 122
        elif bb == 125:
            # 0x118E73  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118E77  6bc00a         imul
            interp_one32(cpu, 0x118E77)  # (interpreter fallback)
            # 0x118E7A  807c28c500     grp1
            _o = (sb["ds"] + r[5] + r[0] + -0x3B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E7F  7452           jcc
            bb = 137 if cpu._cond(0x4) else 126
        elif bb == 126:
            # 0x118E81  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118E85  6bc00a         imul
            interp_one32(cpu, 0x118E85)  # (interpreter fallback)
            # 0x118E88  8a4428c4       mov
            _o = (sb["ds"] + r[5] + r[0] + -0x3C) & 0xFFFFFFFF
            cpu.set_reg(0, 1, mem.r8(_o))
            # 0x118E8C  8845c0         mov
            _o = (sb["ss"] + r[5] + -0x40) & 0xFFFFFFFF
            mem.w8(_o, cpu.reg(0, 1))
            # 0x118E8F  807dc002       grp1
            _o = (sb["ss"] + r[5] + -0x40) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E93  720e           jcc
            bb = 130 if cpu._cond(0x2) else 127
        elif bb == 127:
            # 0x118E95  807dc002       grp1
            _o = (sb["ss"] + r[5] + -0x40) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x2
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E99  7614           jcc
            bb = 132 if cpu._cond(0x6) else 128
        elif bb == 128:
            # 0x118E9B  807dc003       grp1
            _o = (sb["ss"] + r[5] + -0x40) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x3
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118E9F  7414           jcc
            bb = 133 if cpu._cond(0x4) else 129
        elif bb == 129:
            # 0x118EA1  eb30           jmp
            bb = 137
        elif bb == 130:
            # 0x118EA3  807dc001       grp1
            _o = (sb["ss"] + r[5] + -0x40) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118EA7  752a           jcc
            bb = 137 if cpu._cond(0x5) else 131
        elif bb == 131:
            # 0x118EA9  c645f001       mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118EAD  eb24           jmp
            bb = 137
        elif bb == 132:
            # 0x118EAF  c645f801       mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118EB3  eb1e           jmp
            bb = 137
        elif bb == 133:
            # 0x118EB5  807dfc01       grp1
            _o = (sb["ss"] + r[5] + -0x4) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118EB9  7518           jcc
            bb = 137 if cpu._cond(0x5) else 134
        elif bb == 134:
            # 0x118EBB  0fb645f4       movzx/sx
            _o = (sb["ss"] + r[5] + -0xC) & 0xFFFFFFFF
            _v = mem.r8(_o)
            r[0] = (_v) & 0xFFFFFFFF
            # 0x118EBF  6bc00a         imul
            interp_one32(cpu, 0x118EBF)  # (interpreter fallback)
            # 0x118EC2  807c28c501     grp1
            _o = (sb["ds"] + r[5] + r[0] + -0x3B) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x1
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118EC7  7506           jcc
            bb = 136 if cpu._cond(0x5) else 135
        elif bb == 135:
            # 0x118EC9  c645f001       mov
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            # 0x118ECD  eb04           jmp
            bb = 137
        elif bb == 136:
            # 0x118ECF  c645f801       mov
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            mem.w8(_o, 0x1)
            bb = 137
        elif bb == 137:
            # 0x118ED3  eb96           jmp
            bb = 124
        elif bb == 138:
            # 0x118ED5  807df800       grp1
            _o = (sb["ss"] + r[5] + -0x8) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118ED9  7412           jcc
            bb = 140 if cpu._cond(0x4) else 139
        elif bb == 139:
            # 0x118EDB  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118EE0  8b5008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118EE3  f7da           grp3
            interp_one32(cpu, 0x118EE3)  # (interpreter fallback)
            # 0x118EE5  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118EEA  895008         mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 140
        elif bb == 140:
            # 0x118EED  807df000       grp1
            _o = (sb["ss"] + r[5] + -0x10) & 0xFFFFFFFF
            _a = mem.r8(_o)
            _b = 0x0
            _r = _a - _b
            cpu._flags_sub(_a, _b, _r, 8)
            # 0x118EF1  7412           jcc
            bb = 142 if cpu._cond(0x4) else 141
        elif bb == 141:
            # 0x118EF3  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118EF8  8b500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118EFB  f7da           grp3
            interp_one32(cpu, 0x118EFB)  # (interpreter fallback)
            # 0x118EFD  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F02  89500c         mov
            _o = (sb["ds"] + r[0] + 0xC) & 0xFFFFFFFF
            mem.w32(_o, r[2])
            bb = 142
        elif bb == 142:
            # 0x118F05  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F0A  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F0C  c1f804         grp2
            cpu._shift(7, True, 0, 4, 0x04)
            # 0x118F0F  a3208e1400     mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118F14  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F19  f6401101       grp3
            interp_one32(cpu, 0x118F19)  # (interpreter fallback)
            # 0x118F1D  740d           jcc
            bb = 144 if cpu._cond(0x4) else 143
        elif bb == 143:
            # 0x118F1F  a1e4de1400     mov
            _o = (sb["ds"] + 0x14DEE4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F24  8b00           mov
            _o = (sb["ds"] + r[0]) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F26  0105208e1400   add
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = r[0]
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            bb = 144
        elif bb == 144:
            # 0x118F2C  8b15ece21400   mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F32  8b45ec         mov
            _o = (sb["ss"] + r[5] + -0x14) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F35  8902           mov
            _o = (sb["ds"] + r[2]) & 0xFFFFFFFF
            mem.w32(_o, r[0])
            # 0x118F37  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F3C  668b15208e1400 mov
            _o = (sb["ds"] + 0x148E20) & 0xFFFFFFFF
            r[2] = (r[2] & 0xFFFF0000) | ((mem.r16(_o)) & 0xFFFF)
            # 0x118F43  66895004       mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x118F47  a1b4dd1400     mov
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F4C  8b5004         mov
            _o = (sb["ds"] + r[0] + 0x4) & 0xFFFFFFFF
            r[2] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F4F  c1fa04         grp2
            cpu._shift(7, True, 2, 4, 0x04)
            # 0x118F52  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F57  66895006       mov
            _o = (sb["ds"] + r[0] + 0x6) & 0xFFFFFFFF
            mem.w16(_o, r[2] & 0xFFFF)
            # 0x118F5B  a1ece21400     mov
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            r[0] = (mem.r32(_o)) & 0xFFFFFFFF
            # 0x118F60  66c740080000   mov
            _o = (sb["ds"] + r[0] + 0x8) & 0xFFFFFFFF
            mem.w16(_o, 0x0)
            # 0x118F66  8305ece214000a grp1
            _o = (sb["ds"] + 0x14E2EC) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0xA
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118F6D  8305b4dd140012 grp1
            _o = (sb["ds"] + 0x14DDB4) & 0xFFFFFFFF
            _a = mem.r32(_o)
            _b = 0x12
            _r = _a + _b
            cpu._flags_add(_a, _b, _r, 32)
            mem.w32(_o, _r & 0xFFFFFFFF)
            # 0x118F74  e9d4f6ffff     jmp
            bb = 3
        elif bb == 145:
            # 0x118F79  c9             leave
            interp_one32(cpu, 0x118F79)  # (interpreter fallback)
            # 0x118F7A  5f             pop
            r[7] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118F7B  5e             pop
            r[6] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118F7C  5b             pop
            r[3] = (cpu.pop(4)) & 0xFFFFFFFF
            # 0x118F7D  c3             ret
            cpu.eip = cpu.pop(4)
            return
    raise LiftRuntimeError(
        'lift_1185a4' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')
